export type AccountType = "자산" | "부채" | "자본" | "수익" | "비용";

export interface Account {
  name: string;
  type: AccountType;
  standards: string[];
}

export const ACCOUNTS: Account[] = [
  // 자산
  { name: "현금", type: "자산", standards: ["common"] },
  { name: "보통예금", type: "자산", standards: ["common"] },
  { name: "당좌예금", type: "자산", standards: ["common"] },
  { name: "받을어음", type: "자산", standards: ["common"] },
  { name: "외상매출금", type: "자산", standards: ["common"] },
  { name: "매출채권", type: "자산", standards: ["k-ifrs"] },
  { name: "미수금", type: "자산", standards: ["common"] },
  { name: "선급금", type: "자산", standards: ["common"] },
  { name: "선급비용", type: "자산", standards: ["common"] },
  { name: "상품", type: "자산", standards: ["common"] },
  { name: "재고자산", type: "자산", standards: ["k-ifrs"] },
  { name: "제품", type: "자산", standards: ["common"] },
  { name: "원재료", type: "자산", standards: ["common"] },
  { name: "건물", type: "자산", standards: ["common"] },
  { name: "토지", type: "자산", standards: ["common"] },
  { name: "비품", type: "자산", standards: ["common"] },
  { name: "차량운반구", type: "자산", standards: ["common"] },
  { name: "기계장치", type: "자산", standards: ["common"] },
  { name: "단기대여금", type: "자산", standards: ["common"] },
  { name: "미수수익", type: "자산", standards: ["common"] },
  { name: "투자부동산", type: "자산", standards: ["k-ifrs"] },
  { name: "사용권자산", type: "자산", standards: ["k-ifrs"] },
  // 부채
  { name: "지급어음", type: "부채", standards: ["common"] },
  { name: "외상매입금", type: "부채", standards: ["common"] },
  { name: "매입채무", type: "부채", standards: ["k-ifrs"] },
  { name: "미지급금", type: "부채", standards: ["common"] },
  { name: "미지급비용", type: "부채", standards: ["common"] },
  { name: "선수금", type: "부채", standards: ["common"] },
  { name: "선수수익", type: "부채", standards: ["common"] },
  { name: "단기차입금", type: "부채", standards: ["common"] },
  { name: "장기차입금", type: "부채", standards: ["common"] },
  { name: "예수금", type: "부채", standards: ["common"] },
  { name: "부가세예수금", type: "부채", standards: ["common"] },
  { name: "리스부채", type: "부채", standards: ["k-ifrs"] },
  { name: "충당부채", type: "부채", standards: ["k-ifrs", "common"] },
  // 자본
  { name: "자본금", type: "자본", standards: ["common"] },
  { name: "이익잉여금", type: "자본", standards: ["common"] },
  { name: "인출금", type: "자본", standards: ["common"] },
  { name: "기타포괄손익누계액", type: "자본", standards: ["k-ifrs"] },
  // 수익
  { name: "매출", type: "수익", standards: ["common"] },
  { name: "이자수익", type: "수익", standards: ["common"] },
  { name: "임대료수익", type: "수익", standards: ["common"] },
  { name: "수수료수익", type: "수익", standards: ["common"] },
  { name: "유형자산처분이익", type: "수익", standards: ["common"] },
  // 비용
  { name: "매출원가", type: "비용", standards: ["common"] },
  { name: "급여", type: "비용", standards: ["common"] },
  { name: "임차료", type: "비용", standards: ["common"] },
  { name: "보험료", type: "비용", standards: ["common"] },
  { name: "접대비", type: "비용", standards: ["common"] },
  { name: "통신비", type: "비용", standards: ["common"] },
  { name: "수도광열비", type: "비용", standards: ["common"] },
  { name: "소모품비", type: "비용", standards: ["common"] },
  { name: "감가상각비", type: "비용", standards: ["common"] },
  { name: "이자비용", type: "비용", standards: ["common"] },
  { name: "세금과공과", type: "비용", standards: ["common"] },
  { name: "광고선전비", type: "비용", standards: ["common"] },
  { name: "운반비", type: "비용", standards: ["common"] },
  { name: "수선비", type: "비용", standards: ["common"] },
  { name: "여비교통비", type: "비용", standards: ["common"] },
  { name: "복리후생비", type: "비용", standards: ["common"] },
  { name: "유형자산처분손실", type: "비용", standards: ["common"] },
  { name: "제품보증비", type: "비용", standards: ["k-ifrs"] },
  { name: "대손상각비", type: "비용", standards: ["common", "k-ifrs"] },
  { name: "재고자산평가손실", type: "비용", standards: ["k-ifrs"] },
  // batch1 추가 계정
  { name: "소모품", type: "자산", standards: ["common"] },
  { name: "대손충당금", type: "자산", standards: ["common", "k-ifrs"] },
  { name: "선급법인세", type: "자산", standards: ["common"] },
  { name: "당기손익-공정가치측정금융자산", type: "자산", standards: ["k-ifrs"] },
  { name: "매도가능금융자산", type: "자산", standards: ["k-ifrs"] },
  { name: "특허권", type: "자산", standards: ["k-ifrs"] },
  { name: "개발비", type: "자산", standards: ["k-ifrs"] },
  { name: "무형자산", type: "자산", standards: ["k-ifrs"] },
  { name: "유형자산", type: "자산", standards: ["k-ifrs"] },
  { name: "자기주식", type: "자본", standards: ["k-ifrs"] },
  { name: "투자자산", type: "자산", standards: ["k-ifrs"] },
  { name: "미지급배당금", type: "부채", standards: ["common"] },
  { name: "미지급세금", type: "부채", standards: ["common"] },
  { name: "사채", type: "부채", standards: ["k-ifrs"] },
  { name: "전환사채", type: "부채", standards: ["k-ifrs"] },
  { name: "확정급여채무", type: "부채", standards: ["k-ifrs"] },
  { name: "퇴직급여충당부채", type: "부채", standards: ["k-ifrs"] },
  { name: "이연정부보조금", type: "부채", standards: ["k-ifrs"] },
  { name: "주식선택권", type: "자본", standards: ["k-ifrs"] },
  { name: "주식발행초과금", type: "자본", standards: ["k-ifrs"] },
  { name: "재평가잉여금", type: "자본", standards: ["k-ifrs"] },
  { name: "금융자산평가이익", type: "수익", standards: ["k-ifrs"] },
  { name: "유형자산평가이익", type: "수익", standards: ["k-ifrs"] },
  { name: "투자부동산평가이익", type: "수익", standards: ["k-ifrs"] },
  { name: "정부보조금수익", type: "수익", standards: ["k-ifrs"] },
  { name: "외환차익", type: "수익", standards: ["k-ifrs"] },
  { name: "수수료비용", type: "비용", standards: ["common"] },
  { name: "법인세비용", type: "비용", standards: ["common"] },
  { name: "연구비", type: "비용", standards: ["k-ifrs"] },
  { name: "퇴직급여", type: "비용", standards: ["k-ifrs"] },
  { name: "매출채권처분손실", type: "비용", standards: ["k-ifrs"] },
  { name: "손상차손", type: "비용", standards: ["k-ifrs"] },
  { name: "외환차손", type: "비용", standards: ["k-ifrs"] },
  { name: "주식보상비용", type: "비용", standards: ["k-ifrs"] },
  { name: "기타포괄손익", type: "자본", standards: ["k-ifrs"] },
  { name: "미실현이익", type: "수익", standards: ["k-ifrs"] },
  // batch2 추가 계정
  { name: "매출액", type: "수익", standards: ["common"] },
  { name: "감가상각누계액", type: "자산", standards: ["common"] },
  { name: "매도가능증권", type: "자산", standards: ["general"] },
  { name: "단기매매증권", type: "자산", standards: ["general"] },
  { name: "만기보유증권", type: "자산", standards: ["general"] },
  { name: "단기매매증권평가이익", type: "수익", standards: ["general"] },
  { name: "매도가능증권평가이익", type: "자본", standards: ["general"] },
  { name: "매도가능증권처분이익", type: "수익", standards: ["general"] },
  { name: "잡손실", type: "비용", standards: ["common"] },
  { name: "경상개발비", type: "비용", standards: ["general"] },
  { name: "영업권", type: "자산", standards: ["general"] },
  { name: "사채할인발행차금", type: "부채", standards: ["general"] },
  { name: "무형자산상각비", type: "비용", standards: ["general"] },
  { name: "재고자산평가충당금", type: "자산", standards: ["general"] },
  { name: "리스자산", type: "자산", standards: ["general"] },
  { name: "대손충당금환입", type: "수익", standards: ["general"] },
  { name: "사채발행비", type: "비용", standards: ["general"] },
  // 은행업
  { name: "요구불예금", type: "부채", standards: ["bank"] },
  { name: "저축성예금", type: "부채", standards: ["bank"] },
  { name: "대출금", type: "자산", standards: ["bank"] },
  { name: "미수이자", type: "자산", standards: ["bank"] },
  { name: "신용손실충당금", type: "자산", standards: ["bank"] },
  { name: "지급준비금", type: "자산", standards: ["bank"] },
  { name: "예치금", type: "자산", standards: ["bank"] },
  { name: "유가증권", type: "자산", standards: ["bank"] },
  { name: "타행환", type: "자산", standards: ["bank"] },
  { name: "외화자산", type: "자산", standards: ["bank"] },
  { name: "양도성예금증서", type: "부채", standards: ["bank"] },
  { name: "파생금융자산", type: "자산", standards: ["bank"] },
  { name: "파생상품평가이익", type: "수익", standards: ["bank"] },
  { name: "환매조건부채권매도", type: "부채", standards: ["bank"] },
  { name: "후순위채권", type: "부채", standards: ["bank"] },
  { name: "부실채권", type: "자산", standards: ["bank"] },
  { name: "콜론", type: "자산", standards: ["bank"] },
  { name: "콜머니", type: "부채", standards: ["bank"] },
  { name: "영업수익", type: "수익", standards: ["bank"] },
  // 공공기관
  { name: "공채", type: "부채", standards: ["public"] },
  { name: "발전설비", type: "자산", standards: ["public"] },
  { name: "인건비", type: "비용", standards: ["public"] },
  { name: "환경비용", type: "비용", standards: ["public"] },
  { name: "복구원가", type: "자산", standards: ["public"] },
  { name: "복구충당부채", type: "부채", standards: ["public"] },
  { name: "자산수증이익", type: "수익", standards: ["public"] },
  // batch3 추가 계정
  { name: "사채할증발행차금", type: "부채", standards: ["k-ifrs"] },
  { name: "사외적립자산", type: "자산", standards: ["k-ifrs"] },
  { name: "기타포괄손익-재측정요소", type: "자본", standards: ["k-ifrs"] },
  { name: "순자산", type: "자본", standards: ["public"] },
  { name: "FVOCI금융자산", type: "자산", standards: ["k-ifrs"] },
  { name: "기타포괄손익-FVOCI평가이익", type: "자본", standards: ["k-ifrs"] },
  { name: "이연법인세자산", type: "자산", standards: ["k-ifrs"] },
  { name: "이연법인세부채", type: "부채", standards: ["k-ifrs"] },
  { name: "금융보증비용", type: "비용", standards: ["k-ifrs"] },
  { name: "금융보증부채", type: "부채", standards: ["k-ifrs"] },
  { name: "기타포괄손익-위험회피적립금", type: "자본", standards: ["k-ifrs"] },
  { name: "당기손익", type: "수익", standards: ["k-ifrs"] },
  { name: "손상차손환입", type: "수익", standards: ["k-ifrs"] },
  { name: "계약부채", type: "부채", standards: ["k-ifrs"] },
  { name: "재고자산평가손실환입", type: "수익", standards: ["k-ifrs"] },
  { name: "재평가손실", type: "비용", standards: ["k-ifrs"] },
  { name: "자기주식처분이익", type: "자본", standards: ["k-ifrs"] },
  { name: "손익", type: "수익", standards: ["common"] },
  { name: "배당금", type: "비용", standards: ["common"] },
  { name: "현금과부족", type: "자산", standards: ["common"] },
  { name: "잡이익", type: "수익", standards: ["common"] },
  { name: "재해손실", type: "비용", standards: ["common"] },
  { name: "단기금융상품", type: "자산", standards: ["common"] },
  { name: "현금성자산", type: "자산", standards: ["common"] },
  { name: "장기금융상품", type: "자산", standards: ["common"] },
  { name: "유동성장기부채", type: "부채", standards: ["common"] },
  { name: "전기오류수정손실", type: "비용", standards: ["common"] },
  { name: "사채상환손실", type: "비용", standards: ["common"] },
  { name: "기부금", type: "비용", standards: ["common"] },
  { name: "기타비용", type: "비용", standards: ["common"] },
  { name: "임대보증금", type: "부채", standards: ["common"] },
  { name: "제조원가-급여", type: "비용", standards: ["common"] },
  { name: "판매비-급여", type: "비용", standards: ["common"] },
  { name: "단기매매증권처분이익", type: "수익", standards: ["general"] },
  { name: "유가증권처분이익", type: "수익", standards: ["general"] },
  { name: "지분법적용투자주식", type: "자산", standards: ["general"] },
  { name: "지분법이익", type: "수익", standards: ["general"] },
  { name: "배당수익", type: "수익", standards: ["common"] },
  { name: "무형자산손상차손", type: "비용", standards: ["general"] },
  { name: "장기성매출채권", type: "자산", standards: ["general"] },
  { name: "결손금", type: "자본", standards: ["general"] },
  { name: "재고자산감모손실", type: "비용", standards: ["general"] },
  { name: "전환권대가", type: "자본", standards: ["k-ifrs"] },
  // batch4 추가 계정 - 은행업
  { name: "신탁유가증권", type: "자산", standards: ["bank"] },
  { name: "신탁원본", type: "부채", standards: ["bank"] },
  { name: "선수이자", type: "부채", standards: ["bank"] },
  { name: "외화대출금", type: "자산", standards: ["bank"] },
  { name: "외화환산이익", type: "수익", standards: ["bank"] },
  { name: "외화환산손실", type: "비용", standards: ["bank"] },
  { name: "파생상품평가손실", type: "비용", standards: ["bank"] },
  { name: "파생금융부채", type: "부채", standards: ["bank"] },
  { name: "외화예금", type: "부채", standards: ["bank"] },
  { name: "한국은행차입금", type: "부채", standards: ["bank"] },
  { name: "가맹점채무", type: "부채", standards: ["bank"] },
  { name: "신용카드수수료수익", type: "수익", standards: ["bank"] },
  { name: "주식", type: "자산", standards: ["bank"] },
  { name: "보증수수료수익", type: "수익", standards: ["bank"] },
  { name: "은행채", type: "부채", standards: ["bank"] },
  { name: "외화현금", type: "자산", standards: ["bank"] },
  { name: "부실채권매각이익", type: "수익", standards: ["bank"] },
  { name: "유동화증권부채", type: "부채", standards: ["bank"] },
  { name: "ABS발행이익", type: "수익", standards: ["bank"] },
  // batch4 추가 계정 - 공공기관
  { name: "성과급", type: "비용", standards: ["public"] },
  { name: "자본잉여금", type: "자본", standards: ["public", "common"] },
  { name: "인프라자산", type: "자산", standards: ["public"] },
  { name: "연체료수익", type: "수익", standards: ["public"] },
  { name: "소프트웨어", type: "자산", standards: ["public"] },
  // batch4 추가 계정 - K-IFRS
  { name: "계약자산", type: "자산", standards: ["k-ifrs"] },
  { name: "포인트비용", type: "비용", standards: ["k-ifrs"] },
  { name: "환불부채", type: "부채", standards: ["k-ifrs"] },
  { name: "미청구공사", type: "자산", standards: ["k-ifrs"] },
  { name: "공사수익", type: "수익", standards: ["k-ifrs"] },
  { name: "종속기업투자주식", type: "자산", standards: ["k-ifrs"] },
  { name: "지분법손실", type: "비용", standards: ["k-ifrs"] },
  { name: "리스채권", type: "자산", standards: ["k-ifrs"] },
  { name: "건설중인자산", type: "자산", standards: ["k-ifrs", "common"] },
  { name: "자산", type: "자산", standards: ["common"] },
  { name: "기타포괄손익-해외사업환산차이", type: "자본", standards: ["k-ifrs"] },
  // batch4 추가 계정 - 공통
  { name: "가지급금", type: "자산", standards: ["common"] },
  { name: "인쇄비", type: "비용", standards: ["common"] },
  { name: "사무용품비", type: "비용", standards: ["common"] },
  { name: "임차보증금", type: "자산", standards: ["common"] },
];

export const ACCOUNT_TYPE_STYLE: Record<AccountType, string> = {
  자산: "bg-asset-bg text-asset border-asset/30",
  부채: "bg-liability-bg text-liability border-liability/30",
  자본: "bg-equity-bg text-equity border-equity/30",
  수익: "bg-revenue-bg text-revenue border-revenue/30",
  비용: "bg-expense-bg text-expense border-expense/30",
};
