export type AccountType = "자산" | "부채" | "자본" | "수익" | "비용";

export interface Account {
  name: string;
  type: AccountType;
  standards: string[];
}

export const ACCOUNTS: Account[] = [
  // 자산
  { name: "현금", type: "자산", standards: ["common"] },
  { name: "보통예금", type: "자산", standards: ["common"] },
  { name: "당좌예금", type: "자산", standards: ["common"] },
  { name: "받을어음", type: "자산", standards: ["common"] },
  { name: "외상매출금", type: "자산", standards: ["common"] },
  { name: "매출채권", type: "자산", standards: ["k-ifrs"] },
  { name: "미수금", type: "자산", standards: ["common"] },
  { name: "선급금", type: "자산", standards: ["common"] },
  { name: "선급비용", type: "자산", standards: ["common"] },
  { name: "상품", type: "자산", standards: ["common"] },
  { name: "재고자산", type: "자산", standards: ["k-ifrs"] },
  { name: "제품", type: "자산", standards: ["common"] },
  { name: "원재료", type: "자산", standards: ["common"] },
  { name: "건물", type: "자산", standards: ["common"] },
  { name: "토지", type: "자산", standards: ["common"] },
  { name: "비품", type: "자산", standards: ["common"] },
  { name: "차량운반구", type: "자산", standards: ["common"] },
  { name: "기계장치", type: "자산", standards: ["common"] },
  { name: "단기대여금", type: "자산", standards: ["common"] },
  { name: "미수수익", type: "자산", standards: ["common"] },
  { name: "투자부동산", type: "자산", standards: ["k-ifrs"] },
  { name: "사용권자산", type: "자산", standards: ["k-ifrs"] },
  // 부채
  { name: "지급어음", type: "부채", standards: ["common"] },
  { name: "외상매입금", type: "부채", standards: ["common"] },
  { name: "매입채무", type: "부채", standards: ["k-ifrs"] },
  { name: "미지급금", type: "부채", standards: ["common"] },
  { name: "미지급비용", type: "부채", standards: ["common"] },
  { name: "선수금", type: "부채", standards: ["common"] },
  { name: "선수수익", type: "부채", standards: ["common"] },
  { name: "단기차입금", type: "부채", standards: ["common"] },
  { name: "장기차입금", type: "부채", standards: ["common"] },
  { name: "예수금", type: "부채", standards: ["common"] },
  { name: "부가세예수금", type: "부채", standards: ["common"] },
  { name: "리스부채", type: "부채", standards: ["k-ifrs"] },
  { name: "충당부채", type: "부채", standards: ["k-ifrs", "common"] },
  // 자본
  { name: "자본금", type: "자본", standards: ["common"] },
  { name: "이익잉여금", type: "자본", standards: ["common"] },
  { name: "인출금", type: "자본", standards: ["common"] },
  { name: "기타포괄손익누계액", type: "자본", standards: ["k-ifrs"] },
  // 수익
  { name: "매출", type: "수익", standards: ["common"] },
  { name: "이자수익", type: "수익", standards: ["common"] },
  { name: "임대료수익", type: "수익", standards: ["common"] },
  { name: "수수료수익", type: "수익", standards: ["common"] },
  { name: "유형자산처분이익", type: "수익", standards: ["common"] },
  // 비용
  { name: "매출원가", type: "비용", standards: ["common"] },
  { name: "급여", type: "비용", standards: ["common"] },
  { name: "임차료", type: "비용", standards: ["common"] },
  { name: "보험료", type: "비용", standards: ["common"] },
  { name: "접대비", type: "비용", standards: ["common"] },
  { name: "통신비", type: "비용", standards: ["common"] },
  { name: "수도광열비", type: "비용", standards: ["common"] },
  { name: "소모품비", type: "비용", standards: ["common"] },
  { name: "감가상각비", type: "비용", standards: ["common"] },
  { name: "이자비용", type: "비용", standards: ["common"] },
  { name: "세금과공과", type: "비용", standards: ["common"] },
  { name: "광고선전비", type: "비용", standards: ["common"] },
  { name: "운반비", type: "비용", standards: ["common"] },
  { name: "수선비", type: "비용", standards: ["common"] },
  { name: "여비교통비", type: "비용", standards: ["common"] },
  { name: "복리후생비", type: "비용", standards: ["common"] },
  { name: "유형자산처분손실", type: "비용", standards: ["common"] },
  { name: "제품보증비", type: "비용", standards: ["k-ifrs"] },
  { name: "대손상각비", type: "비용", standards: ["common", "k-ifrs"] },
  { name: "재고자산평가손실", type: "비용", standards: ["k-ifrs"] },
  // batch1 추가 계정
  { name: "소모품", type: "자산", standards: ["common"] },
  { name: "대손충당금", type: "자산", standards: ["common", "k-ifrs"] },
  { name: "선급법인세", type: "자산", standards: ["common"] },
  { name: "당기손익-공정가치측정금융자산", type: "자산", standards: ["k-ifrs"] },
  { name: "매도가능금융자산", type: "자산", standards: ["k-ifrs"] },
  { name: "특허권", type: "자산", standards: ["k-ifrs"] },
  { name: "개발비", type: "자산", standards: ["k-ifrs"] },
  { name: "무형자산", type: "자산", standards: ["k-ifrs"] },
  { name: "유형자산", type: "자산", standards: ["k-ifrs"] },
  { name: "자기주식", type: "자본", standards: ["k-ifrs"] },
  { name: "투자자산", type: "자산", standards: ["k-ifrs"] },
  { name: "미지급배당금", type: "부채", standards: ["common"] },
  { name: "미지급세금", type: "부채", standards: ["common"] },
  { name: "사채", type: "부채", standards: ["k-ifrs"] },
  { name: "전환사채", type: "부채", standards: ["k-ifrs"] },
  { name: "확정급여채무", type: "부채", standards: ["k-ifrs"] },
  { name: "퇴직급여충당부채", type: "부채", standards: ["k-ifrs"] },
  { name: "이연정부보조금", type: "부채", standards: ["k-ifrs"] },
  { name: "주식선택권", type: "자본", standards: ["k-ifrs"] },
  { name: "주식발행초과금", type: "자본", standards: ["k-ifrs"] },
  { name: "재평가잉여금", type: "자본", standards: ["k-ifrs"] },
  { name: "금융자산평가이익", type: "수익", standards: ["k-ifrs"] },
  { name: "유형자산평가이익", type: "수익", standards: ["k-ifrs"] },
  { name: "투자부동산평가이익", type: "수익", standards: ["k-ifrs"] },
  { name: "정부보조금수익", type: "수익", standards: ["k-ifrs"] },
  { name: "외환차익", type: "수익", standards: ["k-ifrs"] },
  { name: "수수료비용", type: "비용", standards: ["common"] },
  { name: "법인세비용", type: "비용", standards: ["common"] },
  { name: "연구비", type: "비용", standards: ["k-ifrs"] },
  { name: "퇴직급여", type: "비용", standards: ["k-ifrs"] },
  { name: "매출채권처분손실", type: "비용", standards: ["k-ifrs"] },
  { name: "손상차손", type: "비용", standards: ["k-ifrs"] },
  { name: "외환차손", type: "비용", standards: ["k-ifrs"] },
  { name: "주식보상비용", type: "비용", standards: ["k-ifrs"] },
  { name: "기타포괄손익", type: "자본", standards: ["k-ifrs"] },
  { name: "미실현이익", type: "수익", standards: ["k-ifrs"] },
];

export const ACCOUNT_TYPE_STYLE: Record<AccountType, string> = {
  자산: "bg-asset-bg text-asset border-asset/30",
  부채: "bg-liability-bg text-liability border-liability/30",
  자본: "bg-equity-bg text-equity border-equity/30",
  수익: "bg-revenue-bg text-revenue border-revenue/30",
  비용: "bg-expense-bg text-expense border-expense/30",
};
