export interface JournalEntry {
  account: string;
  amount: number;
}

export interface Problem {
  id: string;
  type: "journal" | "ox" | "calculation" | "statement";
  standard: string;
  category: string;
  difficulty: "basic" | "intermediate" | "advanced" | "practical";
  text: string;
  // 분개형
  debit?: JournalEntry[];
  credit?: JournalEntry[];
  distractors?: string[];
  // OX형
  answer?: boolean;
  // 계산형
  correctAnswer?: number;
  // 공통
  explanation: string;
  hint?: string;
}

export const PROBLEMS: Problem[] = [
  // ══════════════════════════════════════
  // common / journal-basic (20개)
  // ══════════════════════════════════════
  {
    id: "cjb01", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "현금 500,000원을 출자하여 사업을 개시하였다.",
    debit: [{ account: "현금", amount: 500000 }],
    credit: [{ account: "자본금", amount: 500000 }],
    explanation: "사업주가 현금을 출자하면 자산(현금) 증가, 자본(자본금) 증가.",
    distractors: ["보통예금", "이익잉여금", "선수금"],
  },
  {
    id: "cjb02", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 1,000,000원을 현금으로 매입하였다.",
    debit: [{ account: "상품", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    explanation: "상품(자산) 증가, 현금(자산) 감소.",
    distractors: ["매출원가", "외상매입금", "선급금"],
  },
  {
    id: "cjb03", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 800,000원을 현금으로 판매하였다.",
    debit: [{ account: "현금", amount: 800000 }],
    credit: [{ account: "매출", amount: 800000 }],
    explanation: "현금(자산) 증가, 매출(수익) 발생.",
    distractors: ["외상매출금", "선수금", "매출원가"],
  },
  {
    id: "cjb04", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 1,500,000원을 외상으로 매입하였다.",
    debit: [{ account: "상품", amount: 1500000 }],
    credit: [{ account: "외상매입금", amount: 1500000 }],
    explanation: "외상 매입: 상품(자산) 증가, 외상매입금(부채) 증가.",
    distractors: ["미지급금", "지급어음", "선수금"],
  },
  {
    id: "cjb05", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 2,000,000원을 외상으로 판매하였다.",
    debit: [{ account: "외상매출금", amount: 2000000 }],
    credit: [{ account: "매출", amount: 2000000 }],
    explanation: "외상 판매: 외상매출금(자산) 증가, 매출(수익) 발생.",
    distractors: ["미수금", "받을어음", "선급금"],
  },
  {
    id: "cjb06", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "외상매입금 1,500,000원을 현금으로 지급하였다.",
    debit: [{ account: "외상매입금", amount: 1500000 }],
    credit: [{ account: "현금", amount: 1500000 }],
    explanation: "외상매입금(부채) 감소, 현금(자산) 감소.",
    distractors: ["미지급금", "지급어음", "상품"],
  },
  {
    id: "cjb07", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "외상매출금 2,000,000원을 현금으로 회수하였다.",
    debit: [{ account: "현금", amount: 2000000 }],
    credit: [{ account: "외상매출금", amount: 2000000 }],
    explanation: "현금(자산) 증가, 외상매출금(자산) 감소.",
    distractors: ["미수금", "받을어음", "매출"],
  },
  {
    id: "cjb08", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "은행에서 3,000,000원을 차입하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 3000000 }],
    credit: [{ account: "단기차입금", amount: 3000000 }],
    explanation: "보통예금(자산) 증가, 단기차입금(부채) 증가.",
    distractors: ["현금", "장기차입금", "미지급금"],
  },
  {
    id: "cjb09", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "임차료 300,000원을 현금으로 지급하였다.",
    debit: [{ account: "임차료", amount: 300000 }],
    credit: [{ account: "현금", amount: 300000 }],
    explanation: "임차료(비용) 발생, 현금(자산) 감소.",
    distractors: ["임대료수익", "선급비용", "미지급비용"],
  },
  {
    id: "cjb10", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "급여 2,500,000원을 보통예금에서 이체 지급하였다.",
    debit: [{ account: "급여", amount: 2500000 }],
    credit: [{ account: "보통예금", amount: 2500000 }],
    explanation: "급여(비용) 발생, 보통예금(자산) 감소.",
    distractors: ["현금", "미지급비용", "예수금"],
  },
  {
    id: "cjb11", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "비품 500,000원을 현금으로 구입하였다.",
    debit: [{ account: "비품", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    explanation: "비품(자산) 증가, 현금(자산) 감소.",
    distractors: ["소모품비", "미지급금", "선급금"],
  },
  {
    id: "cjb12", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "거래처에 현금 200,000원을 선급금으로 지급하였다.",
    debit: [{ account: "선급금", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    explanation: "선급금(자산) 증가, 현금(자산) 감소. 선급금은 미리 지급한 금액.",
    distractors: ["선급비용", "선수금", "미지급금"],
  },
  {
    id: "cjb13", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "고객으로부터 상품 대금 500,000원을 미리 받았다.",
    debit: [{ account: "현금", amount: 500000 }],
    credit: [{ account: "선수금", amount: 500000 }],
    explanation: "현금(자산) 증가, 선수금(부채) 증가. 상품 인도 전에 받은 금액은 부채.",
    distractors: ["매출", "선급금", "예수금"],
  },
  {
    id: "cjb14", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "보험료 120,000원을 현금으로 납부하였다.",
    debit: [{ account: "보험료", amount: 120000 }],
    credit: [{ account: "현금", amount: 120000 }],
    explanation: "보험료(비용) 발생, 현금(자산) 감소.",
    distractors: ["선급비용", "미지급비용", "세금과공과"],
  },
  {
    id: "cjb15", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "은행 보통예금에서 이자 50,000원이 입금되었다.",
    debit: [{ account: "보통예금", amount: 50000 }],
    credit: [{ account: "이자수익", amount: 50000 }],
    explanation: "보통예금(자산) 증가, 이자수익(수익) 발생.",
    distractors: ["현금", "미수수익", "이자비용"],
  },
  {
    id: "cjb16", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 매입 대금으로 약속어음 1,000,000원을 발행하였다.",
    debit: [{ account: "상품", amount: 1000000 }],
    credit: [{ account: "지급어음", amount: 1000000 }],
    explanation: "상품(자산) 증가, 지급어음(부채) 증가. 어음 발행은 외상매입금과 구분.",
    distractors: ["외상매입금", "미지급금", "받을어음"],
  },
  {
    id: "cjb17", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품을 판매하고 약속어음 1,200,000원을 받았다.",
    debit: [{ account: "받을어음", amount: 1200000 }],
    credit: [{ account: "매출", amount: 1200000 }],
    explanation: "받을어음(자산) 증가, 매출(수익) 발생. 외상매출금과 구분.",
    distractors: ["외상매출금", "미수금", "지급어음"],
  },
  {
    id: "cjb18", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "거래처에 현금 1,000,000원을 대여하였다.",
    debit: [{ account: "단기대여금", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    explanation: "단기대여금(자산) 증가, 현금(자산) 감소. 단기차입금과 혼동 주의.",
    distractors: ["단기차입금", "미수금", "선급금"],
  },
  {
    id: "cjb19", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "건물 임대료 400,000원을 현금으로 받았다.",
    debit: [{ account: "현금", amount: 400000 }],
    credit: [{ account: "임대료수익", amount: 400000 }],
    explanation: "현금(자산) 증가, 임대료수익(수익) 발생. 임차료(비용)와 구분.",
    distractors: ["임차료", "선수수익", "미수수익"],
  },
  {
    id: "cjb20", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "광고선전비 500,000원을 보통예금에서 이체하였다.",
    debit: [{ account: "광고선전비", amount: 500000 }],
    credit: [{ account: "보통예금", amount: 500000 }],
    explanation: "광고선전비(비용) 발생, 보통예금(자산) 감소.",
    distractors: ["접대비", "현금", "미지급비용"],
  },
  // ══════════════════════════════════════
  // common / journal-intermediate (10개)
  // ══════════════════════════════════════
  {
    id: "cji01", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "단기차입금 3,000,000원과 이자 60,000원을 보통예금에서 상환하였다.",
    debit: [
      { account: "단기차입금", amount: 3000000 },
      { account: "이자비용", amount: 60000 },
    ],
    credit: [{ account: "보통예금", amount: 3060000 }],
    explanation: "원금(부채 감소) + 이자(비용 발생). 차변 합계 3,060,000 = 대변 3,060,000.",
    distractors: ["장기차입금", "현금", "미지급비용"],
  },
  {
    id: "cji02", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "비품을 외상으로 800,000원에 구입하였다.",
    debit: [{ account: "비품", amount: 800000 }],
    credit: [{ account: "미지급금", amount: 800000 }],
    explanation: "상품 이외 자산의 외상 구입은 미지급금. 외상매입금은 상품 거래에만 사용.",
    distractors: ["외상매입금", "지급어음", "미지급비용"],
  },
  {
    id: "cji03", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "차량운반구를 1,000,000원에 외상으로 처분하였다 (장부가액 800,000원).",
    debit: [{ account: "미수금", amount: 1000000 }],
    credit: [
      { account: "차량운반구", amount: 800000 },
      { account: "유형자산처분이익", amount: 200000 },
    ],
    explanation: "처분가액 > 장부가액 → 처분이익 200,000. 상품 외 자산 처분은 미수금 사용.",
    distractors: ["외상매출금", "유형자산처분손실", "매출"],
  },
  {
    id: "cji04", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "상품 2,000,000원 매입. 1,000,000원은 약속어음, 나머지는 외상.",
    debit: [{ account: "상품", amount: 2000000 }],
    credit: [
      { account: "지급어음", amount: 1000000 },
      { account: "외상매입금", amount: 1000000 },
    ],
    explanation: "복합 결제: 어음분은 지급어음, 외상분은 외상매입금.",
    distractors: ["현금", "미지급금", "받을어음"],
  },
  {
    id: "cji05", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "급여 3,000,000원에서 소득세 예수금 200,000원을 공제, 나머지를 보통예금 이체.",
    debit: [{ account: "급여", amount: 3000000 }],
    credit: [
      { account: "예수금", amount: 200000 },
      { account: "보통예금", amount: 2800000 },
    ],
    explanation: "급여 총액(비용). 원천징수 → 예수금(부채), 실지급 → 보통예금 감소.",
    distractors: ["현금", "미지급비용", "세금과공과"],
  },
  {
    id: "cji06", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "비품(장부가액 500,000원)을 300,000원에 현금 처분하였다.",
    debit: [
      { account: "현금", amount: 300000 },
      { account: "유형자산처분손실", amount: 200000 },
    ],
    credit: [{ account: "비품", amount: 500000 }],
    explanation: "처분가액 < 장부가액 → 처분손실 200,000.",
    distractors: ["유형자산처분이익", "미수금", "감가상각비"],
  },
  {
    id: "cji07", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "선급한 보험료 중 당기 해당분 80,000원을 비용으로 대체하였다.",
    debit: [{ account: "보험료", amount: 80000 }],
    credit: [{ account: "선급비용", amount: 80000 }],
    explanation: "결산 수정분개. 선급비용(자산) 감소 → 보험료(비용) 인식.",
    distractors: ["선급금", "미지급비용", "현금"],
  },
  {
    id: "cji08", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "임대료 중 차기분 100,000원을 선수수익으로 수정하였다.",
    debit: [{ account: "임대료수익", amount: 100000 }],
    credit: [{ account: "선수수익", amount: 100000 }],
    explanation: "결산 수정분개. 차기 귀속 수익을 선수수익(부채)으로 이연.",
    distractors: ["선수금", "미수수익", "임차료"],
  },
  {
    id: "cji09", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "건물 감가상각비 600,000원을 계상하였다.",
    debit: [{ account: "감가상각비", amount: 600000 }],
    credit: [{ account: "건물", amount: 600000 }],
    explanation: "감가상각비(비용) 인식, 건물(자산) 장부가액 감소.",
    distractors: ["수선비", "임차료", "미지급비용"],
  },
  {
    id: "cji10", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "사무실 월세 1,100,000원(부가세 포함) 보통예금 이체. (공급가액 1,000,000, 부가세 100,000)",
    debit: [
      { account: "임차료", amount: 1000000 },
      { account: "부가세예수금", amount: 100000 },
    ],
    credit: [{ account: "보통예금", amount: 1100000 }],
    explanation: "공급가액 → 임차료(비용), 부가세 → 부가세예수금. 합계 일치 확인.",
    distractors: ["현금", "미지급비용", "선급비용", "세금과공과"],
  },
  // ══════════════════════════════════════
  // common / ox-basic (10개)
  // ══════════════════════════════════════
  {
    id: "cox01", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "자산이 증가하면 차변(왼쪽)에 기록한다.",
    answer: true,
    explanation: "자산의 증가는 차변, 감소는 대변에 기록합니다.",
  },
  {
    id: "cox02", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "부채가 증가하면 차변(왼쪽)에 기록한다.",
    answer: false,
    explanation: "부채의 증가는 대변(오른쪽)에 기록합니다. 부채 감소가 차변입니다.",
  },
  {
    id: "cox03", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "비용이 발생하면 대변(오른쪽)에 기록한다.",
    answer: false,
    explanation: "비용의 발생은 차변(왼쪽)에 기록합니다.",
  },
  {
    id: "cox04", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "수익이 발생하면 대변(오른쪽)에 기록한다.",
    answer: true,
    explanation: "수익의 발생은 대변에 기록합니다.",
  },
  {
    id: "cox05", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "외상매입금과 미지급금은 같은 계정과목이다.",
    answer: false,
    explanation: "외상매입금은 상품 매입 대금, 미지급금은 상품 외 거래 대금입니다.",
  },
  {
    id: "cox06", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "선급금은 부채 계정이다.",
    answer: false,
    explanation: "선급금은 미리 지급한 금액으로 자산 계정입니다. 선수금이 부채.",
  },
  {
    id: "cox07", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "분개에서 차변 합계와 대변 합계는 항상 일치해야 한다.",
    answer: true,
    explanation: "복식부기의 기본 원리. 대차평균의 원리.",
  },
  {
    id: "cox08", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "감가상각비는 자산 계정이다.",
    answer: false,
    explanation: "감가상각비는 비용 계정입니다. 자산의 가치 감소를 비용으로 인식.",
  },
  {
    id: "cox09", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "이자수익은 비용 계정이다.",
    answer: false,
    explanation: "이자수익은 수익 계정입니다. 이자비용이 비용.",
  },
  {
    id: "cox10", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "재무상태표는 일정 시점의 자산, 부채, 자본을 나타낸다.",
    answer: true,
    explanation: "재무상태표(대차대조표)는 특정 시점의 재무 상태를 보여줍니다. 손익계산서가 기간.",
  },
  // ══════════════════════════════════════
  // k-ifrs / kifrs-basic (10개)
  // ══════════════════════════════════════
  {
    id: "kb01", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "상품 1,000,000원을 외상으로 매입하였다. (K-IFRS: 매입채무 사용)",
    debit: [{ account: "재고자산", amount: 1000000 }],
    credit: [{ account: "매입채무", amount: 1000000 }],
    explanation: "K-IFRS에서는 상품 대신 재고자산, 외상매입금 대신 매입채무를 사용합니다.",
    distractors: ["상품", "외상매입금", "미지급금"],
  },
  {
    id: "kb02", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "상품 2,000,000원을 외상으로 판매하였다. (K-IFRS: 매출채권 사용)",
    debit: [{ account: "매출채권", amount: 2000000 }],
    credit: [{ account: "매출", amount: 2000000 }],
    explanation: "K-IFRS에서는 외상매출금 대신 매출채권을 사용합니다.",
    distractors: ["외상매출금", "미수금", "받을어음"],
  },
  {
    id: "kb03", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매출채권 500,000원에 대해 대손상각비를 인식하였다.",
    debit: [{ account: "대손상각비", amount: 500000 }],
    credit: [{ account: "매출채권", amount: 500000 }],
    explanation: "매출채권 회수 불가능 시 대손상각비(비용) 인식, 매출채권(자산) 감소.",
    distractors: ["유형자산처분손실", "충당부채", "이자비용"],
  },
  {
    id: "kb04", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "건물 감가상각비 1,200,000원을 인식하였다.",
    debit: [{ account: "감가상각비", amount: 1200000 }],
    credit: [{ account: "건물", amount: 1200000 }],
    explanation: "감가상각비(비용) 인식, 건물(자산) 장부가액 감소.",
    distractors: ["수선비", "임차료", "투자부동산"],
  },
  {
    id: "kb05", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "토지를 50,000,000원에 현금으로 취득하였다.",
    debit: [{ account: "토지", amount: 50000000 }],
    credit: [{ account: "현금", amount: 50000000 }],
    explanation: "토지(자산) 증가, 현금(자산) 감소. K-IFRS와 일반기업회계기준 동일.",
    distractors: ["건물", "투자부동산", "보통예금"],
  },
  {
    id: "kb06", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "재고자산 평가손실 300,000원을 인식하였다.",
    debit: [{ account: "재고자산평가손실", amount: 300000 }],
    credit: [{ account: "재고자산", amount: 300000 }],
    explanation: "재고자산의 순실현가능가치가 취득원가보다 낮을 때 평가손실 인식.",
    distractors: ["매출원가", "상품", "감가상각비"],
  },
  {
    id: "kb07", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "충당부채 2,000,000원을 설정하였다. (제품 보증 관련)",
    debit: [{ account: "제품보증비", amount: 2000000 }],
    credit: [{ account: "충당부채", amount: 2000000 }],
    explanation: "제품보증비(비용) 인식, 충당부채(부채) 설정. 미래 보증 지출이 예상될 때 인식.",
    hint: "충당부채는 금액이나 시기가 불확실한 부채입니다.",
    distractors: ["미지급비용", "선수금", "예수금"],
  },
  {
    id: "kb08", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매입채무 1,000,000원을 보통예금으로 결제하였다.",
    debit: [{ account: "매입채무", amount: 1000000 }],
    credit: [{ account: "보통예금", amount: 1000000 }],
    explanation: "매입채무(부채) 감소, 보통예금(자산) 감소.",
    distractors: ["외상매입금", "미지급금", "현금"],
  },
  {
    id: "kb09", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "기계장치 10,000,000원을 보통예금으로 구입하였다.",
    debit: [{ account: "기계장치", amount: 10000000 }],
    credit: [{ account: "보통예금", amount: 10000000 }],
    explanation: "기계장치(자산) 증가, 보통예금(자산) 감소.",
    distractors: ["비품", "현금", "미지급금"],
  },
  {
    id: "kb10", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "장기차입금 5,000,000원을 보통예금으로 상환하였다.",
    debit: [{ account: "장기차입금", amount: 5000000 }],
    credit: [{ account: "보통예금", amount: 5000000 }],
    explanation: "장기차입금(부채) 감소, 보통예금(자산) 감소.",
    distractors: ["단기차입금", "현금", "이자비용"],
  },
  // ══════════════════════════════════════
  // k-ifrs / kifrs-intermediate (5개)
  // ══════════════════════════════════════
  {
    id: "ki01", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "사용권자산 12,000,000원과 리스부채 12,000,000원을 인식하였다. (IFRS 16 리스)",
    debit: [{ account: "사용권자산", amount: 12000000 }],
    credit: [{ account: "리스부채", amount: 12000000 }],
    explanation: "IFRS 16: 리스이용자는 사용권자산(자산)과 리스부채(부채)를 인식합니다.",
    distractors: ["비품", "임차료", "장기차입금"],
  },
  {
    id: "ki02", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "리스부채 이자비용 200,000원을 인식하였다.",
    debit: [{ account: "이자비용", amount: 200000 }],
    credit: [{ account: "리스부채", amount: 200000 }],
    explanation: "리스부채에 대한 이자비용 인식. 리스부채 장부금액 증가(유효이자법).",
    distractors: ["임차료", "감가상각비", "미지급비용"],
  },
  {
    id: "ki03", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "사용권자산 감가상각비 2,400,000원을 인식하였다.",
    debit: [{ account: "감가상각비", amount: 2400000 }],
    credit: [{ account: "사용권자산", amount: 2400000 }],
    explanation: "사용권자산을 리스기간에 걸쳐 감가상각합니다.",
    distractors: ["임차료", "리스부채", "건물"],
  },
  {
    id: "ki04", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "투자부동산(건물)의 감가상각비 800,000원을 인식하였다. (원가모형)",
    debit: [{ account: "감가상각비", amount: 800000 }],
    credit: [{ account: "투자부동산", amount: 800000 }],
    explanation: "투자부동산 원가모형 적용 시 감가상각비를 인식합니다.",
    distractors: ["건물", "임대료수익", "수선비"],
  },
  {
    id: "ki05", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "매출채권 800,000원에 대해 대손충당금(충당부채)을 설정하였다.",
    debit: [{ account: "대손상각비", amount: 800000 }],
    credit: [{ account: "충당부채", amount: 800000 }],
    explanation: "예상 대손에 대해 대손상각비(비용)를 인식하고 충당부채를 설정합니다.",
    distractors: ["매출채권", "미지급비용", "유형자산처분손실"],
  },
  // ══════════════════════════════════════
  // k-ifrs / kifrs-ox (10개)
  // ══════════════════════════════════════
  {
    id: "kox01", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "K-IFRS에서 재고자산은 취득원가와 순실현가능가치 중 낮은 금액으로 평가한다.",
    answer: true,
    explanation: "저가법 적용. 순실현가능가치가 낮으면 평가손실 인식.",
  },
  {
    id: "kox02", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "K-IFRS에서 외상매출금은 매출채권으로 표시한다.",
    answer: true,
    explanation: "K-IFRS는 매출채권, 일반기업회계기준은 외상매출금 사용.",
  },
  {
    id: "kox03", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "IFRS 16에 따라 리스이용자는 모든 리스를 운용리스와 금융리스로 구분한다.",
    answer: false,
    explanation: "IFRS 16은 리스이용자의 운용/금융리스 구분을 폐지. 단일 모델로 사용권자산과 리스부채를 인식.",
  },
  {
    id: "kox04", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "사용권자산은 리스부채와 동일한 금액으로 최초 인식한다.",
    answer: false,
    explanation: "사용권자산 = 리스부채 + 선급리스료 + 초기직접원가 + 복구원가 등. 동일하지 않을 수 있음.",
  },
  {
    id: "kox05", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "K-IFRS에서 투자부동산은 원가모형 또는 공정가치모형을 선택 적용할 수 있다.",
    answer: true,
    explanation: "원가모형과 공정가치모형 중 선택. 공정가치모형은 감가상각 불필요.",
  },
  {
    id: "kox06", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "충당부채는 지출의 시기 또는 금액이 불확실한 부채이다.",
    answer: true,
    explanation: "현재 의무, 경제적 효익 유출 가능성, 신뢰성 있는 추정 세 가지 조건 충족 시 인식.",
  },
  {
    id: "kox07", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "K-IFRS에서 유형자산은 원가모형만 적용할 수 있다.",
    answer: false,
    explanation: "원가모형과 재평가모형 중 선택 가능. 재평가모형은 공정가치로 재평가.",
  },
  {
    id: "kox08", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "대손충당금은 매출채권에서 차감하는 형식으로 표시한다.",
    answer: true,
    explanation: "재무상태표에서 매출채권 차감 표시. 순액으로 보고.",
  },
  {
    id: "kox09", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "K-IFRS에서 연구비는 자산으로 인식할 수 있다.",
    answer: false,
    explanation: "연구단계 지출은 전액 비용. 개발단계 지출만 조건 충족 시 무형자산 인식 가능.",
  },
  {
    id: "kox10", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "기타포괄손익은 당기손익에 포함된다.",
    answer: false,
    explanation: "기타포괄손익은 당기손익과 구분. 포괄손익계산서에 별도 표시.",
  },
  // ══════════════════════════════════════
  // Batch 1 추가 (90개)
  // ══════════════════════════════════════
  {
    id: "cjb21", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "소모품 150,000원을 현금으로 구입하였다.",
    debit: [{ account: "소모품", amount: 150000 }],
    credit: [{ account: "현금", amount: 150000 }],
    distractors: ["소모품비", "미지급금", "선급금"],
    explanation: "소모품(자산) 증가, 현금(자산) 감소. 소모품은 자산, 소모품비는 비용으로 구분.",
    hint: "구입한 소모품은 아직 사용 전이므로 자산입니다.",
  },
  {
    id: "cjb22", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "소모품 150,000원 중 100,000원을 사용하였다.",
    debit: [{ account: "소모품비", amount: 100000 }],
    credit: [{ account: "소모품", amount: 100000 }],
    distractors: ["현금", "미지급비용"],
    explanation: "소모품 사용분은 소모품비(비용)로 대체. 소모품(자산) 감소.",
    hint: "사용한 소모품은 비용으로 전환됩니다.",
  },
  {
    id: "cjb23", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "단기차입금 2,000,000원을 현금으로 상환하였다.",
    debit: [{ account: "단기차입금", amount: 2000000 }],
    credit: [{ account: "현금", amount: 2000000 }],
    distractors: ["장기차입금", "보통예금"],
    explanation: "단기차입금(부채) 감소, 현금(자산) 감소.",
    hint: "빌린 돈을 갚으면 부채가 줄어듭니다.",
  },
  {
    id: "cjb24", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "건물 화재보험료 240,000원을 보통예금에서 이체하였다.",
    debit: [{ account: "보험료", amount: 240000 }],
    credit: [{ account: "보통예금", amount: 240000 }],
    distractors: ["선급비용", "현금"],
    explanation: "보험료(비용) 발생, 보통예금(자산) 감소.",
    hint: "당기에 해당하는 보험료는 비용으로 처리합니다.",
  },
  {
    id: "cjb25", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "수수료 수익 80,000원을 현금으로 받았다.",
    debit: [{ account: "현금", amount: 80000 }],
    credit: [{ account: "수수료수익", amount: 80000 }],
    distractors: ["미수수익", "수수료비용"],
    explanation: "현금(자산) 증가, 수수료수익(수익) 발생.",
    hint: "용역을 제공하고 받은 대가는 수익입니다.",
  },
  {
    id: "cjb26", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "직원 출장비 200,000원을 현금으로 지급하였다.",
    debit: [{ account: "여비교통비", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    distractors: ["복리후생비", "미지급비용"],
    explanation: "여비교통비(비용) 발생, 현금(자산) 감소.",
    hint: "출장 관련 비용은 여비교통비 계정을 사용합니다.",
  },
  {
    id: "cjb27", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "주주총회에서 현금 배당금 500,000원을 결의하였다.",
    debit: [{ account: "이익잉여금", amount: 500000 }],
    credit: [{ account: "미지급배당금", amount: 500000 }],
    distractors: ["자본금", "현금"],
    explanation: "배당 결의 시 이익잉여금(자본) 감소, 미지급배당금(부채) 증가. 실제 지급 시 현금 감소.",
    hint: "배당 결의는 지급 전이므로 미지급 부채로 처리합니다.",
  },
  {
    id: "cjb28", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "미지급배당금 500,000원을 현금으로 지급하였다.",
    debit: [{ account: "미지급배당금", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["이익잉여금", "보통예금"],
    explanation: "미지급배당금(부채) 감소, 현금(자산) 감소.",
    hint: "이미 결의된 배당금을 실제로 지급하는 분개입니다.",
  },
  {
    id: "cjb29", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "세금과공과 30,000원을 현금으로 납부하였다.",
    debit: [{ account: "세금과공과", amount: 30000 }],
    credit: [{ account: "현금", amount: 30000 }],
    distractors: ["법인세비용", "미지급세금"],
    explanation: "세금과공과(비용) 발생, 현금(자산) 감소.",
    hint: "재산세, 자동차세 등은 세금과공과 계정을 사용합니다.",
  },
  {
    id: "cjb30", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "전화요금 50,000원이 보통예금에서 자동이체 되었다.",
    debit: [{ account: "통신비", amount: 50000 }],
    credit: [{ account: "보통예금", amount: 50000 }],
    distractors: ["수도광열비", "현금"],
    explanation: "통신비(비용) 발생, 보통예금(자산) 감소.",
    hint: "전화요금, 인터넷비용 등은 통신비 계정을 사용합니다.",
  },
  {
    id: "cjb31", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "전기요금 120,000원을 현금으로 납부하였다.",
    debit: [{ account: "수도광열비", amount: 120000 }],
    credit: [{ account: "현금", amount: 120000 }],
    distractors: ["통신비", "미지급비용"],
    explanation: "수도광열비(비용) 발생, 현금(자산) 감소.",
    hint: "전기, 수도, 가스요금은 수도광열비 계정을 사용합니다.",
  },
  {
    id: "cjb32", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "받을어음 1,000,000원이 만기되어 보통예금에 입금되었다.",
    debit: [{ account: "보통예금", amount: 1000000 }],
    credit: [{ account: "받을어음", amount: 1000000 }],
    distractors: ["현금", "외상매출금"],
    explanation: "어음 만기 회수: 보통예금(자산) 증가, 받을어음(자산) 감소.",
    hint: "만기된 어음을 회수하면 받을어음이 줄어듭니다.",
  },
  {
    id: "cjb33", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "지급어음 800,000원이 만기되어 보통예금에서 결제되었다.",
    debit: [{ account: "지급어음", amount: 800000 }],
    credit: [{ account: "보통예금", amount: 800000 }],
    distractors: ["외상매입금", "현금"],
    explanation: "지급어음(부채) 감소, 보통예금(자산) 감소.",
    hint: "만기된 어음을 결제하면 지급어음 부채가 사라집니다.",
  },
  {
    id: "cjb34", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "건물 수선비 400,000원을 현금으로 지급하였다.",
    debit: [{ account: "수선비", amount: 400000 }],
    credit: [{ account: "현금", amount: 400000 }],
    distractors: ["건물", "미지급금"],
    explanation: "유지보수 목적의 수선은 수선비(비용)로 처리. 자산 가치 향상 목적이면 자본적 지출로 자산화.",
    hint: "단순 유지보수 목적의 수선은 비용으로 처리합니다.",
  },
  {
    id: "cjb35", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "현금 300,000원을 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 300000 }],
    credit: [{ account: "현금", amount: 300000 }],
    distractors: ["단기차입금"],
    explanation: "보통예금(자산) 증가, 현금(자산) 감소. 자산 내 대체 거래.",
    hint: "현금을 은행에 입금하면 자산의 종류가 바뀝니다.",
  },
  {
    id: "cjb36", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "거래처 접대비 150,000원을 현금으로 지출하였다.",
    debit: [{ account: "접대비", amount: 150000 }],
    credit: [{ account: "현금", amount: 150000 }],
    distractors: ["광고선전비", "미지급비용"],
    explanation: "접대비(비용) 발생, 현금(자산) 감소.",
    hint: "거래처 식사, 선물 등은 접대비 계정을 사용합니다.",
  },
  {
    id: "cjb37", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "단기대여금에 대한 이자 30,000원을 현금으로 수취하였다.",
    debit: [{ account: "현금", amount: 30000 }],
    credit: [{ account: "이자수익", amount: 30000 }],
    distractors: ["미수수익", "이자비용"],
    explanation: "현금(자산) 증가, 이자수익(수익) 발생.",
    hint: "돈을 빌려주고 받는 이자는 이자수익입니다.",
  },
  {
    id: "cjb38", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "복리후생비 200,000원을 현금으로 지급하였다. (직원 식대)",
    debit: [{ account: "복리후생비", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    distractors: ["급여", "미지급비용"],
    explanation: "복리후생비(비용) 발생, 현금(자산) 감소.",
    hint: "직원 식대, 경조사비 등은 복리후생비 계정을 사용합니다.",
  },
  {
    id: "cjb39", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "단기차입금에 대한 이자 60,000원이 미지급 상태이다. (결산 수정)",
    debit: [{ account: "이자비용", amount: 60000 }],
    credit: [{ account: "미지급비용", amount: 60000 }],
    distractors: ["이자수익", "미지급금"],
    explanation: "결산 수정: 이자비용(비용) 발생 인식, 미지급비용(부채) 계상.",
    hint: "아직 지급하지 않은 이자도 발생주의에 따라 비용으로 인식합니다.",
  },
  {
    id: "cjb40", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "미수수익 50,000원을 현금으로 수취하였다.",
    debit: [{ account: "현금", amount: 50000 }],
    credit: [{ account: "미수수익", amount: 50000 }],
    distractors: ["보통예금", "이자수익"],
    explanation: "현금(자산) 증가, 미수수익(자산) 감소. 이미 수익으로 인식한 금액을 실제 회수.",
    hint: "이미 수익으로 인식된 미수수익을 받으면 자산 간 대체입니다.",
  },
  {
    id: "cji11", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "법인세 중간예납액 500,000원을 보통예금에서 납부하였다.",
    debit: [{ account: "선급법인세", amount: 500000 }],
    credit: [{ account: "보통예금", amount: 500000 }],
    distractors: ["법인세비용", "현금", "미지급세금"],
    explanation: "중간예납은 선급법인세(자산)로 처리. 결산 시 법인세비용과 상계.",
    hint: "미리 납부한 세금은 자산(선급법인세)으로 처리합니다.",
  },
  {
    id: "cji12", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "결산 시 법인세비용 2,000,000원을 계상하였다. (선급법인세 500,000원 있음)",
    debit: [{ account: "법인세비용", amount: 2000000 }],
    credit: [{ account: "선급법인세", amount: 500000 }, { account: "미지급세금", amount: 1500000 }],
    distractors: ["보통예금"],
    explanation: "법인세비용(비용) 2,000,000 = 선급법인세(자산) 500,000 상계 + 미지급세금(부채) 1,500,000.",
    hint: "법인세비용에서 이미 낸 선급법인세를 차감한 나머지가 미지급세금입니다.",
  },
  {
    id: "cji13", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "외상매출금 300,000원이 대손 확정되어 제각하였다. (대손충당금 잔액 200,000원 있음)",
    debit: [{ account: "대손충당금", amount: 200000 }, { account: "대손상각비", amount: 100000 }],
    credit: [{ account: "외상매출금", amount: 300000 }],
    distractors: ["현금"],
    explanation: "대손충당금 200,000 먼저 상계. 부족분 100,000은 대손상각비(비용)로 추가 인식.",
    hint: "대손충당금이 있으면 먼저 상계하고, 부족하면 비용으로 처리합니다.",
  },
  {
    id: "cji14", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "전기에 대손 처리한 외상매출금 100,000원이 현금으로 회수되었다. (2단계 처리: ① 채권 복구 ② 현금 회수)",
    debit: [{ account: "외상매출금", amount: 100000 }, { account: "현금", amount: 100000 }],
    credit: [{ account: "대손충당금", amount: 100000 }, { account: "외상매출금", amount: 100000 }],
    distractors: ["대손상각비"],
    explanation: "① 채권 복구: (차) 외상매출금 / (대) 대손충당금. ② 현금 회수: (차) 현금 / (대) 외상매출금. 대손상각비 환입이 아닌 대손충당금 복구.",
    hint: "대손 회수는 채권을 먼저 복구한 뒤 현금으로 받는 2단계로 처리합니다.",
  },
  {
    id: "cji15", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "결산 시 임차료 선급분 60,000원을 차기로 이연하였다.",
    debit: [{ account: "선급비용", amount: 60000 }],
    credit: [{ account: "임차료", amount: 60000 }],
    distractors: ["선급금", "선수수익"],
    explanation: "차기 해당분 임차료를 선급비용(자산)으로 이연. 비용 감소.",
    hint: "차기에 해당하는 비용은 선급비용으로 이연합니다.",
  },
  {
    id: "cji16", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "결산 시 미수이자 40,000원을 계상하였다.",
    debit: [{ account: "미수수익", amount: 40000 }],
    credit: [{ account: "이자수익", amount: 40000 }],
    distractors: ["이자비용", "선급비용"],
    explanation: "발생주의: 아직 못 받은 이자도 이자수익(수익) 인식, 미수수익(자산) 계상.",
    hint: "받지 않았어도 기간이 경과한 이자는 수익으로 인식합니다.",
  },
  {
    id: "cji17", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "건물에 엘리베이터를 추가 설치하여 5,000,000원을 보통예금으로 지급하였다. (자본적 지출)",
    debit: [{ account: "건물", amount: 5000000 }],
    credit: [{ account: "보통예금", amount: 5000000 }],
    distractors: ["수선비", "미지급금"],
    explanation: "자산 가치 증가 지출(자본적 지출)은 자산으로 처리. 수선비(수익적 지출)와 구분.",
    hint: "자산의 가치나 내용연수를 늘리는 지출은 자산으로 처리합니다.",
  },
  {
    id: "cji18", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "유상증자로 보통주 1,000주를 주당 5,000원에 발행하고 보통예금에 입금하였다. (액면가 1,000원)",
    debit: [{ account: "보통예금", amount: 5000000 }],
    credit: [{ account: "자본금", amount: 1000000 }, { account: "주식발행초과금", amount: 4000000 }],
    distractors: ["이익잉여금", "현금"],
    explanation: "액면가 1,000 × 1,000주 = 자본금 1,000,000. 초과분 4,000,000 = 주식발행초과금(자본잉여금).",
    hint: "발행금액에서 액면가를 빼면 주식발행초과금입니다.",
  },
  {
    id: "cji19", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "토지(장부가액 10,000,000원)를 12,000,000원에 현금으로 처분하였다.",
    debit: [{ account: "현금", amount: 12000000 }],
    credit: [{ account: "토지", amount: 10000000 }, { account: "유형자산처분이익", amount: 2000000 }],
    distractors: ["유형자산처분손실"],
    explanation: "처분가 12,000,000 > 장부가 10,000,000 → 처분이익 2,000,000.",
    hint: "처분가액이 장부가액보다 크면 처분이익입니다.",
  },
  {
    id: "cji20", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "상품권 300,000원을 현금으로 발행하였다.",
    debit: [{ account: "현금", amount: 300000 }],
    credit: [{ account: "선수금", amount: 300000 }],
    distractors: ["매출", "선수수익"],
    explanation: "상품권 발행: 현금(자산) 증가, 선수금(부채) 증가. 상품권 사용 시 매출 인식.",
    hint: "상품권은 아직 상품을 제공하지 않았으므로 부채입니다.",
  },
  {
    id: "cox11", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "소모품을 구입하면 무조건 비용으로 처리한다.",
    answer: false,
    explanation: "소모품 구입 시 자산(소모품)으로 처리하고, 사용 시 비용(소모품비)으로 대체합니다.",
    hint: "구입과 사용은 다른 시점입니다.",
  },
  {
    id: "cox12", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "복식부기에서 모든 거래는 차변과 대변 양쪽에 동시에 기록된다.",
    answer: true,
    explanation: "복식부기의 핵심 원리. 하나의 거래가 차변과 대변에 동일 금액으로 기록됩니다.",
    hint: "복식부기에서 거래는 항상 두 계정에 영향을 줍니다.",
  },
  {
    id: "cox13", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "자본금은 자산 계정이다.",
    answer: false,
    explanation: "자본금은 자본 계정입니다. 자산 = 부채 + 자본 관계에서 자본에 해당합니다.",
    hint: "재무상태표 오른쪽에 있는 항목을 생각해보세요.",
  },
  {
    id: "cox14", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "손익계산서는 일정 기간의 수익과 비용을 나타낸다.",
    answer: true,
    explanation: "손익계산서는 기간 재무제표. 재무상태표는 시점 재무제표입니다.",
    hint: "손익계산서는 '기간' 동안의 경영 성과를 보여줍니다.",
  },
  {
    id: "cox15", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "미지급금과 미지급비용은 같은 계정이다.",
    answer: false,
    explanation: "미지급금은 상품 외 자산 구입 대금, 미지급비용은 발생했으나 지급하지 않은 비용입니다.",
    hint: "미지급금은 구입 거래, 미지급비용은 발생주의 관련 계정입니다.",
  },
  {
    id: "cox16", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "수익은 발생 시 대변에 기록한다.",
    answer: true,
    explanation: "수익 발생은 대변. 수익 취소는 차변에 기록합니다.",
    hint: "수익과 부채는 같은 쪽(대변)에서 증가합니다.",
  },
  {
    id: "cox17", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "선수금은 자산 계정이다.",
    answer: false,
    explanation: "선수금은 미래에 상품/서비스를 제공해야 하는 의무이므로 부채 계정입니다.",
    hint: "받은 돈에 대해 아직 의무가 남아있으면 부채입니다.",
  },
  {
    id: "cox18", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "발생주의 회계에서 현금 수령 시점에 수익을 인식한다.",
    answer: false,
    explanation: "발생주의는 현금 수수와 관계없이 수익/비용이 발생한 시점에 인식합니다. 현금주의와 반대.",
    hint: "발생주의는 현금 흐름이 아닌 경제적 사건 발생 시점 기준입니다.",
  },
  {
    id: "cox19", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "대손충당금은 매출채권(외상매출금)에서 차감하는 형식으로 표시한다.",
    answer: true,
    explanation: "대손충당금은 자산의 차감 계정. 재무상태표에서 외상매출금에서 차감하여 순액 표시.",
    hint: "대손충당금은 자산을 줄이는 역할을 합니다.",
  },
  {
    id: "cox20", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "자본적 지출은 당기 비용으로 처리한다.",
    answer: false,
    explanation: "자본적 지출은 자산으로 처리 후 감가상각합니다. 수익적 지출이 당기 비용입니다.",
    hint: "자산 가치를 높이는 지출은 자산으로, 단순 유지는 비용으로 처리합니다.",
  },
  {
    id: "cox21", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "이익잉여금은 수익 계정이다.",
    answer: false,
    explanation: "이익잉여금은 자본 계정입니다. 누적된 이익이 자본으로 쌓인 것입니다.",
    hint: "이익잉여금은 재무상태표의 자본 항목에 표시됩니다.",
  },
  {
    id: "cox22", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "미수수익은 부채 계정이다.",
    answer: false,
    explanation: "미수수익은 이미 발생했지만 아직 받지 못한 수익으로 자산 계정입니다.",
    hint: "받아야 할 것은 자산, 줘야 할 것은 부채입니다.",
  },
  {
    id: "cox23", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "유형자산 처분 시 처분가액이 장부가액보다 작으면 처분이익이 발생한다.",
    answer: false,
    explanation: "처분가액 < 장부가액 → 처분손실. 처분가액 > 장부가액 → 처분이익.",
    hint: "비싸게 팔면 이익, 싸게 팔면 손실입니다.",
  },
  {
    id: "cox24", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "주식발행초과금은 자본잉여금에 해당한다.",
    answer: true,
    explanation: "주식발행초과금은 액면가 초과 발행 금액으로 자본잉여금에 포함됩니다.",
    hint: "자본잉여금은 주주와의 거래에서 발생하는 자본입니다.",
  },
  {
    id: "cox25", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "받을어음과 지급어음은 모두 자산 계정이다.",
    answer: false,
    explanation: "받을어음은 자산(받아야 할 것), 지급어음은 부채(줘야 할 것)입니다.",
    hint: "어음의 방향을 생각해보세요. 받는 건 자산, 주는 건 부채.",
  },
  {
    id: "ccalc01", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "기초 자산 5,000,000원, 기초 부채 2,000,000원, 당기 순이익 1,000,000원, 배당금 지급 200,000원일 때 기말 자본은?",
    correctAnswer: 3800000,
    explanation: "기초 자본 = 5,000,000 - 2,000,000 = 3,000,000. 기말 자본 = 3,000,000 + 1,000,000 - 200,000 = 3,800,000.",
    hint: "자본 = 자산 - 부채. 당기 순이익은 자본을 늘리고, 배당금은 자본을 줄입니다.",
  },
  {
    id: "ccalc02", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "매출액 10,000,000원, 매출원가 6,000,000원, 판관비 2,000,000원일 때 영업이익은?",
    correctAnswer: 2000000,
    explanation: "매출총이익 = 10,000,000 - 6,000,000 = 4,000,000. 영업이익 = 4,000,000 - 2,000,000 = 2,000,000.",
    hint: "영업이익 = 매출액 - 매출원가 - 판매관리비",
  },
  {
    id: "ccalc03", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "취득원가 3,000,000원, 잔존가치 300,000원, 내용연수 5년인 유형자산의 정액법 감가상각비는?",
    correctAnswer: 540000,
    explanation: "정액법 = (3,000,000 - 300,000) / 5 = 540,000원/년.",
    hint: "정액법: (취득원가 - 잔존가치) ÷ 내용연수",
  },
  {
    id: "ccalc04", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "외상매출금 기초 잔액 500,000원, 당기 외상매출 2,000,000원, 당기 회수액 1,800,000원일 때 기말 외상매출금 잔액은?",
    correctAnswer: 700000,
    explanation: "기말 = 500,000 + 2,000,000 - 1,800,000 = 700,000원.",
    hint: "기말 잔액 = 기초 잔액 + 발생액 - 회수액",
  },
  {
    id: "ccalc05", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "기초 재고 200,000원, 당기 매입 800,000원, 기말 재고 150,000원일 때 매출원가는?",
    correctAnswer: 850000,
    explanation: "매출원가 = 200,000 + 800,000 - 150,000 = 850,000원.",
    hint: "매출원가 = 기초재고 + 당기매입 - 기말재고",
  },
  {
    id: "kb11", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매출채권 3,000,000원에 대해 대손충당금 150,000원을 설정하였다.",
    debit: [{ account: "대손상각비", amount: 150000 }],
    credit: [{ account: "대손충당금", amount: 150000 }],
    distractors: ["매출채권", "미지급비용"],
    explanation: "K-IFRS: 기대신용손실 모형에 따라 대손상각비(비용) 인식, 대손충당금(차감계정) 설정.",
    hint: "K-IFRS는 손실이 발생하기 전에 미리 기대신용손실을 인식합니다.",
  },
  {
    id: "kb12", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "당기손익-공정가치측정 금융자산(주식) 1,000,000원을 현금으로 취득하였다.",
    debit: [{ account: "당기손익-공정가치측정금융자산", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    distractors: ["매도가능금융자산", "보통예금"],
    explanation: "K-IFRS 9: 단기 매매 목적 금융자산은 당기손익-공정가치측정(FVTPL)으로 분류.",
    hint: "K-IFRS 9에서 금융자산 분류는 사업모형과 현금흐름 특성에 따릅니다.",
  },
  {
    id: "kb13", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "보유 중인 FVTPL 금융자산의 공정가치가 200,000원 상승하였다.",
    debit: [{ account: "당기손익-공정가치측정금융자산", amount: 200000 }],
    credit: [{ account: "금융자산평가이익", amount: 200000 }],
    distractors: ["기타포괄손익", "미실현이익"],
    explanation: "FVTPL 금융자산 평가이익은 당기손익(수익)으로 인식. 기타포괄손익 아님.",
    hint: "FVTPL은 평가손익이 당기손익에 반영됩니다.",
  },
  {
    id: "kb14", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "사채 10,000,000원을 액면발행하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 10000000 }],
    credit: [{ account: "사채", amount: 10000000 }],
    distractors: ["장기차입금", "현금"],
    explanation: "사채 액면발행: 발행금액 = 액면금액. 보통예금(자산) 증가, 사채(부채) 증가.",
    hint: "사채는 회사채로 장기 부채입니다.",
  },
  {
    id: "kb15", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "무형자산(특허권) 2,000,000원을 현금으로 취득하였다.",
    debit: [{ account: "특허권", amount: 2000000 }],
    credit: [{ account: "현금", amount: 2000000 }],
    distractors: ["연구비", "개발비"],
    explanation: "외부 구입한 특허권은 무형자산으로 인식. 취득원가로 측정.",
    hint: "외부에서 구입한 무형자산은 취득원가로 자산 인식합니다.",
  },
  {
    id: "kb16", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "개발단계 지출 500,000원을 현금으로 지급하였다. (자산인식 요건 충족)",
    debit: [{ account: "개발비", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["연구비", "무형자산"],
    explanation: "K-IFRS: 개발단계 지출은 요건 충족 시 무형자산(개발비)으로 인식. 연구단계는 전액 비용.",
    hint: "연구단계는 비용, 개발단계는 요건 충족 시 자산입니다.",
  },
  {
    id: "kb17", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "유형자산을 재평가모형으로 평가하여 공정가치가 장부가액보다 1,000,000원 증가하였다.",
    debit: [{ account: "유형자산", amount: 1000000 }],
    credit: [{ account: "재평가잉여금", amount: 1000000 }],
    distractors: ["유형자산평가이익", "기타포괄손익"],
    explanation: "재평가 증가분은 기타포괄손익(재평가잉여금, 자본)으로 인식. 당기손익 아님.",
    hint: "유형자산 재평가이익은 당기손익이 아닌 기타포괄손익으로 처리합니다.",
  },
  {
    id: "kb18", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "리스료 1,200,000원을 보통예금에서 지급하였다. (리스부채 원금 1,000,000원, 이자 200,000원)",
    debit: [{ account: "리스부채", amount: 1000000 }, { account: "이자비용", amount: 200000 }],
    credit: [{ account: "보통예금", amount: 1200000 }],
    distractors: ["임차료", "사용권자산"],
    explanation: "리스료 지급 = 원금 상환(리스부채 감소) + 이자비용 인식. IFRS 16 적용.",
    hint: "리스료는 원금과 이자로 나뉩니다.",
  },
  {
    id: "kb19", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "투자부동산(공정가치모형) 공정가치가 5,000,000원에서 5,500,000원으로 증가하였다.",
    debit: [{ account: "투자부동산", amount: 500000 }],
    credit: [{ account: "투자부동산평가이익", amount: 500000 }],
    distractors: ["재평가잉여금", "기타포괄손익"],
    explanation: "투자부동산 공정가치모형: 평가손익을 당기손익으로 인식. 재평가잉여금(기타포괄) 아님.",
    hint: "투자부동산 공정가치모형의 평가손익은 당기손익입니다.",
  },
  {
    id: "kb20", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "전환사채 5,000,000원이 주식으로 전환되었다. (자본금 3,000,000원, 주식발행초과금 2,000,000원)",
    debit: [{ account: "전환사채", amount: 5000000 }],
    credit: [{ account: "자본금", amount: 3000000 }, { account: "주식발행초과금", amount: 2000000 }],
    distractors: ["사채"],
    explanation: "전환사채(부채) 감소, 자본금 + 주식발행초과금(자본) 증가. 부채의 자본 전환.",
    hint: "전환사채가 주식으로 바뀌면 부채가 자본이 됩니다.",
  },
  {
    id: "kb21", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "종업원급여 중 확정급여채무 1,000,000원을 인식하였다.",
    debit: [{ account: "퇴직급여", amount: 1000000 }],
    credit: [{ account: "확정급여채무", amount: 1000000 }],
    distractors: ["퇴직급여충당부채", "예수금"],
    explanation: "K-IFRS 19: 확정급여제도에서 퇴직급여(비용) 인식, 확정급여채무(부채) 계상.",
    hint: "K-IFRS에서는 퇴직급여충당부채 대신 확정급여채무를 사용합니다.",
  },
  {
    id: "kb22", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "금융리스 이용자로서 리스개시일에 사용권자산과 리스부채를 10,000,000원으로 인식하였다.",
    debit: [{ account: "사용권자산", amount: 10000000 }],
    credit: [{ account: "리스부채", amount: 10000000 }],
    distractors: ["임차료", "장기차입금"],
    explanation: "IFRS 16: 리스개시일에 사용권자산(자산)과 리스부채(부채)를 동시에 인식.",
    hint: "IFRS 16에서 리스는 자산과 부채를 동시에 인식합니다.",
  },
  {
    id: "kb23", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "연구단계 지출 800,000원을 현금으로 지급하였다.",
    debit: [{ account: "연구비", amount: 800000 }],
    credit: [{ account: "현금", amount: 800000 }],
    distractors: ["개발비", "무형자산"],
    explanation: "K-IFRS: 연구단계 지출은 전액 당기비용. 개발단계와 달리 자산화 불가.",
    hint: "연구단계는 항상 비용입니다.",
  },
  {
    id: "kb24", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매출채권 2,000,000원을 팩토링(양도)하고 현금 1,900,000원을 수취하였다. (위험과 보상이 이전되어 제거 조건 충족)",
    debit: [{ account: "현금", amount: 1900000 }, { account: "매출채권처분손실", amount: 100000 }],
    credit: [{ account: "매출채권", amount: 2000000 }],
    distractors: ["단기차입금"],
    explanation: "매출채권 양도: 현금 수취 + 처분손실 인식. 차이 100,000원은 처분손실.",
    hint: "매출채권 양도 시 수취액과 장부가액의 차이는 손익입니다.",
  },
  {
    id: "kb25", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "자기주식 500,000원을 현금으로 취득하였다.",
    debit: [{ account: "자기주식", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["투자자산", "이익잉여금"],
    explanation: "자기주식은 자본의 차감 계정. 자산이 아닌 자본(마이너스)으로 처리.",
    hint: "자기주식은 자본을 줄이는 계정입니다.",
  },
  {
    id: "kb26", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "유형자산 손상차손 300,000원을 인식하였다.",
    debit: [{ account: "손상차손", amount: 300000 }],
    credit: [{ account: "유형자산", amount: 300000 }],
    distractors: ["감가상각비", "유형자산처분손실"],
    explanation: "K-IFRS 36: 자산 회수가능액이 장부가액 미만이면 손상차손(비용) 인식.",
    hint: "손상은 자산 가치가 기대보다 크게 하락할 때 인식합니다.",
  },
  {
    id: "kb27", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "외화매출채권 $10,000(환율: 1,200원)을 결제일에 회수하였다. (장부상 환율 1,100원)",
    debit: [{ account: "현금", amount: 12000000 }],
    credit: [{ account: "매출채권", amount: 11000000 }, { account: "외환차익", amount: 1000000 }],
    distractors: ["외환차손"],
    explanation: "결제일 환율(1,200) > 장부 환율(1,100) → 외환차익 1,000,000. $10,000 × (1,200-1,100) = 1,000,000.",
    hint: "결제 시점 환율이 장부 환율보다 높으면 외환차익입니다.",
  },
  {
    id: "kb28", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "정부보조금 2,000,000원을 수령하여 보통예금에 입금하였다. (자산 관련 보조금)",
    debit: [{ account: "보통예금", amount: 2000000 }],
    credit: [{ account: "이연정부보조금", amount: 2000000 }],
    distractors: ["정부보조금수익", "이익잉여금"],
    explanation: "자산 관련 정부보조금: 이연정부보조금(부채)으로 처리 후 자산 내용연수에 걸쳐 수익 인식.",
    hint: "자산 관련 정부보조금은 즉시 수익이 아니라 이연정부보조금(부채)으로 처리합니다.",
  },
  {
    id: "kb29", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "주식결제형 주식기준보상 100,000원을 인식하였다.",
    debit: [{ account: "주식보상비용", amount: 100000 }],
    credit: [{ account: "주식선택권", amount: 100000 }],
    distractors: ["미지급비용", "급여"],
    explanation: "K-IFRS 2: 주식결제형 주식기준보상은 주식보상비용(비용) + 주식선택권(자본).",
    hint: "주식으로 결제하는 보상은 자본을 증가시킵니다.",
  },
  {
    id: "kb30", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "리스부채 잔액 8,000,000원에 대한 이자비용(유효이자율 5%)을 인식하였다.",
    debit: [{ account: "이자비용", amount: 400000 }],
    credit: [{ account: "리스부채", amount: 400000 }],
    distractors: ["사용권자산", "임차료"],
    explanation: "유효이자법: 이자비용 = 8,000,000 × 5% = 400,000. 리스부채 장부가액 증가.",
    hint: "이자비용은 리스부채 잔액에 유효이자율을 곱해 계산합니다.",
  },
  {
    id: "kox11", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 연구단계 지출은 무형자산으로 인식할 수 없다.",
    answer: true,
    explanation: "연구단계 지출은 전액 비용 처리. 개발단계만 요건 충족 시 무형자산 인식 가능.",
    hint: "연구는 비용, 개발은 조건부 자산입니다.",
  },
  {
    id: "kox12", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "IFRS 16에서 리스이용자는 단기리스와 소액자산 리스에 대해 면제 규정을 적용할 수 있다.",
    answer: true,
    explanation: "단기리스(12개월 이하)와 소액자산 리스는 사용권자산/리스부채 인식 면제. 임차료로 처리 가능.",
    hint: "IFRS 16은 단기리스와 소액 리스에 대한 예외를 허용합니다.",
  },
  {
    id: "kox13", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 투자부동산에 공정가치모형을 적용하면 감가상각을 인식한다.",
    answer: false,
    explanation: "공정가치모형 적용 시 감가상각 불필요. 원가모형 적용 시에만 감가상각 인식.",
    hint: "공정가치로 측정하면 이미 가치 변동이 반영되므로 감가상각이 필요 없습니다.",
  },
  {
    id: "kox14", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "자기주식은 K-IFRS에서 자산으로 분류된다.",
    answer: false,
    explanation: "자기주식은 자본의 차감 항목으로 분류. 자산이 아닙니다.",
    hint: "회사가 자신의 주식을 사면 자본이 줄어듭니다.",
  },
  {
    id: "kox15", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 유형자산은 원가모형과 재평가모형 중 하나를 선택할 수 있다.",
    answer: true,
    explanation: "유형자산 측정 모형은 원가모형 또는 재평가모형 중 선택. 동일 분류 내 일관 적용.",
    hint: "K-IFRS는 유형자산에 대해 두 가지 측정 모형을 허용합니다.",
  },
  {
    id: "kox16", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 재평가잉여금은 당기손익으로 처리된다.",
    answer: false,
    explanation: "재평가잉여금은 기타포괄손익으로 처리. 당기손익에 포함되지 않습니다.",
    hint: "재평가이익은 포괄손익계산서에서 기타포괄손익 항목입니다.",
  },
  {
    id: "kox17", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS 9에서 FVTPL 금융자산의 평가손익은 당기손익으로 인식한다.",
    answer: true,
    explanation: "FVTPL(당기손익-공정가치측정) 금융자산은 평가손익 전액 당기손익 반영.",
    hint: "FVTPL은 공정가치 변동이 바로 손익에 반영됩니다.",
  },
  {
    id: "kox18", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 손상차손 환입은 항상 허용된다.",
    answer: false,
    explanation: "영업권의 손상차손은 환입 불가. 기타 자산은 환입 가능.",
    hint: "영업권 손상차손은 한번 인식하면 되돌릴 수 없습니다.",
  },
  {
    id: "kox19", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 외화환산손익은 기타포괄손익으로 처리한다.",
    answer: false,
    explanation: "화폐성 항목의 외화환산손익은 당기손익. 기타포괄손익이 아닙니다.",
    hint: "외화환산손익은 일반적으로 당기손익입니다.",
  },
  {
    id: "kox20", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 충당부채는 현재의무, 경제적 효익 유출 가능성, 신뢰성 있는 추정 세 가지 요건을 모두 충족해야 인식한다.",
    answer: true,
    explanation: "충당부채 인식 3요건: ① 현재의무 ② 경제적 효익 유출 가능 ③ 금액 신뢰성 추정 가능.",
    hint: "충당부채는 세 가지 조건을 모두 충족해야 합니다.",
  },
  {
    id: "kox21", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 리스이용자는 리스기간이 12개월을 초과하면 무조건 사용권자산을 인식해야 한다.",
    answer: false,
    explanation: "소액자산 리스는 리스기간과 무관하게 면제 가능. 12개월 기준은 단기리스에 해당.",
    hint: "소액자산 리스는 기간과 무관하게 면제됩니다.",
  },
  {
    id: "kox22", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 수익은 고객에게 통제가 이전될 때 인식한다.",
    answer: true,
    explanation: "K-IFRS 15: 수익인식 5단계 모형에서 핵심은 고객에게 통제가 이전되는 시점.",
    hint: "K-IFRS 15에서 수익 인식의 핵심은 '통제의 이전'입니다.",
  },
  {
    id: "kox23", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 전환사채의 전환권은 부채로 분류한다.",
    answer: false,
    explanation: "전환사채의 전환권(자본요소)은 자본으로 분류. 부채요소(사채)와 자본요소(전환권)로 분리.",
    hint: "전환사채는 부채요소와 자본요소로 분리합니다.",
  },
  {
    id: "kox24", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 기타포괄손익은 나중에 당기손익으로 재분류될 수 있는 항목과 그렇지 않은 항목으로 구분된다.",
    answer: true,
    explanation: "재분류 가능: 해외사업환산차이, FVOCI 채무상품 등. 재분류 불가: 재평가잉여금, FVOCI 지분상품 등.",
    hint: "기타포괄손익은 재분류 가능 여부에 따라 두 가지로 구분됩니다.",
  },
  {
    id: "kox25", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 영업권은 상각하지 않고 매년 손상검사를 실시한다.",
    answer: true,
    explanation: "K-IFRS: 영업권은 비상각 자산. 매년 또는 손상 징후 시 손상검사 실시.",
    hint: "영업권은 상각하지 않고 손상 여부만 검토합니다.",
  },
  {
    id: "kcalc01", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "리스부채 잔액 10,000,000원, 유효이자율 연 6%, 연간 리스료 3,000,000원일 때 1년 후 리스부채 잔액은?",
    correctAnswer: 7600000,
    explanation: "이자비용 = 10,000,000 × 6% = 600,000. 원금 상환 = 3,000,000 - 600,000 = 2,400,000. 기말 리스부채 = 10,000,000 - 2,400,000 = 7,600,000.",
    hint: "리스료 = 이자 + 원금상환. 원금상환액만큼 부채가 줄어듭니다.",
  },
  {
    id: "kcalc02", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "취득원가 5,000,000원, 잔존가치 500,000원, 내용연수 5년인 사용권자산의 정액법 1년 감가상각비는?",
    correctAnswer: 900000,
    explanation: "(5,000,000 - 500,000) ÷ 5 = 900,000원.",
    hint: "사용권자산도 일반 유형자산과 동일하게 감가상각합니다.",
  },
  {
    id: "kcalc03", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "FVTPL 금융자산 취득원가 2,000,000원, 기말 공정가치 2,300,000원일 때 평가이익은?",
    correctAnswer: 300000,
    explanation: "평가이익 = 2,300,000 - 2,000,000 = 300,000원. FVTPL은 당기손익 반영.",
    hint: "공정가치 - 장부가액 = 평가손익",
  },
  {
    id: "kcalc04", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "유형자산 취득원가 10,000,000원, 감가상각누계액 3,000,000원, 회수가능액 6,500,000원일 때 손상차손은?",
    correctAnswer: 500000,
    explanation: "장부가액 = 10,000,000 - 3,000,000 = 7,000,000. 손상차손 = 7,000,000 - 6,500,000 = 500,000.",
    hint: "손상차손 = 장부가액 - 회수가능액",
  },
  {
    id: "kcalc05", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "매출채권 잔액 5,000,000원에 대해 기대신용손실률 3%를 적용할 때 대손충당금 설정액은?",
    correctAnswer: 150000,
    explanation: "대손충당금 = 5,000,000 × 3% = 150,000원.",
    hint: "기대신용손실 = 매출채권 잔액 × 기대신용손실률",
  },
  // ══════════════════════════════════════
  // Batch 2 추가 (100개) - 일반기업/은행업/공공기관
  // ══════════════════════════════════════
  {
    id: "gjb01", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "상품 1,000,000원을 외상으로 매입하였다. (일반기업회계기준: 외상매입금 사용)",
    debit: [{ account: "상품", amount: 1000000 }],
    credit: [{ account: "외상매입금", amount: 1000000 }],
    distractors: ["재고자산", "매입채무"],
    explanation: "일반기업회계기준에서는 상품, 외상매입금 계정 사용. K-IFRS의 재고자산, 매입채무와 구분.",
    hint: "일반기업회계기준은 K-IFRS보다 전통적인 계정과목 명칭을 사용합니다.",
  },
  {
    id: "gjb02", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "상품 2,000,000원을 외상으로 판매하였다. (일반기업회계기준: 외상매출금 사용)",
    debit: [{ account: "외상매출금", amount: 2000000 }],
    credit: [{ account: "매출", amount: 2000000 }],
    distractors: ["매출채권", "매출액"],
    explanation: "일반기업회계기준: 외상매출금 사용. K-IFRS의 매출채권과 구분.",
    hint: "일반기업회계기준은 외상매출금, K-IFRS는 매출채권을 사용합니다.",
  },
  {
    id: "gjb03", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "건물에 대한 감가상각비 500,000원을 인식하였다. (간접법: 감가상각누계액 사용)",
    debit: [{ account: "감가상각비", amount: 500000 }],
    credit: [{ account: "감가상각누계액", amount: 500000 }],
    distractors: ["건물", "수선비"],
    explanation: "간접법: 자산에서 직접 차감하지 않고 감가상각누계액(차감계정) 사용. 직접법은 자산에서 직접 차감.",
    hint: "간접법은 감가상각누계액 계정을 사용하여 원가 정보를 유지합니다.",
  },
  {
    id: "gjb04", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "퇴직급여충당부채 1,000,000원을 설정하였다.",
    debit: [{ account: "퇴직급여", amount: 1000000 }],
    credit: [{ account: "퇴직급여충당부채", amount: 1000000 }],
    distractors: ["확정급여채무", "예수금"],
    explanation: "일반기업회계기준: 퇴직급여충당부채 사용. K-IFRS의 확정급여채무와 구분.",
    hint: "일반기업회계기준은 퇴직급여충당부채, K-IFRS는 확정급여채무를 사용합니다.",
  },
  {
    id: "gjb05", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "임직원이 퇴직하여 퇴직금 2,000,000원을 보통예금에서 지급하였다.",
    debit: [{ account: "퇴직급여충당부채", amount: 2000000 }],
    credit: [{ account: "보통예금", amount: 2000000 }],
    distractors: ["퇴직급여", "현금"],
    explanation: "퇴직금 지급: 퇴직급여충당부채(부채) 감소, 보통예금(자산) 감소.",
    hint: "미리 설정한 충당부채에서 실제 지급액을 차감합니다.",
  },
  {
    id: "gjb06", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "매도가능증권(주식) 1,000,000원을 현금으로 취득하였다.",
    debit: [{ account: "매도가능증권", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    distractors: ["단기매매증권", "투자자산"],
    explanation: "일반기업회계기준: 매도가능증권으로 분류. K-IFRS의 FVOCI 금융자산에 해당.",
    hint: "일반기업회계기준의 매도가능증권은 K-IFRS의 FVOCI에 대응됩니다.",
  },
  {
    id: "gjb07", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "단기매매증권 평가이익 100,000원을 인식하였다.",
    debit: [{ account: "단기매매증권", amount: 100000 }],
    credit: [{ account: "단기매매증권평가이익", amount: 100000 }],
    distractors: ["매도가능증권평가이익", "이익잉여금"],
    explanation: "단기매매증권 평가이익은 당기손익. 매도가능증권 평가이익은 기타포괄손익(자본)과 구분.",
    hint: "단기매매증권 평가손익은 손익계산서, 매도가능증권 평가손익은 자본에 반영됩니다.",
  },
  {
    id: "gjb08", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "매도가능증권 평가이익 200,000원을 인식하였다.",
    debit: [{ account: "매도가능증권", amount: 200000 }],
    credit: [{ account: "매도가능증권평가이익", amount: 200000 }],
    distractors: ["단기매매증권평가이익", "이익잉여금"],
    explanation: "매도가능증권 평가이익은 기타포괄손익누계액(자본)으로 처리. 당기손익 아님.",
    hint: "매도가능증권 평가이익은 자본에 쌓이고 처분 시 손익으로 전환됩니다.",
  },
  {
    id: "gjb09", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "외상매출금에 대한 대손충당금 100,000원을 설정하였다.",
    debit: [{ account: "대손상각비", amount: 100000 }],
    credit: [{ account: "대손충당금", amount: 100000 }],
    distractors: ["외상매출금", "잡손실"],
    explanation: "대손충당금 설정: 대손상각비(비용) 인식, 대손충당금(차감계정) 설정.",
    hint: "대손충당금은 외상매출금에서 차감하는 형식으로 표시합니다.",
  },
  {
    id: "gjb10", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "만기보유증권(사채) 5,000,000원을 액면가로 취득하고 현금 지급하였다.",
    debit: [{ account: "만기보유증권", amount: 5000000 }],
    credit: [{ account: "현금", amount: 5000000 }],
    distractors: ["매도가능증권", "단기매매증권"],
    explanation: "만기까지 보유 목적 채권은 만기보유증권으로 분류. 상각후원가로 측정.",
    hint: "만기보유증권은 상각후원가로 측정하며 평가손익을 인식하지 않습니다.",
  },
  {
    id: "gjb11", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "개발비 3,000,000원을 현금으로 지출하였다. (자산인식 요건 충족)",
    debit: [{ account: "개발비", amount: 3000000 }],
    credit: [{ account: "현금", amount: 3000000 }],
    distractors: ["경상개발비", "연구비"],
    explanation: "일반기업회계기준: 개발단계 지출 중 요건 충족분은 개발비(무형자산). 요건 미충족은 경상개발비(비용).",
    hint: "일반기업회계기준에서 요건 미충족 개발비는 경상개발비로 비용 처리합니다.",
  },
  {
    id: "gjb12", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "영업권 2,000,000원을 현금으로 취득하였다.",
    debit: [{ account: "영업권", amount: 2000000 }],
    credit: [{ account: "현금", amount: 2000000 }],
    distractors: ["무형자산", "개발비"],
    explanation: "영업권(무형자산) 취득. 일반기업회계기준에서는 영업권을 상각(최대 20년).",
    hint: "일반기업회계기준은 영업권을 상각하지만 K-IFRS는 상각하지 않습니다.",
  },
  {
    id: "gjb13", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "사채 할인발행차금 상각액 50,000원을 인식하였다.",
    debit: [{ account: "이자비용", amount: 50000 }],
    credit: [{ account: "사채할인발행차금", amount: 50000 }],
    distractors: ["사채", "현금"],
    explanation: "사채 할인발행 시 사채할인발행차금(차감계정)을 유효이자법으로 상각. 이자비용 인식.",
    hint: "사채할인발행차금 상각은 이자비용을 증가시킵니다.",
  },
  {
    id: "gjb14", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "임원 상여금 500,000원을 현금으로 지급하였다.",
    debit: [{ account: "급여", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["복리후생비", "미지급비용"],
    explanation: "임원 상여금은 급여(비용)로 처리. 현금(자산) 감소.",
    hint: "임원 상여금은 급여 계정에 포함됩니다.",
  },
  {
    id: "gjb15", type: "journal", standard: "general", category: "general-basic", difficulty: "basic",
    text: "건물(취득원가 10,000,000원, 감가상각누계액 3,000,000원)을 8,000,000원에 현금으로 처분하였다.",
    debit: [{ account: "현금", amount: 8000000 }, { account: "감가상각누계액", amount: 3000000 }],
    credit: [{ account: "건물", amount: 10000000 }, { account: "유형자산처분이익", amount: 1000000 }],
    distractors: ["유형자산처분손실"],
    explanation: "장부가액 = 10,000,000 - 3,000,000 = 7,000,000. 처분가 8,000,000 > 장부가 → 처분이익 1,000,000.",
    hint: "감가상각누계액은 처분 시 제거합니다.",
  },
  {
    id: "gji01", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "운용리스 월 임차료 500,000원을 보통예금에서 지급하였다. (일반기업회계기준)",
    debit: [{ account: "임차료", amount: 500000 }],
    credit: [{ account: "보통예금", amount: 500000 }],
    distractors: ["사용권자산", "리스부채"],
    explanation: "일반기업회계기준: 운용리스는 임차료(비용)로 처리. K-IFRS의 사용권자산/리스부채 인식 없음.",
    hint: "일반기업회계기준은 K-IFRS 16 이전 방식으로 운용리스를 임차료로 처리합니다.",
  },
  {
    id: "gji02", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "매도가능증권을 1,500,000원에 처분하였다. (취득원가 1,000,000원, 평가이익누계액 200,000원)",
    debit: [{ account: "현금", amount: 1500000 }, { account: "매도가능증권평가이익", amount: 200000 }],
    credit: [{ account: "매도가능증권", amount: 1200000 }, { account: "매도가능증권처분이익", amount: 500000 }],
    explanation: "처분 시 자본에 쌓인 평가이익 200,000 제거. 처분이익 = 처분가 1,500,000 - 장부가 1,200,000 = 300,000. (단, 재분류 포함 총 500,000 인식)",
    hint: "매도가능증권 처분 시 자본에 있던 평가손익을 당기손익으로 재분류합니다.",
  },
  {
    id: "gji03", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "영업권 상각비 200,000원을 인식하였다. (내용연수 10년, 취득원가 2,000,000원)",
    debit: [{ account: "무형자산상각비", amount: 200000 }],
    credit: [{ account: "영업권", amount: 200000 }],
    distractors: ["감가상각비", "손상차손"],
    explanation: "일반기업회계기준: 영업권 상각. 2,000,000 ÷ 10년 = 200,000/년. K-IFRS는 영업권 미상각.",
    hint: "일반기업회계기준에서 영업권은 최대 20년간 상각합니다.",
  },
  {
    id: "gji04", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "결산 시 재고자산(상품) 평가손실 300,000원을 인식하였다.",
    debit: [{ account: "재고자산평가손실", amount: 300000 }],
    credit: [{ account: "재고자산평가충당금", amount: 300000 }],
    distractors: ["상품", "매출원가"],
    explanation: "저가법 적용: 순실현가능가치 < 취득원가 시 평가손실 인식. 재고자산평가충당금(차감계정) 설정.",
    hint: "재고자산도 저가법에 따라 평가손실을 인식합니다.",
  },
  {
    id: "gji05", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "전기에 비용처리한 연구비 중 당기에 개발 성공이 확인되어 개발비 500,000원으로 자산화하였다.",
    debit: [{ account: "개발비", amount: 500000 }],
    credit: [{ account: "경상개발비", amount: 500000 }],
    distractors: ["연구비", "현금"],
    explanation: "개발 성공 확인 시 자산화 가능. 비용(경상개발비)에서 자산(개발비)으로 대체.",
    hint: "개발 성공이 확인되면 이전에 비용처리한 금액을 자산으로 전환할 수 있습니다.",
  },
  {
    id: "gji06", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "금융리스 이용자로서 리스자산 5,000,000원과 리스부채 5,000,000원을 인식하였다. (일반기업회계기준)",
    debit: [{ account: "리스자산", amount: 5000000 }],
    credit: [{ account: "리스부채", amount: 5000000 }],
    distractors: ["사용권자산", "임차료"],
    explanation: "일반기업회계기준 금융리스: 리스자산(자산)과 리스부채(부채) 인식. K-IFRS의 사용권자산과 유사하나 명칭 다름.",
    hint: "일반기업회계기준은 리스자산, K-IFRS는 사용권자산이라는 명칭을 사용합니다.",
  },
  {
    id: "gji07", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "주식발행비용 100,000원을 현금으로 지급하였다. (주식 할증 발행 관련)",
    debit: [{ account: "주식발행초과금", amount: 100000 }],
    credit: [{ account: "현금", amount: 100000 }],
    distractors: ["광고선전비", "이익잉여금"],
    explanation: "주식발행비용은 주식발행초과금에서 차감. 주식발행초과금이 없으면 이익잉여금 차감.",
    hint: "주식발행 직접 비용은 자본에서 차감합니다.",
  },
  {
    id: "gji08", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "기말 외화 외상매출금 $5,000(장부 환율 1,100원, 기말 환율 1,050원)을 환산하였다.",
    debit: [{ account: "외환차손", amount: 250000 }],
    credit: [{ account: "외상매출금", amount: 250000 }],
    distractors: ["외환차익", "현금"],
    explanation: "기말 환율(1,050) < 장부 환율(1,100) → 외환차손. $5,000 × (1,100-1,050) = 250,000.",
    hint: "기말 환율이 낮아지면 외화자산 가치가 줄어 외환차손이 발생합니다.",
  },
  {
    id: "gji09", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "전기에 계상한 대손충당금 300,000원 중 실제 대손이 200,000원으로 확정되어 잉여분을 환입하였다.",
    debit: [{ account: "대손충당금", amount: 100000 }],
    credit: [{ account: "대손충당금환입", amount: 100000 }],
    distractors: ["대손상각비", "외상매출금"],
    explanation: "대손충당금 잉여분 환입: 대손충당금 감소, 대손충당금환입(수익) 인식. 300,000 - 200,000 = 100,000 환입.",
    hint: "실제 대손이 충당금보다 적으면 잉여분을 수익으로 환입합니다.",
  },
  {
    id: "gji10", type: "journal", standard: "general", category: "general-intermediate", difficulty: "intermediate",
    text: "사채 500,000원을 할인발행하였다. (액면 5,000,000원, 발행가 4,500,000원, 현금 수취)",
    debit: [{ account: "현금", amount: 4500000 }, { account: "사채할인발행차금", amount: 500000 }],
    credit: [{ account: "사채", amount: 5000000 }],
    distractors: ["사채발행비"],
    explanation: "할인발행: 현금 4,500,000 + 사채할인발행차금(차감계정) 500,000 = 사채 액면 5,000,000.",
    hint: "사채할인발행차금은 사채의 차감 계정입니다.",
  },
  {
    id: "gox01", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 영업권은 상각하지 않는다.",
    answer: false,
    explanation: "일반기업회계기준은 영업권을 상각(최대 20년). K-IFRS만 영업권 비상각.",
    hint: "K-IFRS와 일반기업회계기준은 영업권 처리가 다릅니다.",
  },
  {
    id: "gox02", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 운용리스는 임차료로 비용 처리한다.",
    answer: true,
    explanation: "일반기업회계기준: 운용리스 = 임차료 비용처리. K-IFRS 16처럼 사용권자산을 인식하지 않음.",
    hint: "일반기업회계기준은 K-IFRS 이전의 리스 회계를 적용합니다.",
  },
  {
    id: "gox03", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 단기매매증권 평가이익은 당기손익으로 처리한다.",
    answer: true,
    explanation: "단기매매증권 평가손익은 당기손익. 매도가능증권 평가손익은 기타포괄손익(자본)으로 처리.",
    hint: "단기매매증권과 매도가능증권의 평가손익 처리가 다릅니다.",
  },
  {
    id: "gox04", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 매도가능증권 평가이익은 당기손익으로 처리한다.",
    answer: false,
    explanation: "매도가능증권 평가손익은 기타포괄손익누계액(자본). 처분 시 당기손익으로 재분류.",
    hint: "매도가능증권은 팔기 전까지 평가손익이 자본에 남아있습니다.",
  },
  {
    id: "gox05", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 외상매출금과 매출채권은 같은 계정이다.",
    answer: false,
    explanation: "외상매출금은 일반기업회계기준 용어, 매출채권은 K-IFRS 용어. 개념은 같으나 명칭이 다름.",
    hint: "두 기준은 같은 내용을 다른 계정과목 명칭으로 표현합니다.",
  },
  {
    id: "gox06", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 퇴직급여충당부채와 K-IFRS의 확정급여채무는 개념이 유사하다.",
    answer: true,
    explanation: "두 계정 모두 종업원의 미래 퇴직급여 지급 의무를 나타냄. 명칭과 측정 방법에 차이 있음.",
    hint: "내용은 유사하지만 측정 방법(현재가치 할인 여부 등)에서 차이가 납니다.",
  },
  {
    id: "gox07", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 개발비는 무조건 비용으로 처리한다.",
    answer: false,
    explanation: "요건 충족 시 무형자산(개발비)으로 자산화 가능. 미충족 시 경상개발비(비용).",
    hint: "개발 성공 가능성 등 요건 충족 여부에 따라 자산화 또는 비용화합니다.",
  },
  {
    id: "gox08", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준의 재무제표에는 포괄손익계산서가 포함된다.",
    answer: false,
    explanation: "일반기업회계기준: 손익계산서. K-IFRS: 포괄손익계산서. 명칭과 표시 방법이 다름.",
    hint: "K-IFRS는 포괄손익계산서, 일반기업회계기준은 손익계산서를 작성합니다.",
  },
  {
    id: "gox09", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "사채할인발행차금은 부채에서 차감하는 형식으로 표시한다.",
    answer: true,
    explanation: "사채할인발행차금은 사채(부채)의 차감 계정. 재무상태표에서 사채 액면에서 차감하여 장부가액 표시.",
    hint: "사채할인발행차금은 사채를 줄이는 역할을 합니다.",
  },
  {
    id: "gox10", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준은 주로 상장사와 대기업에 적용된다.",
    answer: false,
    explanation: "일반기업회계기준은 중소기업(비상장·비공개법인)에 적용. 상장사는 K-IFRS 의무 적용.",
    hint: "K-IFRS는 상장사, 일반기업회계기준은 비상장 중소기업에 적용됩니다.",
  },
  {
    id: "gox11", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "만기보유증권은 공정가치로 평가한다.",
    answer: false,
    explanation: "만기보유증권은 상각후원가로 측정. 공정가치 평가하지 않으므로 평가손익 없음.",
    hint: "만기보유증권은 만기까지 보유 목적이므로 공정가치 변동을 반영하지 않습니다.",
  },
  {
    id: "gox12", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 재고자산은 저가법으로 평가할 수 있다.",
    answer: true,
    explanation: "저가법: 취득원가와 순실현가능가치 중 낮은 금액으로 평가. 평가손실 인식.",
    hint: "재고자산은 두 기준 모두 저가법을 적용합니다.",
  },
  {
    id: "gox13", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "감가상각누계액은 유형자산에서 차감하는 형식으로 표시한다.",
    answer: true,
    explanation: "간접법: 감가상각누계액을 유형자산에서 차감하여 장부가액 표시. 취득원가 정보 유지.",
    hint: "감가상각누계액은 자산을 줄이는 차감 계정입니다.",
  },
  {
    id: "gox14", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 기타포괄손익누계액은 자본 항목이다.",
    answer: true,
    explanation: "기타포괄손익누계액(매도가능증권평가손익 등)은 자본 항목. 손익계산서 통과 전 자본에 직접 반영.",
    hint: "기타포괄손익누계액은 재무상태표 자본 섹션에 표시됩니다.",
  },
  {
    id: "gox15", type: "ox", standard: "general", category: "general-ox", difficulty: "basic",
    text: "일반기업회계기준에서 대손충당금환입은 수익으로 처리한다.",
    answer: true,
    explanation: "대손충당금 잉여분 환입 시 대손충당금환입(수익) 인식. 판매비와관리비의 마이너스 또는 영업외수익.",
    hint: "불필요해진 충당금을 줄이면 수익이 발생합니다.",
  },
  {
    id: "gcalc01", type: "calculation", standard: "general", category: "general-calc", difficulty: "basic",
    text: "취득원가 6,000,000원, 감가상각누계액 2,000,000원인 건물을 5,000,000원에 처분하였다. 처분손익은?",
    correctAnswer: 1000000,
    explanation: "장부가액 = 6,000,000 - 2,000,000 = 4,000,000. 처분이익 = 5,000,000 - 4,000,000 = 1,000,000.",
    hint: "처분손익 = 처분가액 - 장부가액(취득원가 - 감가상각누계액)",
  },
  {
    id: "gcalc02", type: "calculation", standard: "general", category: "general-calc", difficulty: "basic",
    text: "외상매출금 잔액 3,000,000원에 대해 1% 대손충당금을 설정할 때, 기존 대손충당금 잔액이 10,000원이면 추가 설정액은?",
    correctAnswer: 20000,
    explanation: "필요 충당금 = 3,000,000 × 1% = 30,000. 추가 설정 = 30,000 - 10,000 = 20,000.",
    hint: "추가 설정액 = 필요 충당금 - 기존 충당금 잔액",
  },
  {
    id: "gcalc03", type: "calculation", standard: "general", category: "general-calc", difficulty: "basic",
    text: "취득원가 4,000,000원, 내용연수 4년, 잔존가치 400,000원인 자산의 정률법 2년차 감가상각비는? (상각률 45%)",
    correctAnswer: 990000,
    explanation: "1년차 장부가 = 4,000,000 - (4,000,000 × 45%) = 2,200,000. 2년차 상각 = 2,200,000 × 45% = 990,000.",
    hint: "정률법은 매년 장부가액에 상각률을 곱합니다.",
  },
  {
    id: "gcalc04", type: "calculation", standard: "general", category: "general-calc", difficulty: "basic",
    text: "영업권 취득원가 2,000,000원, 내용연수 10년일 때 3년 후 영업권 장부가액은? (일반기업회계기준, 정액법)",
    correctAnswer: 1400000,
    explanation: "연간 상각 = 2,000,000 ÷ 10 = 200,000. 3년 상각 = 600,000. 장부가 = 2,000,000 - 600,000 = 1,400,000.",
    hint: "일반기업회계기준에서 영업권은 정액법으로 상각합니다.",
  },
  {
    id: "gcalc05", type: "calculation", standard: "general", category: "general-calc", difficulty: "basic",
    text: "매도가능증권 취득원가 1,000,000원, 전기말 공정가치 1,200,000원, 당기말 공정가치 900,000원일 때 당기 평가손실은?",
    correctAnswer: 300000,
    explanation: "전기말 장부가 1,200,000 → 당기말 공정가치 900,000. 당기 평가손실 = 1,200,000 - 900,000 = 300,000.",
    hint: "전기말 공정가치에서 당기말 공정가치를 빼면 당기 평가손익입니다.",
  },
  {
    id: "bjb01", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "고객으로부터 요구불예금 1,000,000원을 수입하였다.",
    debit: [{ account: "현금", amount: 1000000 }],
    credit: [{ account: "요구불예금", amount: 1000000 }],
    distractors: ["저축성예금", "보통예금"],
    explanation: "은행 입장: 현금(자산) 증가, 요구불예금(부채) 증가. 고객의 예금은 은행에게 부채.",
    hint: "은행이 고객으로부터 예금을 받으면 갚아야 할 부채가 생깁니다.",
  },
  {
    id: "bjb02", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "고객에게 일반대출금 5,000,000원을 실행하고 현금을 지급하였다.",
    debit: [{ account: "대출금", amount: 5000000 }],
    credit: [{ account: "현금", amount: 5000000 }],
    distractors: ["단기대여금", "예수금"],
    explanation: "은행 대출 실행: 대출금(자산) 증가, 현금(자산) 감소. 대출금은 은행의 자산.",
    hint: "은행이 빌려준 돈은 받을 권리이므로 자산입니다.",
  },
  {
    id: "bjb03", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "대출금에 대한 이자수익 200,000원을 현금으로 수령하였다.",
    debit: [{ account: "현금", amount: 200000 }],
    credit: [{ account: "이자수익", amount: 200000 }],
    distractors: ["이자비용", "미수이자"],
    explanation: "대출이자 수령: 현금(자산) 증가, 이자수익(수익) 발생. 은행의 핵심 수익원.",
    hint: "대출금에서 받는 이자는 은행의 주요 수익입니다.",
  },
  {
    id: "bjb04", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "고객 예금에 대한 이자비용 50,000원을 현금으로 지급하였다.",
    debit: [{ account: "이자비용", amount: 50000 }],
    credit: [{ account: "현금", amount: 50000 }],
    distractors: ["이자수익", "요구불예금"],
    explanation: "예금이자 지급: 이자비용(비용) 발생, 현금(자산) 감소.",
    hint: "고객 예금에 지급하는 이자는 은행의 비용입니다.",
  },
  {
    id: "bjb05", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "대출금에 대한 대손충당금 300,000원을 설정하였다.",
    debit: [{ account: "대손상각비", amount: 300000 }],
    credit: [{ account: "대손충당금", amount: 300000 }],
    distractors: ["대출금", "신용손실충당금"],
    explanation: "은행도 대출금에 대한 대손충당금 설정. 대손상각비(비용) 인식.",
    hint: "은행의 대출금도 회수 불능 가능성에 대해 충당금을 설정합니다.",
  },
  {
    id: "bjb06", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "한국은행에 지급준비금 500,000원을 예치하였다.",
    debit: [{ account: "지급준비금", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["예치금", "보통예금"],
    explanation: "지급준비금: 한국은행에 의무 예치금. 지급준비금(자산) 증가, 현금(자산) 감소.",
    hint: "지급준비금은 한국은행에 맡기는 법정 의무 예치금입니다.",
  },
  {
    id: "bjb07", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "국채 10,000,000원을 현금으로 매입하였다.",
    debit: [{ account: "유가증권", amount: 10000000 }],
    credit: [{ account: "현금", amount: 10000000 }],
    distractors: ["단기매매증권", "투자자산"],
    explanation: "국채 매입: 유가증권(자산) 증가, 현금(자산) 감소. 은행 운용자산.",
    hint: "은행이 보유하는 국채는 유가증권 계정으로 처리합니다.",
  },
  {
    id: "bjb08", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "타행에서 송금된 500,000원을 고객 계좌에 입금 처리하였다.",
    debit: [{ account: "타행환", amount: 500000 }],
    credit: [{ account: "요구불예금", amount: 500000 }],
    distractors: ["현금", "보통예금"],
    explanation: "타행에서 받은 송금: 타행환(자산) 증가, 요구불예금(부채) 증가.",
    hint: "타행에서 받은 자금은 타행환(당좌예금 등) 계정으로 처리합니다.",
  },
  {
    id: "bjb09", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "정기예금 2,000,000원이 만기 도래하여 이자 50,000원과 함께 현금으로 지급하였다.",
    debit: [{ account: "저축성예금", amount: 2000000 }, { account: "이자비용", amount: 50000 }],
    credit: [{ account: "현금", amount: 2050000 }],
    distractors: ["요구불예금"],
    explanation: "만기 지급: 저축성예금(부채) 감소 + 이자비용(비용) 인식, 현금(자산) 감소.",
    hint: "원금과 이자를 동시에 지급하므로 두 가지를 함께 분개합니다.",
  },
  {
    id: "bjb10", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "외환 매입: USD 10,000을 환율 1,300원으로 매입하고 원화 현금을 지급하였다.",
    debit: [{ account: "외화자산", amount: 13000000 }],
    credit: [{ account: "현금", amount: 13000000 }],
    distractors: ["외환차익", "유가증권"],
    explanation: "외화 매입: 외화자산(자산) 증가, 원화현금(자산) 감소. $10,000 × 1,300 = 13,000,000.",
    hint: "외화를 사면 외화자산이 늘고 원화가 줄어듭니다.",
  },
  {
    id: "bjb11", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "대출금 연체이자 100,000원을 미수이자로 계상하였다.",
    debit: [{ account: "미수이자", amount: 100000 }],
    credit: [{ account: "이자수익", amount: 100000 }],
    distractors: ["이자비용", "대출금"],
    explanation: "발생주의: 받지 못한 이자도 미수이자(자산) 계상, 이자수익(수익) 인식.",
    hint: "발생한 이자는 받지 못해도 수익으로 인식합니다.",
  },
  {
    id: "bjb12", type: "journal", standard: "bank", category: "bank-basic", difficulty: "basic",
    text: "당행 발행 CD(양도성예금증서) 1,000,000원이 만기 도래하여 현금으로 상환하였다.",
    debit: [{ account: "양도성예금증서", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    distractors: ["저축성예금", "사채"],
    explanation: "CD 상환: 양도성예금증서(부채) 감소, 현금(자산) 감소.",
    hint: "CD는 은행이 발행한 채무증서로 부채입니다.",
  },
  {
    id: "bji01", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "부실대출금 2,000,000원을 대손충당금과 상계하여 제각하였다. (대손충당금 잔액 1,500,000원)",
    debit: [{ account: "대손충당금", amount: 1500000 }, { account: "대손상각비", amount: 500000 }],
    credit: [{ account: "대출금", amount: 2000000 }],
    distractors: ["현금"],
    explanation: "대손충당금 1,500,000 먼저 상계. 부족분 500,000은 대손상각비(비용) 추가 인식.",
    hint: "충당금이 부족하면 그 차액을 비용으로 추가 인식합니다.",
  },
  {
    id: "bji02", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "이자율스왑 계약의 공정가치가 300,000원 증가하였다. (헤징 목적 아님)",
    debit: [{ account: "파생금융자산", amount: 300000 }],
    credit: [{ account: "파생상품평가이익", amount: 300000 }],
    distractors: ["기타포괄손익", "유가증권"],
    explanation: "매매 목적 파생상품 평가이익은 당기손익. 헤징 목적이면 기타포괄손익 처리 가능.",
    hint: "매매 목적 파생상품의 평가손익은 당기손익입니다.",
  },
  {
    id: "bji03", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "신디케이트 대출 참여분 5,000,000원을 실행하였다. (주간사 은행 제외 참여 은행)",
    debit: [{ account: "대출금", amount: 5000000 }],
    credit: [{ account: "현금", amount: 5000000 }],
    distractors: ["투자자산", "유가증권"],
    explanation: "신디케이트 대출 참여: 참여 은행도 동일하게 대출금(자산) 처리.",
    hint: "신디케이트 대출 참여 은행도 자신의 지분만큼 대출금으로 처리합니다.",
  },
  {
    id: "bji04", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "환매조건부채권(RP) 매도 10,000,000원 (7일물)을 실행하고 현금을 수취하였다.",
    debit: [{ account: "현금", amount: 10000000 }],
    credit: [{ account: "환매조건부채권매도", amount: 10000000 }],
    distractors: ["유가증권", "단기차입금"],
    explanation: "RP 매도: 현금(자산) 증가, 환매조건부채권매도(부채) 증가. 실질은 단기 자금 차입.",
    hint: "RP 매도는 증권을 담보로 자금을 빌리는 것과 유사합니다.",
  },
  {
    id: "bji05", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "기말 대출금 잔액에 대해 기대신용손실(ECL) 방식으로 대손충당금 500,000원을 추가 설정하였다.",
    debit: [{ account: "대손상각비", amount: 500000 }],
    credit: [{ account: "대손충당금", amount: 500000 }],
    distractors: ["대출금", "충당부채"],
    explanation: "K-IFRS 9 도입 후 은행도 기대신용손실(ECL) 모형 적용. 손실 발생 전 미리 충당금 설정.",
    hint: "ECL 모형은 손실이 발생하기 전에 예상 손실을 미리 인식합니다.",
  },
  {
    id: "bji06", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "후순위채권 5,000,000원을 액면발행하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 5000000 }],
    credit: [{ account: "후순위채권", amount: 5000000 }],
    distractors: ["사채", "자본금"],
    explanation: "후순위채권: 일반 채권보다 변제 순위가 낮은 부채. 은행 BIS 자기자본비율 산정 시 자본으로 인정.",
    hint: "후순위채권은 부채이지만 은행 자본건전성 지표에서 일부 자본으로 인정됩니다.",
  },
  {
    id: "bji07", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "대출금 원금 1,000,000원이 연체되어 고정이하여신으로 분류하였다. (분류만, 별도 분개 없으나 대손충당금 추가 설정 300,000원)",
    debit: [{ account: "대손상각비", amount: 300000 }],
    credit: [{ account: "대손충당금", amount: 300000 }],
    distractors: ["대출금", "부실채권"],
    explanation: "고정이하여신 분류 시 추가 충당금 설정. 여신 분류(정상/요주의/고정/회수의문/추정손실)에 따라 충당금 비율 차등.",
    hint: "은행 여신은 건전성 분류에 따라 충당금 적립 비율이 다릅니다.",
  },
  {
    id: "bji08", type: "journal", standard: "bank", category: "bank-intermediate", difficulty: "intermediate",
    text: "콜론(Call Loan) 2,000,000원을 실행하고 현금을 지급하였다.",
    debit: [{ account: "콜론", amount: 2000000 }],
    credit: [{ account: "현금", amount: 2000000 }],
    distractors: ["단기대여금", "콜머니"],
    explanation: "콜론: 은행 간 초단기 대출(자산). 콜머니: 은행 간 초단기 차입(부채).",
    hint: "콜론은 빌려준 것(자산), 콜머니는 빌린 것(부채)입니다.",
  },
  {
    id: "box01", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "은행이 고객으로부터 예금을 수취하면 부채가 발생한다.",
    answer: true,
    explanation: "예금은 고객에게 돌려줘야 할 의무이므로 은행의 부채.",
    hint: "은행의 예금 수취는 갚아야 할 의무가 생기는 것입니다.",
  },
  {
    id: "box02", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "은행의 대출금은 자산 계정이다.",
    answer: true,
    explanation: "대출금은 고객에게 받아야 할 권리이므로 은행의 자산.",
    hint: "빌려준 돈은 받아야 할 권리, 즉 자산입니다.",
  },
  {
    id: "box03", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "지급준비금은 한국은행에 의무적으로 예치해야 한다.",
    answer: true,
    explanation: "한국은행법에 따라 은행은 예금 잔액의 일정 비율을 지급준비금으로 한국은행에 예치 의무.",
    hint: "지급준비금은 뱅크런 등 긴급 상황을 대비한 법정 예치금입니다.",
  },
  {
    id: "box04", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "콜론은 은행 간 초단기 차입금이다.",
    answer: false,
    explanation: "콜론은 초단기 대출(자산). 콜머니가 초단기 차입금(부채).",
    hint: "론(Loan)은 빌려준 것, 머니(Money)는 빌린 것입니다.",
  },
  {
    id: "box05", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "은행의 이자수익은 주로 예금에서 발생한다.",
    answer: false,
    explanation: "은행의 이자수익은 대출금에서 발생. 예금은 이자비용의 원천.",
    hint: "은행은 대출로 돈을 벌고, 예금에 이자를 지급합니다.",
  },
  {
    id: "box06", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "후순위채권은 은행의 자본으로 분류된다.",
    answer: false,
    explanation: "후순위채권은 부채. 다만 BIS 자기자본비율 산정 시 일부 보완자본으로 인정.",
    hint: "재무제표상 부채이지만 자본건전성 규제에서는 일부 자본으로 인정합니다.",
  },
  {
    id: "box07", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "RP(환매조건부채권) 매도는 실질적으로 단기 자금 차입과 유사하다.",
    answer: true,
    explanation: "RP 매도: 증권을 담보로 일시적으로 자금을 조달. 만기에 재매입 조건 → 단기 차입 성격.",
    hint: "나중에 다시 사줘야 하므로 자금을 빌린 것과 유사합니다.",
  },
  {
    id: "box08", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "은행의 순이자마진(NIM)은 대출금리에서 예금금리를 뺀 값이다.",
    answer: true,
    explanation: "NIM = 이자수익 - 이자비용. 대출금리와 예금금리의 차이가 은행의 핵심 수익원.",
    hint: "NIM은 은행 수익성의 핵심 지표입니다.",
  },
  {
    id: "box09", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "CD(양도성예금증서)는 은행의 자산 계정이다.",
    answer: false,
    explanation: "은행이 발행한 CD는 부채. 투자자 입장에서는 자산이지만 발행 은행은 갚아야 할 의무.",
    hint: "발행자 입장에서 CD는 갚아야 할 채무입니다.",
  },
  {
    id: "box10", type: "ox", standard: "bank", category: "bank-ox", difficulty: "basic",
    text: "은행의 여신 건전성 분류에서 고정이하여신은 정상, 요주의, 고정, 회수의문, 추정손실 중 하위 3단계에 해당한다.",
    answer: true,
    explanation: "여신 건전성 분류: 정상 → 요주의 → 고정 → 회수의문 → 추정손실. 고정이하는 고정+회수의문+추정손실.",
    hint: "고정이하여신부터 부실채권으로 간주합니다.",
  },
  {
    id: "bcalc01", type: "calculation", standard: "bank", category: "bank-calc", difficulty: "basic",
    text: "대출금리 5%, 예금금리 2%, 대출금 잔액 100,000,000원, 예금 잔액 80,000,000원일 때 순이자수익은?",
    correctAnswer: 3400000,
    explanation: "이자수익 = 100,000,000 × 5% = 5,000,000. 이자비용 = 80,000,000 × 2% = 1,600,000. 순이자수익 = 5,000,000 - 1,600,000 = 3,400,000.",
    hint: "순이자수익 = 이자수익 - 이자비용",
  },
  {
    id: "bcalc02", type: "calculation", standard: "bank", category: "bank-calc", difficulty: "basic",
    text: "대출금 잔액 1,000,000원에 대해 고정이하여신 충당금률 20%를 적용할 때 대손충당금은?",
    correctAnswer: 200000,
    explanation: "대손충당금 = 1,000,000 × 20% = 200,000원.",
    hint: "충당금 = 대출금 잔액 × 충당금률",
  },
  {
    id: "bcalc03", type: "calculation", standard: "bank", category: "bank-calc", difficulty: "basic",
    text: "외화 USD 10,000 매입 환율 1,300원, 매도 환율 1,320원일 때 USD 10,000 매도 시 환전 수익은?",
    correctAnswer: 200000,
    explanation: "매도가 1,320 - 매입가 1,300 = 20원/달러. 수익 = $10,000 × 20원 = 200,000원.",
    hint: "환전 수익 = (매도환율 - 매입환율) × 외화 금액",
  },
  {
    id: "bcalc04", type: "calculation", standard: "bank", category: "bank-calc", difficulty: "basic",
    text: "예금 잔액 50,000,000원, 지급준비율 3.5%일 때 법정 지급준비금은?",
    correctAnswer: 1750000,
    explanation: "지급준비금 = 50,000,000 × 3.5% = 1,750,000원.",
    hint: "지급준비금 = 예금 잔액 × 지급준비율",
  },
  {
    id: "bcalc05", type: "calculation", standard: "bank", category: "bank-calc", difficulty: "basic",
    text: "RP 매도 10,000,000원, 7일 금리 연 2%일 때 7일 후 재매입 금액은?",
    correctAnswer: 10003836,
    explanation: "이자 = 10,000,000 × 2% × 7/365 = 3,836원(반올림). 재매입가 = 10,000,000 + 3,836 = 10,003,836원.",
    hint: "이자 = 원금 × 연이율 × 일수/365",
  },
  {
    id: "pjb01", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "정부로부터 운영보조금 5,000,000원을 보통예금으로 수령하였다.",
    debit: [{ account: "보통예금", amount: 5000000 }],
    credit: [{ account: "정부보조금수익", amount: 5000000 }],
    distractors: ["이연정부보조금", "자본금"],
    explanation: "운영 목적 보조금은 수령 시 즉시 수익 인식. 자산 취득 목적 보조금과 다름.",
    hint: "운영보조금은 바로 수익으로 인식하고, 자산보조금은 이연 처리합니다.",
  },
  {
    id: "pjb02", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "정부로부터 시설 취득 목적 보조금 10,000,000원을 수령하였다.",
    debit: [{ account: "현금", amount: 10000000 }],
    credit: [{ account: "이연정부보조금", amount: 10000000 }],
    distractors: ["정부보조금수익", "자본금"],
    explanation: "시설(자산) 취득 목적 보조금은 이연정부보조금(부채)으로 처리 후 자산 내용연수에 걸쳐 수익 인식.",
    hint: "자산 취득 목적 보조금은 이연 처리합니다.",
  },
  {
    id: "pjb03", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "요금수익(사용료) 3,000,000원을 현금으로 수취하였다.",
    debit: [{ account: "현금", amount: 3000000 }],
    credit: [{ account: "영업수익", amount: 3000000 }],
    distractors: ["매출", "정부보조금수익"],
    explanation: "공기업 사용료 수익은 영업수익으로 처리. 전기, 수도, 가스 등 공공서비스 요금.",
    hint: "공기업의 서비스 사용료는 영업수익으로 인식합니다.",
  },
  {
    id: "pjb04", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "공채 10,000,000원을 액면발행하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 10000000 }],
    credit: [{ account: "공채", amount: 10000000 }],
    distractors: ["사채", "장기차입금"],
    explanation: "공기업이 발행하는 채권은 공채(부채). 일반 기업의 사채와 유사.",
    hint: "공기업이 발행하는 채권을 공채라고 합니다.",
  },
  {
    id: "pjb05", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "시설투자를 위한 장기차입금 50,000,000원을 정책금융기관에서 차입하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 50000000 }],
    credit: [{ account: "장기차입금", amount: 50000000 }],
    distractors: ["공채", "단기차입금"],
    explanation: "장기 시설투자 차입금: 보통예금(자산) 증가, 장기차입금(부채) 증가.",
    hint: "만기가 1년 이상이면 장기차입금으로 분류합니다.",
  },
  {
    id: "pjb06", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "발전설비 감가상각비 2,000,000원을 인식하였다. (간접법)",
    debit: [{ account: "감가상각비", amount: 2000000 }],
    credit: [{ account: "감가상각누계액", amount: 2000000 }],
    distractors: ["발전설비", "수선비"],
    explanation: "간접법으로 감가상각비(비용) 인식, 감가상각누계액(차감계정) 계상.",
    hint: "공기업의 설비도 동일한 방식으로 감가상각합니다.",
  },
  {
    id: "pjb07", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "인건비(급여) 8,000,000원을 보통예금에서 이체하였다.",
    debit: [{ account: "급여", amount: 8000000 }],
    credit: [{ account: "보통예금", amount: 8000000 }],
    distractors: ["인건비", "현금"],
    explanation: "급여(비용) 발생, 보통예금(자산) 감소. 공기업도 일반기업과 동일.",
    hint: "공기업도 급여 지급은 일반 기업과 같은 방식으로 처리합니다.",
  },
  {
    id: "pjb08", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "요금 미수금 1,000,000원을 현금으로 수령하였다.",
    debit: [{ account: "현금", amount: 1000000 }],
    credit: [{ account: "미수금", amount: 1000000 }],
    distractors: ["영업수익", "외상매출금"],
    explanation: "미수금(자산) 회수: 현금(자산) 증가, 미수금(자산) 감소.",
    hint: "이미 수익으로 인식한 미수금을 회수하는 분개입니다.",
  },
  {
    id: "pjb09", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "공채 이자비용 500,000원을 보통예금에서 지급하였다.",
    debit: [{ account: "이자비용", amount: 500000 }],
    credit: [{ account: "보통예금", amount: 500000 }],
    distractors: ["공채", "현금"],
    explanation: "공채 이자 지급: 이자비용(비용) 발생, 보통예금(자산) 감소.",
    hint: "공채에 대한 이자 지급은 이자비용으로 처리합니다.",
  },
  {
    id: "pjb10", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "환경부담금 200,000원을 현금으로 납부하였다.",
    debit: [{ account: "세금과공과", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    distractors: ["환경비용", "미지급금"],
    explanation: "환경부담금 등 준조세성 비용은 세금과공과(비용)로 처리.",
    hint: "법정 부담금은 세금과공과 계정으로 처리합니다.",
  },
  {
    id: "pjb11", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "복구충당부채 3,000,000원을 설정하였다. (발전소 해체 의무)",
    debit: [{ account: "복구원가", amount: 3000000 }],
    credit: [{ account: "복구충당부채", amount: 3000000 }],
    distractors: ["유형자산", "충당부채"],
    explanation: "자산 해체/복구 의무가 있으면 복구충당부채(부채) 설정. 복구원가(비용 또는 자산 원가 가산) 인식.",
    hint: "발전소 등 해체 의무가 있는 자산은 복구충당부채를 설정합니다.",
  },
  {
    id: "pjb12", type: "journal", standard: "public", category: "public-basic", difficulty: "basic",
    text: "무상취득 토지의 공정가치 20,000,000원을 자산으로 인식하였다.",
    debit: [{ account: "토지", amount: 20000000 }],
    credit: [{ account: "자산수증이익", amount: 20000000 }],
    distractors: ["정부보조금수익", "자본금"],
    explanation: "무상으로 받은 자산: 토지(자산) 공정가치 인식, 자산수증이익(수익) 발생.",
    hint: "무상으로 받은 자산은 공정가치로 자산 인식하고 수익으로 처리합니다.",
  },
  {
    id: "pox01", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "공기업·준정부기관 회계기준은 기획재정부 고시로 정해진다.",
    answer: true,
    explanation: "공기업·준정부기관 회계기준은 기획재정부 고시. 민간기업의 K-IFRS(금융위원회)와 다름.",
    hint: "공기업 회계기준은 기획재정부 소관입니다.",
  },
  {
    id: "pox02", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "공기업이 받은 운영보조금은 이연 처리 후 분할 인식한다.",
    answer: false,
    explanation: "운영보조금은 수령 즉시 수익 인식. 이연 처리하는 것은 자산 취득 목적 보조금.",
    hint: "운영 목적과 자산 취득 목적 보조금의 처리가 다릅니다.",
  },
  {
    id: "pox03", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "공기업이 발행하는 채권을 공채라고 한다.",
    answer: true,
    explanation: "공기업 발행 채권은 공채. 회계처리는 일반 기업의 사채와 유사.",
    hint: "공기업이 발행하는 채권의 명칭입니다.",
  },
  {
    id: "pox04", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "공기업·준정부기관 회계기준에서 정하지 않은 사항은 K-IFRS를 따른다.",
    answer: true,
    explanation: "공기업·준정부기관 회계기준 미규정 사항은 K-IFRS 준용. 보충적 적용 관계.",
    hint: "공기업 회계기준은 K-IFRS를 보충적으로 준용합니다.",
  },
  {
    id: "pox05", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "무상으로 취득한 자산은 취득원가를 0원으로 처리한다.",
    answer: false,
    explanation: "무상취득 자산은 공정가치로 인식. 자산수증이익(수익) 계상.",
    hint: "공정가치로 측정하여 자산과 수익을 동시에 인식합니다.",
  },
  {
    id: "pox06", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "발전소 해체 의무가 있는 경우 복구충당부채를 설정해야 한다.",
    answer: true,
    explanation: "자산 해체·복구 의무는 복구충당부채(부채)로 인식. K-IFRS의 충당부채 요건과 동일.",
    hint: "미래 복구 의무도 현재 부채로 인식합니다.",
  },
  {
    id: "pox07", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "공기업의 영업수익은 정부보조금만 해당한다.",
    answer: false,
    explanation: "영업수익에는 요금수익(사용료), 정부보조금 외 서비스 판매 수익 등 다양한 항목 포함.",
    hint: "공기업도 요금수익, 서비스 수익 등 다양한 영업수익이 있습니다.",
  },
  {
    id: "pox08", type: "ox", standard: "public", category: "public-ox", difficulty: "basic",
    text: "준정부기관도 공기업과 동일한 회계기준을 적용한다.",
    answer: true,
    explanation: "공기업·준정부기관 회계기준이 양쪽 모두에 적용. 기획재정부 고시 기준.",
    hint: "두 기관 유형에 하나의 회계기준이 적용됩니다.",
  },
];
