export interface JournalEntry {
  account: string;
  amount: number;
}

export interface Problem {
  id: string;
  category: "basic" | "intermediate" | "advanced" | "practical";
  text: string;
  debit: JournalEntry[];
  credit: JournalEntry[];
  explanation: string;
  difficulty: 1 | 2 | 3;
  distractors: string[];
}

export interface Category {
  id: Problem["category"];
  name: string;
  description: string;
  emoji: string;
}

export const CATEGORIES: Category[] = [
  { id: "basic", name: "기본 분개", description: "초급 — 기본 거래의 분개", emoji: "📗" },
  { id: "intermediate", name: "거래 유형별", description: "중급 — 유형별 분개 연습", emoji: "📘" },
  { id: "advanced", name: "복합 거래", description: "고급 — 복합 거래 분개", emoji: "📕" },
  { id: "practical", name: "실무 사례", description: "실무 — 실제 업무 기반 문제", emoji: "📒" },
];

export const PROBLEMS: Problem[] = [
  // ── basic (15개) ──
  {
    id: "b01",
    category: "basic",
    text: "현금 500,000원을 출자하여 사업을 개시하였다.",
    debit: [{ account: "현금", amount: 500000 }],
    credit: [{ account: "자본금", amount: 500000 }],
    explanation: "사업주가 현금을 출자하면 자산(현금)이 증가하고 자본(자본금)이 증가합니다.",
    difficulty: 1,
    distractors: ["보통예금", "이익잉여금", "선수금"],
  },
  {
    id: "b02",
    category: "basic",
    text: "상품 1,000,000원을 현금으로 매입하였다.",
    debit: [{ account: "상품", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    explanation: "상품을 매입하면 자산(상품)이 증가하고, 현금으로 지급했으므로 자산(현금)이 감소합니다.",
    difficulty: 1,
    distractors: ["매출원가", "외상매입금", "선급금"],
  },
  {
    id: "b03",
    category: "basic",
    text: "상품 800,000원을 현금으로 판매하였다.",
    debit: [{ account: "현금", amount: 800000 }],
    credit: [{ account: "매출", amount: 800000 }],
    explanation: "상품을 판매하면 수익(매출)이 발생하고, 현금으로 받았으므로 자산(현금)이 증가합니다.",
    difficulty: 1,
    distractors: ["외상매출금", "선수금", "매출원가"],
  },
  {
    id: "b04",
    category: "basic",
    text: "상품 1,500,000원을 외상으로 매입하였다.",
    debit: [{ account: "상품", amount: 1500000 }],
    credit: [{ account: "외상매입금", amount: 1500000 }],
    explanation: "외상 매입이므로 자산(상품)이 증가하고 부채(외상매입금)가 증가합니다.",
    difficulty: 1,
    distractors: ["미지급금", "지급어음", "선수금"],
  },
  {
    id: "b05",
    category: "basic",
    text: "상품 2,000,000원을 외상으로 판매하였다.",
    debit: [{ account: "외상매출금", amount: 2000000 }],
    credit: [{ account: "매출", amount: 2000000 }],
    explanation: "외상 판매이므로 자산(외상매출금)이 증가하고 수익(매출)이 발생합니다.",
    difficulty: 1,
    distractors: ["미수금", "받을어음", "선급금"],
  },
  {
    id: "b06",
    category: "basic",
    text: "외상매입금 1,500,000원을 현금으로 지급하였다.",
    debit: [{ account: "외상매입금", amount: 1500000 }],
    credit: [{ account: "현금", amount: 1500000 }],
    explanation: "외상매입금을 갚으면 부채(외상매입금)가 감소하고 자산(현금)이 감소합니다.",
    difficulty: 1,
    distractors: ["미지급금", "지급어음", "상품"],
  },
  {
    id: "b07",
    category: "basic",
    text: "외상매출금 2,000,000원을 현금으로 회수하였다.",
    debit: [{ account: "현금", amount: 2000000 }],
    credit: [{ account: "외상매출금", amount: 2000000 }],
    explanation: "외상매출금을 회수하면 자산(현금)이 증가하고 자산(외상매출금)이 감소합니다.",
    difficulty: 1,
    distractors: ["미수금", "받을어음", "매출"],
  },
  {
    id: "b08",
    category: "basic",
    text: "은행에서 3,000,000원을 차입하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 3000000 }],
    credit: [{ account: "단기차입금", amount: 3000000 }],
    explanation: "차입하면 자산(보통예금)이 증가하고 부채(단기차입금)가 증가합니다.",
    difficulty: 1,
    distractors: ["현금", "장기차입금", "미지급금"],
  },
  {
    id: "b09",
    category: "basic",
    text: "임차료 300,000원을 현금으로 지급하였다.",
    debit: [{ account: "임차료", amount: 300000 }],
    credit: [{ account: "현금", amount: 300000 }],
    explanation: "임차료는 비용입니다. 비용 발생(차변) + 현금 감소(대변).",
    difficulty: 1,
    distractors: ["임대료수익", "선급비용", "미지급비용"],
  },
  {
    id: "b10",
    category: "basic",
    text: "급여 2,500,000원을 보통예금에서 이체 지급하였다.",
    debit: [{ account: "급여", amount: 2500000 }],
    credit: [{ account: "보통예금", amount: 2500000 }],
    explanation: "급여는 비용입니다. 비용 발생(차변) + 보통예금 감소(대변).",
    difficulty: 1,
    distractors: ["현금", "미지급비용", "예수금"],
  },
  {
    id: "b11",
    category: "basic",
    text: "비품 500,000원을 현금으로 구입하였다.",
    debit: [{ account: "비품", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    explanation: "비품(자산) 증가(차변) + 현금(자산) 감소(대변).",
    difficulty: 1,
    distractors: ["소모품비", "미지급금", "선급금"],
  },
  {
    id: "b12",
    category: "basic",
    text: "거래처에 현금 200,000원을 선급금으로 지급하였다.",
    debit: [{ account: "선급금", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    explanation: "선급금은 미리 지급한 금액으로 자산입니다. 자산(선급금) 증가(차변) + 현금 감소(대변).",
    difficulty: 1,
    distractors: ["선급비용", "선수금", "미지급금"],
  },
  {
    id: "b13",
    category: "basic",
    text: "고객으로부터 상품 대금 500,000원을 미리 받았다.",
    debit: [{ account: "현금", amount: 500000 }],
    credit: [{ account: "선수금", amount: 500000 }],
    explanation: "상품 인도 전에 받은 금액은 부채(선수금)입니다. 현금 증가(차변) + 선수금 증가(대변).",
    difficulty: 1,
    distractors: ["매출", "선급금", "예수금"],
  },
  {
    id: "b14",
    category: "basic",
    text: "보험료 120,000원을 현금으로 납부하였다.",
    debit: [{ account: "보험료", amount: 120000 }],
    credit: [{ account: "현금", amount: 120000 }],
    explanation: "보험료는 비용입니다. 비용 발생(차변) + 현금 감소(대변).",
    difficulty: 1,
    distractors: ["선급비용", "미지급비용", "세금과공과"],
  },
  {
    id: "b15",
    category: "basic",
    text: "은행 보통예금에서 이자 50,000원이 입금되었다.",
    debit: [{ account: "보통예금", amount: 50000 }],
    credit: [{ account: "이자수익", amount: 50000 }],
    explanation: "이자를 받으면 자산(보통예금)이 증가하고 수익(이자수익)이 발생합니다.",
    difficulty: 1,
    distractors: ["현금", "미수수익", "이자비용"],
  },
  // ── intermediate (10개) ──
  {
    id: "i01",
    category: "intermediate",
    text: "상품 매입 대금으로 약속어음 1,000,000원을 발행하였다.",
    debit: [{ account: "상품", amount: 1000000 }],
    credit: [{ account: "지급어음", amount: 1000000 }],
    explanation: "약속어음 발행은 부채(지급어음) 증가입니다. 어음으로 매입한 경우 외상매입금이 아니라 지급어음을 사용합니다.",
    difficulty: 2,
    distractors: ["외상매입금", "미지급금", "받을어음"],
  },
  {
    id: "i02",
    category: "intermediate",
    text: "상품을 판매하고 약속어음 1,200,000원을 받았다.",
    debit: [{ account: "받을어음", amount: 1200000 }],
    credit: [{ account: "매출", amount: 1200000 }],
    explanation: "약속어음을 받으면 자산(받을어음)이 증가합니다. 외상매출금과 구분하세요.",
    difficulty: 2,
    distractors: ["외상매출금", "미수금", "지급어음"],
  },
  {
    id: "i03",
    category: "intermediate",
    text: "단기차입금 3,000,000원과 이자 60,000원을 보통예금에서 상환하였다.",
    debit: [
      { account: "단기차입금", amount: 3000000 },
      { account: "이자비용", amount: 60000 },
    ],
    credit: [{ account: "보통예금", amount: 3060000 }],
    explanation: "차입금 상환 시 원금(부채 감소)과 이자(비용 발생)를 함께 처리합니다. 차변: 단기차입금 3,000,000 + 이자비용 60,000 = 대변: 보통예금 3,060,000.",
    difficulty: 2,
    distractors: ["장기차입금", "현금", "미지급비용"],
  },
  {
    id: "i04",
    category: "intermediate",
    text: "거래처에 현금 1,000,000원을 대여하였다.",
    debit: [{ account: "단기대여금", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    explanation: "돈을 빌려주면 자산(단기대여금)이 증가하고 현금이 감소합니다. 단기차입금과 혼동 주의.",
    difficulty: 2,
    distractors: ["단기차입금", "미수금", "선급금"],
  },
  {
    id: "i05",
    category: "intermediate",
    text: "건물 임대료 400,000원을 현금으로 받았다.",
    debit: [{ account: "현금", amount: 400000 }],
    credit: [{ account: "임대료수익", amount: 400000 }],
    explanation: "건물을 임대하고 받은 금액은 수익(임대료수익)입니다. 임차료(비용)와 구분하세요.",
    difficulty: 2,
    distractors: ["임차료", "선수수익", "미수수익"],
  },
  {
    id: "i06",
    category: "intermediate",
    text: "비품을 외상으로 800,000원에 구입하였다.",
    debit: [{ account: "비품", amount: 800000 }],
    credit: [{ account: "미지급금", amount: 800000 }],
    explanation: "상품 이외 자산의 외상 구입은 미지급금(부채)을 사용합니다. 외상매입금은 상품 거래에만 사용.",
    difficulty: 2,
    distractors: ["외상매입금", "지급어음", "미지급비용"],
  },
  {
    id: "i07",
    category: "intermediate",
    text: "차량운반구를 1,000,000원에 외상으로 처분하였다 (장부가액 800,000원).",
    debit: [{ account: "미수금", amount: 1000000 }],
    credit: [
      { account: "차량운반구", amount: 800000 },
      { account: "유형자산처분이익", amount: 200000 },
    ],
    explanation: "처분가액(1,000,000) > 장부가액(800,000)이므로 유형자산처분이익 200,000원 발생. 상품 외 자산 외상 처분은 미수금 사용.",
    difficulty: 2,
    distractors: ["외상매출금", "유형자산처분손실", "매출"],
  },
  {
    id: "i08",
    category: "intermediate",
    text: "광고선전비 500,000원을 보통예금에서 이체하였다.",
    debit: [{ account: "광고선전비", amount: 500000 }],
    credit: [{ account: "보통예금", amount: 500000 }],
    explanation: "광고선전비는 비용입니다. 비용 발생(차변) + 보통예금 감소(대변).",
    difficulty: 2,
    distractors: ["접대비", "현금", "미지급비용"],
  },
  {
    id: "i09",
    category: "intermediate",
    text: "출장 여비교통비 150,000원을 현금으로 지급하였다.",
    debit: [{ account: "여비교통비", amount: 150000 }],
    credit: [{ account: "현금", amount: 150000 }],
    explanation: "여비교통비는 비용입니다. 비용 발생(차변) + 현금 감소(대변).",
    difficulty: 2,
    distractors: ["운반비", "복리후생비", "미지급비용"],
  },
  {
    id: "i10",
    category: "intermediate",
    text: "건물 감가상각비 600,000원을 계상하였다.",
    debit: [{ account: "감가상각비", amount: 600000 }],
    credit: [{ account: "건물", amount: 600000 }],
    explanation: "감가상각은 비용(감가상각비)을 인식하고 자산(건물)의 장부가액을 감소시킵니다.",
    difficulty: 2,
    distractors: ["수선비", "임차료", "미지급비용"],
  },
  // ── advanced (5개) ──
  {
    id: "a01",
    category: "advanced",
    text: "상품 2,000,000원을 매입하고 대금 중 1,000,000원은 약속어음을 발행하고 나머지는 외상으로 하였다.",
    debit: [{ account: "상품", amount: 2000000 }],
    credit: [
      { account: "지급어음", amount: 1000000 },
      { account: "외상매입금", amount: 1000000 },
    ],
    explanation: "복합 결제: 어음 발행분은 지급어음, 나머지 외상은 외상매입금. 차변 2,000,000 = 대변 1,000,000 + 1,000,000.",
    difficulty: 3,
    distractors: ["현금", "미지급금", "받을어음"],
  },
  {
    id: "a02",
    category: "advanced",
    text: "급여 3,000,000원에서 소득세 예수금 200,000원을 공제하고 나머지를 보통예금에서 이체하였다.",
    debit: [{ account: "급여", amount: 3000000 }],
    credit: [
      { account: "예수금", amount: 200000 },
      { account: "보통예금", amount: 2800000 },
    ],
    explanation: "급여 총액은 비용(차변). 원천징수분은 예수금(부채), 실지급액은 보통예금 감소. 차변 3,000,000 = 대변 200,000 + 2,800,000.",
    difficulty: 3,
    distractors: ["현금", "미지급비용", "세금과공과"],
  },
  {
    id: "a03",
    category: "advanced",
    text: "비품(장부가액 500,000원)을 300,000원에 현금 처분하였다.",
    debit: [
      { account: "현금", amount: 300000 },
      { account: "유형자산처분손실", amount: 200000 },
    ],
    credit: [{ account: "비품", amount: 500000 }],
    explanation: "처분가액(300,000) < 장부가액(500,000)이므로 유형자산처분손실 200,000원 발생. 차변 300,000 + 200,000 = 대변 500,000.",
    difficulty: 3,
    distractors: ["유형자산처분이익", "미수금", "감가상각비"],
  },
  {
    id: "a04",
    category: "advanced",
    text: "선급한 보험료 중 당기 해당분 80,000원을 비용으로 대체하였다.",
    debit: [{ account: "보험료", amount: 80000 }],
    credit: [{ account: "선급비용", amount: 80000 }],
    explanation: "선급비용(자산)에서 당기 비용으로 대체하는 결산 수정분개입니다. 비용 증가(차변) + 선급비용 감소(대변).",
    difficulty: 3,
    distractors: ["선급금", "미지급비용", "현금"],
  },
  {
    id: "a05",
    category: "advanced",
    text: "임대료 중 차기분 100,000원을 선수수익으로 수정하였다.",
    debit: [{ account: "임대료수익", amount: 100000 }],
    credit: [{ account: "선수수익", amount: 100000 }],
    explanation: "당기에 받았지만 차기에 귀속되는 수익을 선수수익(부채)으로 이연하는 결산 수정분개입니다.",
    difficulty: 3,
    distractors: ["선수금", "미수수익", "임차료"],
  },
  // ── practical (5개) ──
  {
    id: "p01",
    category: "practical",
    text: "사무실 월세 1,100,000원(부가세 포함)을 보통예금에서 이체하였다. (공급가액 1,000,000원, 부가세 100,000원)",
    debit: [
      { account: "임차료", amount: 1000000 },
      { account: "부가세예수금", amount: 100000 },
    ],
    credit: [{ account: "보통예금", amount: 1100000 }],
    explanation: "부가세 포함 거래. 공급가액은 임차료(비용), 부가세는 부가세예수금으로 처리. 차변 1,000,000 + 100,000 = 대변 1,100,000.",
    difficulty: 2,
    distractors: ["현금", "미지급비용", "선급비용", "세금과공과"],
  },
  {
    id: "p02",
    category: "practical",
    text: "직원 회식비 200,000원을 법인카드(미지급금)로 결제하였다.",
    debit: [{ account: "복리후생비", amount: 200000 }],
    credit: [{ account: "미지급금", amount: 200000 }],
    explanation: "직원 회식비는 복리후생비(비용). 법인카드 결제는 미지급금(부채)으로 처리합니다. 접대비와 구분: 접대비는 외부 거래처 대상.",
    difficulty: 2,
    distractors: ["접대비", "외상매입금", "현금", "급여"],
  },
  {
    id: "p03",
    category: "practical",
    text: "거래처 접대를 위해 식사비 300,000원을 현금으로 지급하였다.",
    debit: [{ account: "접대비", amount: 300000 }],
    credit: [{ account: "현금", amount: 300000 }],
    explanation: "외부 거래처 접대 비용은 접대비입니다. 직원 대상 회식(복리후생비)과 구분하세요.",
    difficulty: 2,
    distractors: ["복리후생비", "광고선전비", "여비교통비"],
  },
  {
    id: "p04",
    category: "practical",
    text: "사무용 소모품 80,000원을 현금으로 구입하였다.",
    debit: [{ account: "소모품비", amount: 80000 }],
    credit: [{ account: "현금", amount: 80000 }],
    explanation: "소모품은 즉시 비용 처리하는 경우 소모품비(비용)로 기록합니다. 비품(자산)과 구분: 소모품은 단기 소모성.",
    difficulty: 2,
    distractors: ["비품", "선급금", "미지급금"],
  },
  {
    id: "p05",
    category: "practical",
    text: "전기요금 150,000원이 보통예금에서 자동이체되었다.",
    debit: [{ account: "수도광열비", amount: 150000 }],
    credit: [{ account: "보통예금", amount: 150000 }],
    explanation: "전기요금은 수도광열비(비용)입니다. 통신비와 구분하세요.",
    difficulty: 2,
    distractors: ["통신비", "현금", "미지급비용", "세금과공과"],
  },
];
