export interface JournalEntry {
  account: string;
  amount: number;
}

export interface Problem {
  id: string;
  type: "journal" | "ox" | "calculation" | "statement";
  standard: string;
  category: string;
  difficulty: "basic" | "intermediate" | "advanced" | "practical";
  text: string;
  // 분개형
  debit?: JournalEntry[];
  credit?: JournalEntry[];
  distractors?: string[];
  // OX형
  answer?: boolean;
  // 계산형
  correctAnswer?: number;
  // 공통
  explanation: string;
  hint?: string;
}

export const PROBLEMS: Problem[] = [
  // ══════════════════════════════════════
  // common / journal-basic (20개)
  // ══════════════════════════════════════
  {
    id: "cjb01", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "현금 500,000원을 출자하여 사업을 개시하였다.",
    debit: [{ account: "현금", amount: 500000 }],
    credit: [{ account: "자본금", amount: 500000 }],
    explanation: "사업주가 현금을 출자하면 자산(현금) 증가, 자본(자본금) 증가.",
    distractors: ["보통예금", "이익잉여금", "선수금"],
  },
  {
    id: "cjb02", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 1,000,000원을 현금으로 매입하였다.",
    debit: [{ account: "상품", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    explanation: "상품(자산) 증가, 현금(자산) 감소.",
    distractors: ["매출원가", "외상매입금", "선급금"],
  },
  {
    id: "cjb03", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 800,000원을 현금으로 판매하였다.",
    debit: [{ account: "현금", amount: 800000 }],
    credit: [{ account: "매출", amount: 800000 }],
    explanation: "현금(자산) 증가, 매출(수익) 발생.",
    distractors: ["외상매출금", "선수금", "매출원가"],
  },
  {
    id: "cjb04", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 1,500,000원을 외상으로 매입하였다.",
    debit: [{ account: "상품", amount: 1500000 }],
    credit: [{ account: "외상매입금", amount: 1500000 }],
    explanation: "외상 매입: 상품(자산) 증가, 외상매입금(부채) 증가.",
    distractors: ["미지급금", "지급어음", "선수금"],
  },
  {
    id: "cjb05", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 2,000,000원을 외상으로 판매하였다.",
    debit: [{ account: "외상매출금", amount: 2000000 }],
    credit: [{ account: "매출", amount: 2000000 }],
    explanation: "외상 판매: 외상매출금(자산) 증가, 매출(수익) 발생.",
    distractors: ["미수금", "받을어음", "선급금"],
  },
  {
    id: "cjb06", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "외상매입금 1,500,000원을 현금으로 지급하였다.",
    debit: [{ account: "외상매입금", amount: 1500000 }],
    credit: [{ account: "현금", amount: 1500000 }],
    explanation: "외상매입금(부채) 감소, 현금(자산) 감소.",
    distractors: ["미지급금", "지급어음", "상품"],
  },
  {
    id: "cjb07", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "외상매출금 2,000,000원을 현금으로 회수하였다.",
    debit: [{ account: "현금", amount: 2000000 }],
    credit: [{ account: "외상매출금", amount: 2000000 }],
    explanation: "현금(자산) 증가, 외상매출금(자산) 감소.",
    distractors: ["미수금", "받을어음", "매출"],
  },
  {
    id: "cjb08", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "은행에서 3,000,000원을 차입하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 3000000 }],
    credit: [{ account: "단기차입금", amount: 3000000 }],
    explanation: "보통예금(자산) 증가, 단기차입금(부채) 증가.",
    distractors: ["현금", "장기차입금", "미지급금"],
  },
  {
    id: "cjb09", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "임차료 300,000원을 현금으로 지급하였다.",
    debit: [{ account: "임차료", amount: 300000 }],
    credit: [{ account: "현금", amount: 300000 }],
    explanation: "임차료(비용) 발생, 현금(자산) 감소.",
    distractors: ["임대료수익", "선급비용", "미지급비용"],
  },
  {
    id: "cjb10", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "급여 2,500,000원을 보통예금에서 이체 지급하였다.",
    debit: [{ account: "급여", amount: 2500000 }],
    credit: [{ account: "보통예금", amount: 2500000 }],
    explanation: "급여(비용) 발생, 보통예금(자산) 감소.",
    distractors: ["현금", "미지급비용", "예수금"],
  },
  {
    id: "cjb11", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "비품 500,000원을 현금으로 구입하였다.",
    debit: [{ account: "비품", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    explanation: "비품(자산) 증가, 현금(자산) 감소.",
    distractors: ["소모품비", "미지급금", "선급금"],
  },
  {
    id: "cjb12", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "거래처에 현금 200,000원을 선급금으로 지급하였다.",
    debit: [{ account: "선급금", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    explanation: "선급금(자산) 증가, 현금(자산) 감소. 선급금은 미리 지급한 금액.",
    distractors: ["선급비용", "선수금", "미지급금"],
  },
  {
    id: "cjb13", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "고객으로부터 상품 대금 500,000원을 미리 받았다.",
    debit: [{ account: "현금", amount: 500000 }],
    credit: [{ account: "선수금", amount: 500000 }],
    explanation: "현금(자산) 증가, 선수금(부채) 증가. 상품 인도 전에 받은 금액은 부채.",
    distractors: ["매출", "선급금", "예수금"],
  },
  {
    id: "cjb14", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "보험료 120,000원을 현금으로 납부하였다.",
    debit: [{ account: "보험료", amount: 120000 }],
    credit: [{ account: "현금", amount: 120000 }],
    explanation: "보험료(비용) 발생, 현금(자산) 감소.",
    distractors: ["선급비용", "미지급비용", "세금과공과"],
  },
  {
    id: "cjb15", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "은행 보통예금에서 이자 50,000원이 입금되었다.",
    debit: [{ account: "보통예금", amount: 50000 }],
    credit: [{ account: "이자수익", amount: 50000 }],
    explanation: "보통예금(자산) 증가, 이자수익(수익) 발생.",
    distractors: ["현금", "미수수익", "이자비용"],
  },
  {
    id: "cjb16", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품 매입 대금으로 약속어음 1,000,000원을 발행하였다.",
    debit: [{ account: "상품", amount: 1000000 }],
    credit: [{ account: "지급어음", amount: 1000000 }],
    explanation: "상품(자산) 증가, 지급어음(부채) 증가. 어음 발행은 외상매입금과 구분.",
    distractors: ["외상매입금", "미지급금", "받을어음"],
  },
  {
    id: "cjb17", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "상품을 판매하고 약속어음 1,200,000원을 받았다.",
    debit: [{ account: "받을어음", amount: 1200000 }],
    credit: [{ account: "매출", amount: 1200000 }],
    explanation: "받을어음(자산) 증가, 매출(수익) 발생. 외상매출금과 구분.",
    distractors: ["외상매출금", "미수금", "지급어음"],
  },
  {
    id: "cjb18", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "거래처에 현금 1,000,000원을 대여하였다.",
    debit: [{ account: "단기대여금", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    explanation: "단기대여금(자산) 증가, 현금(자산) 감소. 단기차입금과 혼동 주의.",
    distractors: ["단기차입금", "미수금", "선급금"],
  },
  {
    id: "cjb19", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "건물 임대료 400,000원을 현금으로 받았다.",
    debit: [{ account: "현금", amount: 400000 }],
    credit: [{ account: "임대료수익", amount: 400000 }],
    explanation: "현금(자산) 증가, 임대료수익(수익) 발생. 임차료(비용)와 구분.",
    distractors: ["임차료", "선수수익", "미수수익"],
  },
  {
    id: "cjb20", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "광고선전비 500,000원을 보통예금에서 이체하였다.",
    debit: [{ account: "광고선전비", amount: 500000 }],
    credit: [{ account: "보통예금", amount: 500000 }],
    explanation: "광고선전비(비용) 발생, 보통예금(자산) 감소.",
    distractors: ["접대비", "현금", "미지급비용"],
  },
  // ══════════════════════════════════════
  // common / journal-intermediate (10개)
  // ══════════════════════════════════════
  {
    id: "cji01", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "단기차입금 3,000,000원과 이자 60,000원을 보통예금에서 상환하였다.",
    debit: [
      { account: "단기차입금", amount: 3000000 },
      { account: "이자비용", amount: 60000 },
    ],
    credit: [{ account: "보통예금", amount: 3060000 }],
    explanation: "원금(부채 감소) + 이자(비용 발생). 차변 합계 3,060,000 = 대변 3,060,000.",
    distractors: ["장기차입금", "현금", "미지급비용"],
  },
  {
    id: "cji02", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "비품을 외상으로 800,000원에 구입하였다.",
    debit: [{ account: "비품", amount: 800000 }],
    credit: [{ account: "미지급금", amount: 800000 }],
    explanation: "상품 이외 자산의 외상 구입은 미지급금. 외상매입금은 상품 거래에만 사용.",
    distractors: ["외상매입금", "지급어음", "미지급비용"],
  },
  {
    id: "cji03", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "차량운반구를 1,000,000원에 외상으로 처분하였다 (장부가액 800,000원).",
    debit: [{ account: "미수금", amount: 1000000 }],
    credit: [
      { account: "차량운반구", amount: 800000 },
      { account: "유형자산처분이익", amount: 200000 },
    ],
    explanation: "처분가액 > 장부가액 → 처분이익 200,000. 상품 외 자산 처분은 미수금 사용.",
    distractors: ["외상매출금", "유형자산처분손실", "매출"],
  },
  {
    id: "cji04", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "상품 2,000,000원 매입. 1,000,000원은 약속어음, 나머지는 외상.",
    debit: [{ account: "상품", amount: 2000000 }],
    credit: [
      { account: "지급어음", amount: 1000000 },
      { account: "외상매입금", amount: 1000000 },
    ],
    explanation: "복합 결제: 어음분은 지급어음, 외상분은 외상매입금.",
    distractors: ["현금", "미지급금", "받을어음"],
  },
  {
    id: "cji05", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "급여 3,000,000원에서 소득세 예수금 200,000원을 공제, 나머지를 보통예금 이체.",
    debit: [{ account: "급여", amount: 3000000 }],
    credit: [
      { account: "예수금", amount: 200000 },
      { account: "보통예금", amount: 2800000 },
    ],
    explanation: "급여 총액(비용). 원천징수 → 예수금(부채), 실지급 → 보통예금 감소.",
    distractors: ["현금", "미지급비용", "세금과공과"],
  },
  {
    id: "cji06", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "비품(장부가액 500,000원)을 300,000원에 현금 처분하였다.",
    debit: [
      { account: "현금", amount: 300000 },
      { account: "유형자산처분손실", amount: 200000 },
    ],
    credit: [{ account: "비품", amount: 500000 }],
    explanation: "처분가액 < 장부가액 → 처분손실 200,000.",
    distractors: ["유형자산처분이익", "미수금", "감가상각비"],
  },
  {
    id: "cji07", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "선급한 보험료 중 당기 해당분 80,000원을 비용으로 대체하였다.",
    debit: [{ account: "보험료", amount: 80000 }],
    credit: [{ account: "선급비용", amount: 80000 }],
    explanation: "결산 수정분개. 선급비용(자산) 감소 → 보험료(비용) 인식.",
    distractors: ["선급금", "미지급비용", "현금"],
  },
  {
    id: "cji08", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "임대료 중 차기분 100,000원을 선수수익으로 수정하였다.",
    debit: [{ account: "임대료수익", amount: 100000 }],
    credit: [{ account: "선수수익", amount: 100000 }],
    explanation: "결산 수정분개. 차기 귀속 수익을 선수수익(부채)으로 이연.",
    distractors: ["선수금", "미수수익", "임차료"],
  },
  {
    id: "cji09", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "건물 감가상각비 600,000원을 계상하였다.",
    debit: [{ account: "감가상각비", amount: 600000 }],
    credit: [{ account: "건물", amount: 600000 }],
    explanation: "감가상각비(비용) 인식, 건물(자산) 장부가액 감소.",
    distractors: ["수선비", "임차료", "미지급비용"],
  },
  {
    id: "cji10", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "사무실 월세 1,100,000원(부가세 포함) 보통예금 이체. (공급가액 1,000,000, 부가세 100,000)",
    debit: [
      { account: "임차료", amount: 1000000 },
      { account: "부가세예수금", amount: 100000 },
    ],
    credit: [{ account: "보통예금", amount: 1100000 }],
    explanation: "공급가액 → 임차료(비용), 부가세 → 부가세예수금. 합계 일치 확인.",
    distractors: ["현금", "미지급비용", "선급비용", "세금과공과"],
  },
  // ══════════════════════════════════════
  // common / ox-basic (10개)
  // ══════════════════════════════════════
  {
    id: "cox01", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "자산이 증가하면 차변(왼쪽)에 기록한다.",
    answer: true,
    explanation: "자산의 증가는 차변, 감소는 대변에 기록합니다.",
  },
  {
    id: "cox02", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "부채가 증가하면 차변(왼쪽)에 기록한다.",
    answer: false,
    explanation: "부채의 증가는 대변(오른쪽)에 기록합니다. 부채 감소가 차변입니다.",
  },
  {
    id: "cox03", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "비용이 발생하면 대변(오른쪽)에 기록한다.",
    answer: false,
    explanation: "비용의 발생은 차변(왼쪽)에 기록합니다.",
  },
  {
    id: "cox04", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "수익이 발생하면 대변(오른쪽)에 기록한다.",
    answer: true,
    explanation: "수익의 발생은 대변에 기록합니다.",
  },
  {
    id: "cox05", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "외상매입금과 미지급금은 같은 계정과목이다.",
    answer: false,
    explanation: "외상매입금은 상품 매입 대금, 미지급금은 상품 외 거래 대금입니다.",
  },
  {
    id: "cox06", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "선급금은 부채 계정이다.",
    answer: false,
    explanation: "선급금은 미리 지급한 금액으로 자산 계정입니다. 선수금이 부채.",
  },
  {
    id: "cox07", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "분개에서 차변 합계와 대변 합계는 항상 일치해야 한다.",
    answer: true,
    explanation: "복식부기의 기본 원리. 대차평균의 원리.",
  },
  {
    id: "cox08", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "감가상각비는 자산 계정이다.",
    answer: false,
    explanation: "감가상각비는 비용 계정입니다. 자산의 가치 감소를 비용으로 인식.",
  },
  {
    id: "cox09", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "이자수익은 비용 계정이다.",
    answer: false,
    explanation: "이자수익은 수익 계정입니다. 이자비용이 비용.",
  },
  {
    id: "cox10", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "재무상태표는 일정 시점의 자산, 부채, 자본을 나타낸다.",
    answer: true,
    explanation: "재무상태표(대차대조표)는 특정 시점의 재무 상태를 보여줍니다. 손익계산서가 기간.",
  },
  // ══════════════════════════════════════
  // k-ifrs / kifrs-basic (10개)
  // ══════════════════════════════════════
  {
    id: "kb01", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "상품 1,000,000원을 외상으로 매입하였다. (K-IFRS: 매입채무 사용)",
    debit: [{ account: "재고자산", amount: 1000000 }],
    credit: [{ account: "매입채무", amount: 1000000 }],
    explanation: "K-IFRS에서는 상품 대신 재고자산, 외상매입금 대신 매입채무를 사용합니다.",
    distractors: ["상품", "외상매입금", "미지급금"],
  },
  {
    id: "kb02", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "상품 2,000,000원을 외상으로 판매하였다. (K-IFRS: 매출채권 사용)",
    debit: [{ account: "매출채권", amount: 2000000 }],
    credit: [{ account: "매출", amount: 2000000 }],
    explanation: "K-IFRS에서는 외상매출금 대신 매출채권을 사용합니다.",
    distractors: ["외상매출금", "미수금", "받을어음"],
  },
  {
    id: "kb03", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매출채권 500,000원에 대해 대손상각비를 인식하였다.",
    debit: [{ account: "대손상각비", amount: 500000 }],
    credit: [{ account: "매출채권", amount: 500000 }],
    explanation: "매출채권 회수 불가능 시 대손상각비(비용) 인식, 매출채권(자산) 감소.",
    distractors: ["유형자산처분손실", "충당부채", "이자비용"],
  },
  {
    id: "kb04", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "건물 감가상각비 1,200,000원을 인식하였다.",
    debit: [{ account: "감가상각비", amount: 1200000 }],
    credit: [{ account: "건물", amount: 1200000 }],
    explanation: "감가상각비(비용) 인식, 건물(자산) 장부가액 감소.",
    distractors: ["수선비", "임차료", "투자부동산"],
  },
  {
    id: "kb05", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "토지를 50,000,000원에 현금으로 취득하였다.",
    debit: [{ account: "토지", amount: 50000000 }],
    credit: [{ account: "현금", amount: 50000000 }],
    explanation: "토지(자산) 증가, 현금(자산) 감소. K-IFRS와 일반기업회계기준 동일.",
    distractors: ["건물", "투자부동산", "보통예금"],
  },
  {
    id: "kb06", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "재고자산 평가손실 300,000원을 인식하였다.",
    debit: [{ account: "재고자산평가손실", amount: 300000 }],
    credit: [{ account: "재고자산", amount: 300000 }],
    explanation: "재고자산의 순실현가능가치가 취득원가보다 낮을 때 평가손실 인식.",
    distractors: ["매출원가", "상품", "감가상각비"],
  },
  {
    id: "kb07", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "충당부채 2,000,000원을 설정하였다. (제품 보증 관련)",
    debit: [{ account: "제품보증비", amount: 2000000 }],
    credit: [{ account: "충당부채", amount: 2000000 }],
    explanation: "제품보증비(비용) 인식, 충당부채(부채) 설정. 미래 보증 지출이 예상될 때 인식.",
    hint: "충당부채는 금액이나 시기가 불확실한 부채입니다.",
    distractors: ["미지급비용", "선수금", "예수금"],
  },
  {
    id: "kb08", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매입채무 1,000,000원을 보통예금으로 결제하였다.",
    debit: [{ account: "매입채무", amount: 1000000 }],
    credit: [{ account: "보통예금", amount: 1000000 }],
    explanation: "매입채무(부채) 감소, 보통예금(자산) 감소.",
    distractors: ["외상매입금", "미지급금", "현금"],
  },
  {
    id: "kb09", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "기계장치 10,000,000원을 보통예금으로 구입하였다.",
    debit: [{ account: "기계장치", amount: 10000000 }],
    credit: [{ account: "보통예금", amount: 10000000 }],
    explanation: "기계장치(자산) 증가, 보통예금(자산) 감소.",
    distractors: ["비품", "현금", "미지급금"],
  },
  {
    id: "kb10", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "장기차입금 5,000,000원을 보통예금으로 상환하였다.",
    debit: [{ account: "장기차입금", amount: 5000000 }],
    credit: [{ account: "보통예금", amount: 5000000 }],
    explanation: "장기차입금(부채) 감소, 보통예금(자산) 감소.",
    distractors: ["단기차입금", "현금", "이자비용"],
  },
  // ══════════════════════════════════════
  // k-ifrs / kifrs-intermediate (5개)
  // ══════════════════════════════════════
  {
    id: "ki01", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "사용권자산 12,000,000원과 리스부채 12,000,000원을 인식하였다. (IFRS 16 리스)",
    debit: [{ account: "사용권자산", amount: 12000000 }],
    credit: [{ account: "리스부채", amount: 12000000 }],
    explanation: "IFRS 16: 리스이용자는 사용권자산(자산)과 리스부채(부채)를 인식합니다.",
    distractors: ["비품", "임차료", "장기차입금"],
  },
  {
    id: "ki02", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "리스부채 이자비용 200,000원을 인식하였다.",
    debit: [{ account: "이자비용", amount: 200000 }],
    credit: [{ account: "리스부채", amount: 200000 }],
    explanation: "리스부채에 대한 이자비용 인식. 리스부채 장부금액 증가(유효이자법).",
    distractors: ["임차료", "감가상각비", "미지급비용"],
  },
  {
    id: "ki03", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "사용권자산 감가상각비 2,400,000원을 인식하였다.",
    debit: [{ account: "감가상각비", amount: 2400000 }],
    credit: [{ account: "사용권자산", amount: 2400000 }],
    explanation: "사용권자산을 리스기간에 걸쳐 감가상각합니다.",
    distractors: ["임차료", "리스부채", "건물"],
  },
  {
    id: "ki04", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "투자부동산(건물)의 감가상각비 800,000원을 인식하였다. (원가모형)",
    debit: [{ account: "감가상각비", amount: 800000 }],
    credit: [{ account: "투자부동산", amount: 800000 }],
    explanation: "투자부동산 원가모형 적용 시 감가상각비를 인식합니다.",
    distractors: ["건물", "임대료수익", "수선비"],
  },
  {
    id: "ki05", type: "journal", standard: "k-ifrs", category: "kifrs-intermediate", difficulty: "intermediate",
    text: "매출채권 800,000원에 대해 대손충당금(충당부채)을 설정하였다.",
    debit: [{ account: "대손상각비", amount: 800000 }],
    credit: [{ account: "충당부채", amount: 800000 }],
    explanation: "예상 대손에 대해 대손상각비(비용)를 인식하고 충당부채를 설정합니다.",
    distractors: ["매출채권", "미지급비용", "유형자산처분손실"],
  },
  // ══════════════════════════════════════
  // k-ifrs / kifrs-ox (10개)
  // ══════════════════════════════════════
  {
    id: "kox01", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "K-IFRS에서 재고자산은 취득원가와 순실현가능가치 중 낮은 금액으로 평가한다.",
    answer: true,
    explanation: "저가법 적용. 순실현가능가치가 낮으면 평가손실 인식.",
  },
  {
    id: "kox02", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "K-IFRS에서 외상매출금은 매출채권으로 표시한다.",
    answer: true,
    explanation: "K-IFRS는 매출채권, 일반기업회계기준은 외상매출금 사용.",
  },
  {
    id: "kox03", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "IFRS 16에 따라 리스이용자는 모든 리스를 운용리스와 금융리스로 구분한다.",
    answer: false,
    explanation: "IFRS 16은 리스이용자의 운용/금융리스 구분을 폐지. 단일 모델로 사용권자산과 리스부채를 인식.",
  },
  {
    id: "kox04", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "사용권자산은 리스부채와 동일한 금액으로 최초 인식한다.",
    answer: false,
    explanation: "사용권자산 = 리스부채 + 선급리스료 + 초기직접원가 + 복구원가 등. 동일하지 않을 수 있음.",
  },
  {
    id: "kox05", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "K-IFRS에서 투자부동산은 원가모형 또는 공정가치모형을 선택 적용할 수 있다.",
    answer: true,
    explanation: "원가모형과 공정가치모형 중 선택. 공정가치모형은 감가상각 불필요.",
  },
  {
    id: "kox06", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "충당부채는 지출의 시기 또는 금액이 불확실한 부채이다.",
    answer: true,
    explanation: "현재 의무, 경제적 효익 유출 가능성, 신뢰성 있는 추정 세 가지 조건 충족 시 인식.",
  },
  {
    id: "kox07", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "K-IFRS에서 유형자산은 원가모형만 적용할 수 있다.",
    answer: false,
    explanation: "원가모형과 재평가모형 중 선택 가능. 재평가모형은 공정가치로 재평가.",
  },
  {
    id: "kox08", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "대손충당금은 매출채권에서 차감하는 형식으로 표시한다.",
    answer: true,
    explanation: "재무상태표에서 매출채권 차감 표시. 순액으로 보고.",
  },
  {
    id: "kox09", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "intermediate",
    text: "K-IFRS에서 연구비는 자산으로 인식할 수 있다.",
    answer: false,
    explanation: "연구단계 지출은 전액 비용. 개발단계 지출만 조건 충족 시 무형자산 인식 가능.",
  },
  {
    id: "kox10", type: "ox", standard: "k-ifrs", category: "kifrs-ox", difficulty: "basic",
    text: "기타포괄손익은 당기손익에 포함된다.",
    answer: false,
    explanation: "기타포괄손익은 당기손익과 구분. 포괄손익계산서에 별도 표시.",
  },
  // ══════════════════════════════════════
  // Batch 1 추가 (90개)
  // ══════════════════════════════════════
  {
    id: "cjb21", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "소모품 150,000원을 현금으로 구입하였다.",
    debit: [{ account: "소모품", amount: 150000 }],
    credit: [{ account: "현금", amount: 150000 }],
    distractors: ["소모품비", "미지급금", "선급금"],
    explanation: "소모품(자산) 증가, 현금(자산) 감소. 소모품은 자산, 소모품비는 비용으로 구분.",
    hint: "구입한 소모품은 아직 사용 전이므로 자산입니다.",
  },
  {
    id: "cjb22", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "소모품 150,000원 중 100,000원을 사용하였다.",
    debit: [{ account: "소모품비", amount: 100000 }],
    credit: [{ account: "소모품", amount: 100000 }],
    distractors: ["현금", "미지급비용"],
    explanation: "소모품 사용분은 소모품비(비용)로 대체. 소모품(자산) 감소.",
    hint: "사용한 소모품은 비용으로 전환됩니다.",
  },
  {
    id: "cjb23", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "단기차입금 2,000,000원을 현금으로 상환하였다.",
    debit: [{ account: "단기차입금", amount: 2000000 }],
    credit: [{ account: "현금", amount: 2000000 }],
    distractors: ["장기차입금", "보통예금"],
    explanation: "단기차입금(부채) 감소, 현금(자산) 감소.",
    hint: "빌린 돈을 갚으면 부채가 줄어듭니다.",
  },
  {
    id: "cjb24", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "건물 화재보험료 240,000원을 보통예금에서 이체하였다.",
    debit: [{ account: "보험료", amount: 240000 }],
    credit: [{ account: "보통예금", amount: 240000 }],
    distractors: ["선급비용", "현금"],
    explanation: "보험료(비용) 발생, 보통예금(자산) 감소.",
    hint: "당기에 해당하는 보험료는 비용으로 처리합니다.",
  },
  {
    id: "cjb25", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "수수료 수익 80,000원을 현금으로 받았다.",
    debit: [{ account: "현금", amount: 80000 }],
    credit: [{ account: "수수료수익", amount: 80000 }],
    distractors: ["미수수익", "수수료비용"],
    explanation: "현금(자산) 증가, 수수료수익(수익) 발생.",
    hint: "용역을 제공하고 받은 대가는 수익입니다.",
  },
  {
    id: "cjb26", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "직원 출장비 200,000원을 현금으로 지급하였다.",
    debit: [{ account: "여비교통비", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    distractors: ["복리후생비", "미지급비용"],
    explanation: "여비교통비(비용) 발생, 현금(자산) 감소.",
    hint: "출장 관련 비용은 여비교통비 계정을 사용합니다.",
  },
  {
    id: "cjb27", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "주주총회에서 현금 배당금 500,000원을 결의하였다.",
    debit: [{ account: "이익잉여금", amount: 500000 }],
    credit: [{ account: "미지급배당금", amount: 500000 }],
    distractors: ["자본금", "현금"],
    explanation: "배당 결의 시 이익잉여금(자본) 감소, 미지급배당금(부채) 증가. 실제 지급 시 현금 감소.",
    hint: "배당 결의는 지급 전이므로 미지급 부채로 처리합니다.",
  },
  {
    id: "cjb28", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "미지급배당금 500,000원을 현금으로 지급하였다.",
    debit: [{ account: "미지급배당금", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["이익잉여금", "보통예금"],
    explanation: "미지급배당금(부채) 감소, 현금(자산) 감소.",
    hint: "이미 결의된 배당금을 실제로 지급하는 분개입니다.",
  },
  {
    id: "cjb29", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "세금과공과 30,000원을 현금으로 납부하였다.",
    debit: [{ account: "세금과공과", amount: 30000 }],
    credit: [{ account: "현금", amount: 30000 }],
    distractors: ["법인세비용", "미지급세금"],
    explanation: "세금과공과(비용) 발생, 현금(자산) 감소.",
    hint: "재산세, 자동차세 등은 세금과공과 계정을 사용합니다.",
  },
  {
    id: "cjb30", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "전화요금 50,000원이 보통예금에서 자동이체 되었다.",
    debit: [{ account: "통신비", amount: 50000 }],
    credit: [{ account: "보통예금", amount: 50000 }],
    distractors: ["수도광열비", "현금"],
    explanation: "통신비(비용) 발생, 보통예금(자산) 감소.",
    hint: "전화요금, 인터넷비용 등은 통신비 계정을 사용합니다.",
  },
  {
    id: "cjb31", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "전기요금 120,000원을 현금으로 납부하였다.",
    debit: [{ account: "수도광열비", amount: 120000 }],
    credit: [{ account: "현금", amount: 120000 }],
    distractors: ["통신비", "미지급비용"],
    explanation: "수도광열비(비용) 발생, 현금(자산) 감소.",
    hint: "전기, 수도, 가스요금은 수도광열비 계정을 사용합니다.",
  },
  {
    id: "cjb32", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "받을어음 1,000,000원이 만기되어 보통예금에 입금되었다.",
    debit: [{ account: "보통예금", amount: 1000000 }],
    credit: [{ account: "받을어음", amount: 1000000 }],
    distractors: ["현금", "외상매출금"],
    explanation: "어음 만기 회수: 보통예금(자산) 증가, 받을어음(자산) 감소.",
    hint: "만기된 어음을 회수하면 받을어음이 줄어듭니다.",
  },
  {
    id: "cjb33", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "지급어음 800,000원이 만기되어 보통예금에서 결제되었다.",
    debit: [{ account: "지급어음", amount: 800000 }],
    credit: [{ account: "보통예금", amount: 800000 }],
    distractors: ["외상매입금", "현금"],
    explanation: "지급어음(부채) 감소, 보통예금(자산) 감소.",
    hint: "만기된 어음을 결제하면 지급어음 부채가 사라집니다.",
  },
  {
    id: "cjb34", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "건물 수선비 400,000원을 현금으로 지급하였다.",
    debit: [{ account: "수선비", amount: 400000 }],
    credit: [{ account: "현금", amount: 400000 }],
    distractors: ["건물", "미지급금"],
    explanation: "유지보수 목적의 수선은 수선비(비용)로 처리. 자산 가치 향상 목적이면 자본적 지출로 자산화.",
    hint: "단순 유지보수 목적의 수선은 비용으로 처리합니다.",
  },
  {
    id: "cjb35", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "현금 300,000원을 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 300000 }],
    credit: [{ account: "현금", amount: 300000 }],
    distractors: ["단기차입금"],
    explanation: "보통예금(자산) 증가, 현금(자산) 감소. 자산 내 대체 거래.",
    hint: "현금을 은행에 입금하면 자산의 종류가 바뀝니다.",
  },
  {
    id: "cjb36", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "거래처 접대비 150,000원을 현금으로 지출하였다.",
    debit: [{ account: "접대비", amount: 150000 }],
    credit: [{ account: "현금", amount: 150000 }],
    distractors: ["광고선전비", "미지급비용"],
    explanation: "접대비(비용) 발생, 현금(자산) 감소.",
    hint: "거래처 식사, 선물 등은 접대비 계정을 사용합니다.",
  },
  {
    id: "cjb37", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "단기대여금에 대한 이자 30,000원을 현금으로 수취하였다.",
    debit: [{ account: "현금", amount: 30000 }],
    credit: [{ account: "이자수익", amount: 30000 }],
    distractors: ["미수수익", "이자비용"],
    explanation: "현금(자산) 증가, 이자수익(수익) 발생.",
    hint: "돈을 빌려주고 받는 이자는 이자수익입니다.",
  },
  {
    id: "cjb38", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "복리후생비 200,000원을 현금으로 지급하였다. (직원 식대)",
    debit: [{ account: "복리후생비", amount: 200000 }],
    credit: [{ account: "현금", amount: 200000 }],
    distractors: ["급여", "미지급비용"],
    explanation: "복리후생비(비용) 발생, 현금(자산) 감소.",
    hint: "직원 식대, 경조사비 등은 복리후생비 계정을 사용합니다.",
  },
  {
    id: "cjb39", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "단기차입금에 대한 이자 60,000원이 미지급 상태이다. (결산 수정)",
    debit: [{ account: "이자비용", amount: 60000 }],
    credit: [{ account: "미지급비용", amount: 60000 }],
    distractors: ["이자수익", "미지급금"],
    explanation: "결산 수정: 이자비용(비용) 발생 인식, 미지급비용(부채) 계상.",
    hint: "아직 지급하지 않은 이자도 발생주의에 따라 비용으로 인식합니다.",
  },
  {
    id: "cjb40", type: "journal", standard: "common", category: "journal-basic", difficulty: "basic",
    text: "미수수익 50,000원을 현금으로 수취하였다.",
    debit: [{ account: "현금", amount: 50000 }],
    credit: [{ account: "미수수익", amount: 50000 }],
    distractors: ["보통예금", "이자수익"],
    explanation: "현금(자산) 증가, 미수수익(자산) 감소. 이미 수익으로 인식한 금액을 실제 회수.",
    hint: "이미 수익으로 인식된 미수수익을 받으면 자산 간 대체입니다.",
  },
  {
    id: "cji11", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "법인세 중간예납액 500,000원을 보통예금에서 납부하였다.",
    debit: [{ account: "선급법인세", amount: 500000 }],
    credit: [{ account: "보통예금", amount: 500000 }],
    distractors: ["법인세비용", "현금", "미지급세금"],
    explanation: "중간예납은 선급법인세(자산)로 처리. 결산 시 법인세비용과 상계.",
    hint: "미리 납부한 세금은 자산(선급법인세)으로 처리합니다.",
  },
  {
    id: "cji12", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "결산 시 법인세비용 2,000,000원을 계상하였다. (선급법인세 500,000원 있음)",
    debit: [{ account: "법인세비용", amount: 2000000 }],
    credit: [{ account: "선급법인세", amount: 500000 }, { account: "미지급세금", amount: 1500000 }],
    distractors: ["보통예금"],
    explanation: "법인세비용(비용) 2,000,000 = 선급법인세(자산) 500,000 상계 + 미지급세금(부채) 1,500,000.",
    hint: "법인세비용에서 이미 낸 선급법인세를 차감한 나머지가 미지급세금입니다.",
  },
  {
    id: "cji13", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "외상매출금 300,000원이 대손 확정되어 제각하였다. (대손충당금 잔액 200,000원 있음)",
    debit: [{ account: "대손충당금", amount: 200000 }, { account: "대손상각비", amount: 100000 }],
    credit: [{ account: "외상매출금", amount: 300000 }],
    distractors: ["현금"],
    explanation: "대손충당금 200,000 먼저 상계. 부족분 100,000은 대손상각비(비용)로 추가 인식.",
    hint: "대손충당금이 있으면 먼저 상계하고, 부족하면 비용으로 처리합니다.",
  },
  {
    id: "cji14", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "전기에 대손 처리한 외상매출금 100,000원이 현금으로 회수되었다. (2단계 처리: ① 채권 복구 ② 현금 회수)",
    debit: [{ account: "외상매출금", amount: 100000 }, { account: "현금", amount: 100000 }],
    credit: [{ account: "대손충당금", amount: 100000 }, { account: "외상매출금", amount: 100000 }],
    distractors: ["대손상각비"],
    explanation: "① 채권 복구: (차) 외상매출금 / (대) 대손충당금. ② 현금 회수: (차) 현금 / (대) 외상매출금. 대손상각비 환입이 아닌 대손충당금 복구.",
    hint: "대손 회수는 채권을 먼저 복구한 뒤 현금으로 받는 2단계로 처리합니다.",
  },
  {
    id: "cji15", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "결산 시 임차료 선급분 60,000원을 차기로 이연하였다.",
    debit: [{ account: "선급비용", amount: 60000 }],
    credit: [{ account: "임차료", amount: 60000 }],
    distractors: ["선급금", "선수수익"],
    explanation: "차기 해당분 임차료를 선급비용(자산)으로 이연. 비용 감소.",
    hint: "차기에 해당하는 비용은 선급비용으로 이연합니다.",
  },
  {
    id: "cji16", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "결산 시 미수이자 40,000원을 계상하였다.",
    debit: [{ account: "미수수익", amount: 40000 }],
    credit: [{ account: "이자수익", amount: 40000 }],
    distractors: ["이자비용", "선급비용"],
    explanation: "발생주의: 아직 못 받은 이자도 이자수익(수익) 인식, 미수수익(자산) 계상.",
    hint: "받지 않았어도 기간이 경과한 이자는 수익으로 인식합니다.",
  },
  {
    id: "cji17", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "건물에 엘리베이터를 추가 설치하여 5,000,000원을 보통예금으로 지급하였다. (자본적 지출)",
    debit: [{ account: "건물", amount: 5000000 }],
    credit: [{ account: "보통예금", amount: 5000000 }],
    distractors: ["수선비", "미지급금"],
    explanation: "자산 가치 증가 지출(자본적 지출)은 자산으로 처리. 수선비(수익적 지출)와 구분.",
    hint: "자산의 가치나 내용연수를 늘리는 지출은 자산으로 처리합니다.",
  },
  {
    id: "cji18", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "유상증자로 보통주 1,000주를 주당 5,000원에 발행하고 보통예금에 입금하였다. (액면가 1,000원)",
    debit: [{ account: "보통예금", amount: 5000000 }],
    credit: [{ account: "자본금", amount: 1000000 }, { account: "주식발행초과금", amount: 4000000 }],
    distractors: ["이익잉여금", "현금"],
    explanation: "액면가 1,000 × 1,000주 = 자본금 1,000,000. 초과분 4,000,000 = 주식발행초과금(자본잉여금).",
    hint: "발행금액에서 액면가를 빼면 주식발행초과금입니다.",
  },
  {
    id: "cji19", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "토지(장부가액 10,000,000원)를 12,000,000원에 현금으로 처분하였다.",
    debit: [{ account: "현금", amount: 12000000 }],
    credit: [{ account: "토지", amount: 10000000 }, { account: "유형자산처분이익", amount: 2000000 }],
    distractors: ["유형자산처분손실"],
    explanation: "처분가 12,000,000 > 장부가 10,000,000 → 처분이익 2,000,000.",
    hint: "처분가액이 장부가액보다 크면 처분이익입니다.",
  },
  {
    id: "cji20", type: "journal", standard: "common", category: "journal-intermediate", difficulty: "intermediate",
    text: "상품권 300,000원을 현금으로 발행하였다.",
    debit: [{ account: "현금", amount: 300000 }],
    credit: [{ account: "선수금", amount: 300000 }],
    distractors: ["매출", "선수수익"],
    explanation: "상품권 발행: 현금(자산) 증가, 선수금(부채) 증가. 상품권 사용 시 매출 인식.",
    hint: "상품권은 아직 상품을 제공하지 않았으므로 부채입니다.",
  },
  {
    id: "cox11", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "소모품을 구입하면 무조건 비용으로 처리한다.",
    answer: false,
    explanation: "소모품 구입 시 자산(소모품)으로 처리하고, 사용 시 비용(소모품비)으로 대체합니다.",
    hint: "구입과 사용은 다른 시점입니다.",
  },
  {
    id: "cox12", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "복식부기에서 모든 거래는 차변과 대변 양쪽에 동시에 기록된다.",
    answer: true,
    explanation: "복식부기의 핵심 원리. 하나의 거래가 차변과 대변에 동일 금액으로 기록됩니다.",
    hint: "복식부기에서 거래는 항상 두 계정에 영향을 줍니다.",
  },
  {
    id: "cox13", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "자본금은 자산 계정이다.",
    answer: false,
    explanation: "자본금은 자본 계정입니다. 자산 = 부채 + 자본 관계에서 자본에 해당합니다.",
    hint: "재무상태표 오른쪽에 있는 항목을 생각해보세요.",
  },
  {
    id: "cox14", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "손익계산서는 일정 기간의 수익과 비용을 나타낸다.",
    answer: true,
    explanation: "손익계산서는 기간 재무제표. 재무상태표는 시점 재무제표입니다.",
    hint: "손익계산서는 '기간' 동안의 경영 성과를 보여줍니다.",
  },
  {
    id: "cox15", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "미지급금과 미지급비용은 같은 계정이다.",
    answer: false,
    explanation: "미지급금은 상품 외 자산 구입 대금, 미지급비용은 발생했으나 지급하지 않은 비용입니다.",
    hint: "미지급금은 구입 거래, 미지급비용은 발생주의 관련 계정입니다.",
  },
  {
    id: "cox16", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "수익은 발생 시 대변에 기록한다.",
    answer: true,
    explanation: "수익 발생은 대변. 수익 취소는 차변에 기록합니다.",
    hint: "수익과 부채는 같은 쪽(대변)에서 증가합니다.",
  },
  {
    id: "cox17", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "선수금은 자산 계정이다.",
    answer: false,
    explanation: "선수금은 미래에 상품/서비스를 제공해야 하는 의무이므로 부채 계정입니다.",
    hint: "받은 돈에 대해 아직 의무가 남아있으면 부채입니다.",
  },
  {
    id: "cox18", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "발생주의 회계에서 현금 수령 시점에 수익을 인식한다.",
    answer: false,
    explanation: "발생주의는 현금 수수와 관계없이 수익/비용이 발생한 시점에 인식합니다. 현금주의와 반대.",
    hint: "발생주의는 현금 흐름이 아닌 경제적 사건 발생 시점 기준입니다.",
  },
  {
    id: "cox19", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "대손충당금은 매출채권(외상매출금)에서 차감하는 형식으로 표시한다.",
    answer: true,
    explanation: "대손충당금은 자산의 차감 계정. 재무상태표에서 외상매출금에서 차감하여 순액 표시.",
    hint: "대손충당금은 자산을 줄이는 역할을 합니다.",
  },
  {
    id: "cox20", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "자본적 지출은 당기 비용으로 처리한다.",
    answer: false,
    explanation: "자본적 지출은 자산으로 처리 후 감가상각합니다. 수익적 지출이 당기 비용입니다.",
    hint: "자산 가치를 높이는 지출은 자산으로, 단순 유지는 비용으로 처리합니다.",
  },
  {
    id: "cox21", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "이익잉여금은 수익 계정이다.",
    answer: false,
    explanation: "이익잉여금은 자본 계정입니다. 누적된 이익이 자본으로 쌓인 것입니다.",
    hint: "이익잉여금은 재무상태표의 자본 항목에 표시됩니다.",
  },
  {
    id: "cox22", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "미수수익은 부채 계정이다.",
    answer: false,
    explanation: "미수수익은 이미 발생했지만 아직 받지 못한 수익으로 자산 계정입니다.",
    hint: "받아야 할 것은 자산, 줘야 할 것은 부채입니다.",
  },
  {
    id: "cox23", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "유형자산 처분 시 처분가액이 장부가액보다 작으면 처분이익이 발생한다.",
    answer: false,
    explanation: "처분가액 < 장부가액 → 처분손실. 처분가액 > 장부가액 → 처분이익.",
    hint: "비싸게 팔면 이익, 싸게 팔면 손실입니다.",
  },
  {
    id: "cox24", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "주식발행초과금은 자본잉여금에 해당한다.",
    answer: true,
    explanation: "주식발행초과금은 액면가 초과 발행 금액으로 자본잉여금에 포함됩니다.",
    hint: "자본잉여금은 주주와의 거래에서 발생하는 자본입니다.",
  },
  {
    id: "cox25", type: "ox", standard: "common", category: "ox-basic", difficulty: "basic",
    text: "받을어음과 지급어음은 모두 자산 계정이다.",
    answer: false,
    explanation: "받을어음은 자산(받아야 할 것), 지급어음은 부채(줘야 할 것)입니다.",
    hint: "어음의 방향을 생각해보세요. 받는 건 자산, 주는 건 부채.",
  },
  {
    id: "ccalc01", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "기초 자산 5,000,000원, 기초 부채 2,000,000원, 당기 순이익 1,000,000원, 배당금 지급 200,000원일 때 기말 자본은?",
    correctAnswer: 3800000,
    explanation: "기초 자본 = 5,000,000 - 2,000,000 = 3,000,000. 기말 자본 = 3,000,000 + 1,000,000 - 200,000 = 3,800,000.",
    hint: "자본 = 자산 - 부채. 당기 순이익은 자본을 늘리고, 배당금은 자본을 줄입니다.",
  },
  {
    id: "ccalc02", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "매출액 10,000,000원, 매출원가 6,000,000원, 판관비 2,000,000원일 때 영업이익은?",
    correctAnswer: 2000000,
    explanation: "매출총이익 = 10,000,000 - 6,000,000 = 4,000,000. 영업이익 = 4,000,000 - 2,000,000 = 2,000,000.",
    hint: "영업이익 = 매출액 - 매출원가 - 판매관리비",
  },
  {
    id: "ccalc03", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "취득원가 3,000,000원, 잔존가치 300,000원, 내용연수 5년인 유형자산의 정액법 감가상각비는?",
    correctAnswer: 540000,
    explanation: "정액법 = (3,000,000 - 300,000) / 5 = 540,000원/년.",
    hint: "정액법: (취득원가 - 잔존가치) ÷ 내용연수",
  },
  {
    id: "ccalc04", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "외상매출금 기초 잔액 500,000원, 당기 외상매출 2,000,000원, 당기 회수액 1,800,000원일 때 기말 외상매출금 잔액은?",
    correctAnswer: 700000,
    explanation: "기말 = 500,000 + 2,000,000 - 1,800,000 = 700,000원.",
    hint: "기말 잔액 = 기초 잔액 + 발생액 - 회수액",
  },
  {
    id: "ccalc05", type: "calculation", standard: "common", category: "calc-basic", difficulty: "basic",
    text: "기초 재고 200,000원, 당기 매입 800,000원, 기말 재고 150,000원일 때 매출원가는?",
    correctAnswer: 850000,
    explanation: "매출원가 = 200,000 + 800,000 - 150,000 = 850,000원.",
    hint: "매출원가 = 기초재고 + 당기매입 - 기말재고",
  },
  {
    id: "kb11", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매출채권 3,000,000원에 대해 대손충당금 150,000원을 설정하였다.",
    debit: [{ account: "대손상각비", amount: 150000 }],
    credit: [{ account: "대손충당금", amount: 150000 }],
    distractors: ["매출채권", "미지급비용"],
    explanation: "K-IFRS: 기대신용손실 모형에 따라 대손상각비(비용) 인식, 대손충당금(차감계정) 설정.",
    hint: "K-IFRS는 손실이 발생하기 전에 미리 기대신용손실을 인식합니다.",
  },
  {
    id: "kb12", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "당기손익-공정가치측정 금융자산(주식) 1,000,000원을 현금으로 취득하였다.",
    debit: [{ account: "당기손익-공정가치측정금융자산", amount: 1000000 }],
    credit: [{ account: "현금", amount: 1000000 }],
    distractors: ["매도가능금융자산", "보통예금"],
    explanation: "K-IFRS 9: 단기 매매 목적 금융자산은 당기손익-공정가치측정(FVTPL)으로 분류.",
    hint: "K-IFRS 9에서 금융자산 분류는 사업모형과 현금흐름 특성에 따릅니다.",
  },
  {
    id: "kb13", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "보유 중인 FVTPL 금융자산의 공정가치가 200,000원 상승하였다.",
    debit: [{ account: "당기손익-공정가치측정금융자산", amount: 200000 }],
    credit: [{ account: "금융자산평가이익", amount: 200000 }],
    distractors: ["기타포괄손익", "미실현이익"],
    explanation: "FVTPL 금융자산 평가이익은 당기손익(수익)으로 인식. 기타포괄손익 아님.",
    hint: "FVTPL은 평가손익이 당기손익에 반영됩니다.",
  },
  {
    id: "kb14", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "사채 10,000,000원을 액면발행하고 보통예금에 입금하였다.",
    debit: [{ account: "보통예금", amount: 10000000 }],
    credit: [{ account: "사채", amount: 10000000 }],
    distractors: ["장기차입금", "현금"],
    explanation: "사채 액면발행: 발행금액 = 액면금액. 보통예금(자산) 증가, 사채(부채) 증가.",
    hint: "사채는 회사채로 장기 부채입니다.",
  },
  {
    id: "kb15", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "무형자산(특허권) 2,000,000원을 현금으로 취득하였다.",
    debit: [{ account: "특허권", amount: 2000000 }],
    credit: [{ account: "현금", amount: 2000000 }],
    distractors: ["연구비", "개발비"],
    explanation: "외부 구입한 특허권은 무형자산으로 인식. 취득원가로 측정.",
    hint: "외부에서 구입한 무형자산은 취득원가로 자산 인식합니다.",
  },
  {
    id: "kb16", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "개발단계 지출 500,000원을 현금으로 지급하였다. (자산인식 요건 충족)",
    debit: [{ account: "개발비", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["연구비", "무형자산"],
    explanation: "K-IFRS: 개발단계 지출은 요건 충족 시 무형자산(개발비)으로 인식. 연구단계는 전액 비용.",
    hint: "연구단계는 비용, 개발단계는 요건 충족 시 자산입니다.",
  },
  {
    id: "kb17", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "유형자산을 재평가모형으로 평가하여 공정가치가 장부가액보다 1,000,000원 증가하였다.",
    debit: [{ account: "유형자산", amount: 1000000 }],
    credit: [{ account: "재평가잉여금", amount: 1000000 }],
    distractors: ["유형자산평가이익", "기타포괄손익"],
    explanation: "재평가 증가분은 기타포괄손익(재평가잉여금, 자본)으로 인식. 당기손익 아님.",
    hint: "유형자산 재평가이익은 당기손익이 아닌 기타포괄손익으로 처리합니다.",
  },
  {
    id: "kb18", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "리스료 1,200,000원을 보통예금에서 지급하였다. (리스부채 원금 1,000,000원, 이자 200,000원)",
    debit: [{ account: "리스부채", amount: 1000000 }, { account: "이자비용", amount: 200000 }],
    credit: [{ account: "보통예금", amount: 1200000 }],
    distractors: ["임차료", "사용권자산"],
    explanation: "리스료 지급 = 원금 상환(리스부채 감소) + 이자비용 인식. IFRS 16 적용.",
    hint: "리스료는 원금과 이자로 나뉩니다.",
  },
  {
    id: "kb19", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "투자부동산(공정가치모형) 공정가치가 5,000,000원에서 5,500,000원으로 증가하였다.",
    debit: [{ account: "투자부동산", amount: 500000 }],
    credit: [{ account: "투자부동산평가이익", amount: 500000 }],
    distractors: ["재평가잉여금", "기타포괄손익"],
    explanation: "투자부동산 공정가치모형: 평가손익을 당기손익으로 인식. 재평가잉여금(기타포괄) 아님.",
    hint: "투자부동산 공정가치모형의 평가손익은 당기손익입니다.",
  },
  {
    id: "kb20", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "전환사채 5,000,000원이 주식으로 전환되었다. (자본금 3,000,000원, 주식발행초과금 2,000,000원)",
    debit: [{ account: "전환사채", amount: 5000000 }],
    credit: [{ account: "자본금", amount: 3000000 }, { account: "주식발행초과금", amount: 2000000 }],
    distractors: ["사채"],
    explanation: "전환사채(부채) 감소, 자본금 + 주식발행초과금(자본) 증가. 부채의 자본 전환.",
    hint: "전환사채가 주식으로 바뀌면 부채가 자본이 됩니다.",
  },
  {
    id: "kb21", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "종업원급여 중 확정급여채무 1,000,000원을 인식하였다.",
    debit: [{ account: "퇴직급여", amount: 1000000 }],
    credit: [{ account: "확정급여채무", amount: 1000000 }],
    distractors: ["퇴직급여충당부채", "예수금"],
    explanation: "K-IFRS 19: 확정급여제도에서 퇴직급여(비용) 인식, 확정급여채무(부채) 계상.",
    hint: "K-IFRS에서는 퇴직급여충당부채 대신 확정급여채무를 사용합니다.",
  },
  {
    id: "kb22", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "금융리스 이용자로서 리스개시일에 사용권자산과 리스부채를 10,000,000원으로 인식하였다.",
    debit: [{ account: "사용권자산", amount: 10000000 }],
    credit: [{ account: "리스부채", amount: 10000000 }],
    distractors: ["임차료", "장기차입금"],
    explanation: "IFRS 16: 리스개시일에 사용권자산(자산)과 리스부채(부채)를 동시에 인식.",
    hint: "IFRS 16에서 리스는 자산과 부채를 동시에 인식합니다.",
  },
  {
    id: "kb23", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "연구단계 지출 800,000원을 현금으로 지급하였다.",
    debit: [{ account: "연구비", amount: 800000 }],
    credit: [{ account: "현금", amount: 800000 }],
    distractors: ["개발비", "무형자산"],
    explanation: "K-IFRS: 연구단계 지출은 전액 당기비용. 개발단계와 달리 자산화 불가.",
    hint: "연구단계는 항상 비용입니다.",
  },
  {
    id: "kb24", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "매출채권 2,000,000원을 팩토링(양도)하고 현금 1,900,000원을 수취하였다. (위험과 보상이 이전되어 제거 조건 충족)",
    debit: [{ account: "현금", amount: 1900000 }, { account: "매출채권처분손실", amount: 100000 }],
    credit: [{ account: "매출채권", amount: 2000000 }],
    distractors: ["단기차입금"],
    explanation: "매출채권 양도: 현금 수취 + 처분손실 인식. 차이 100,000원은 처분손실.",
    hint: "매출채권 양도 시 수취액과 장부가액의 차이는 손익입니다.",
  },
  {
    id: "kb25", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "자기주식 500,000원을 현금으로 취득하였다.",
    debit: [{ account: "자기주식", amount: 500000 }],
    credit: [{ account: "현금", amount: 500000 }],
    distractors: ["투자자산", "이익잉여금"],
    explanation: "자기주식은 자본의 차감 계정. 자산이 아닌 자본(마이너스)으로 처리.",
    hint: "자기주식은 자본을 줄이는 계정입니다.",
  },
  {
    id: "kb26", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "유형자산 손상차손 300,000원을 인식하였다.",
    debit: [{ account: "손상차손", amount: 300000 }],
    credit: [{ account: "유형자산", amount: 300000 }],
    distractors: ["감가상각비", "유형자산처분손실"],
    explanation: "K-IFRS 36: 자산 회수가능액이 장부가액 미만이면 손상차손(비용) 인식.",
    hint: "손상은 자산 가치가 기대보다 크게 하락할 때 인식합니다.",
  },
  {
    id: "kb27", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "외화매출채권 $10,000(환율: 1,200원)을 결제일에 회수하였다. (장부상 환율 1,100원)",
    debit: [{ account: "현금", amount: 12000000 }],
    credit: [{ account: "매출채권", amount: 11000000 }, { account: "외환차익", amount: 1000000 }],
    distractors: ["외환차손"],
    explanation: "결제일 환율(1,200) > 장부 환율(1,100) → 외환차익 1,000,000. $10,000 × (1,200-1,100) = 1,000,000.",
    hint: "결제 시점 환율이 장부 환율보다 높으면 외환차익입니다.",
  },
  {
    id: "kb28", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "정부보조금 2,000,000원을 수령하여 보통예금에 입금하였다. (자산 관련 보조금)",
    debit: [{ account: "보통예금", amount: 2000000 }],
    credit: [{ account: "이연정부보조금", amount: 2000000 }],
    distractors: ["정부보조금수익", "이익잉여금"],
    explanation: "자산 관련 정부보조금: 이연정부보조금(부채)으로 처리 후 자산 내용연수에 걸쳐 수익 인식.",
    hint: "자산 관련 정부보조금은 즉시 수익이 아니라 이연정부보조금(부채)으로 처리합니다.",
  },
  {
    id: "kb29", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "주식결제형 주식기준보상 100,000원을 인식하였다.",
    debit: [{ account: "주식보상비용", amount: 100000 }],
    credit: [{ account: "주식선택권", amount: 100000 }],
    distractors: ["미지급비용", "급여"],
    explanation: "K-IFRS 2: 주식결제형 주식기준보상은 주식보상비용(비용) + 주식선택권(자본).",
    hint: "주식으로 결제하는 보상은 자본을 증가시킵니다.",
  },
  {
    id: "kb30", type: "journal", standard: "k-ifrs", category: "kifrs-basic", difficulty: "basic",
    text: "리스부채 잔액 8,000,000원에 대한 이자비용(유효이자율 5%)을 인식하였다.",
    debit: [{ account: "이자비용", amount: 400000 }],
    credit: [{ account: "리스부채", amount: 400000 }],
    distractors: ["사용권자산", "임차료"],
    explanation: "유효이자법: 이자비용 = 8,000,000 × 5% = 400,000. 리스부채 장부가액 증가.",
    hint: "이자비용은 리스부채 잔액에 유효이자율을 곱해 계산합니다.",
  },
  {
    id: "kox11", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 연구단계 지출은 무형자산으로 인식할 수 없다.",
    answer: true,
    explanation: "연구단계 지출은 전액 비용 처리. 개발단계만 요건 충족 시 무형자산 인식 가능.",
    hint: "연구는 비용, 개발은 조건부 자산입니다.",
  },
  {
    id: "kox12", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "IFRS 16에서 리스이용자는 단기리스와 소액자산 리스에 대해 면제 규정을 적용할 수 있다.",
    answer: true,
    explanation: "단기리스(12개월 이하)와 소액자산 리스는 사용권자산/리스부채 인식 면제. 임차료로 처리 가능.",
    hint: "IFRS 16은 단기리스와 소액 리스에 대한 예외를 허용합니다.",
  },
  {
    id: "kox13", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 투자부동산에 공정가치모형을 적용하면 감가상각을 인식한다.",
    answer: false,
    explanation: "공정가치모형 적용 시 감가상각 불필요. 원가모형 적용 시에만 감가상각 인식.",
    hint: "공정가치로 측정하면 이미 가치 변동이 반영되므로 감가상각이 필요 없습니다.",
  },
  {
    id: "kox14", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "자기주식은 K-IFRS에서 자산으로 분류된다.",
    answer: false,
    explanation: "자기주식은 자본의 차감 항목으로 분류. 자산이 아닙니다.",
    hint: "회사가 자신의 주식을 사면 자본이 줄어듭니다.",
  },
  {
    id: "kox15", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 유형자산은 원가모형과 재평가모형 중 하나를 선택할 수 있다.",
    answer: true,
    explanation: "유형자산 측정 모형은 원가모형 또는 재평가모형 중 선택. 동일 분류 내 일관 적용.",
    hint: "K-IFRS는 유형자산에 대해 두 가지 측정 모형을 허용합니다.",
  },
  {
    id: "kox16", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 재평가잉여금은 당기손익으로 처리된다.",
    answer: false,
    explanation: "재평가잉여금은 기타포괄손익으로 처리. 당기손익에 포함되지 않습니다.",
    hint: "재평가이익은 포괄손익계산서에서 기타포괄손익 항목입니다.",
  },
  {
    id: "kox17", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS 9에서 FVTPL 금융자산의 평가손익은 당기손익으로 인식한다.",
    answer: true,
    explanation: "FVTPL(당기손익-공정가치측정) 금융자산은 평가손익 전액 당기손익 반영.",
    hint: "FVTPL은 공정가치 변동이 바로 손익에 반영됩니다.",
  },
  {
    id: "kox18", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 손상차손 환입은 항상 허용된다.",
    answer: false,
    explanation: "영업권의 손상차손은 환입 불가. 기타 자산은 환입 가능.",
    hint: "영업권 손상차손은 한번 인식하면 되돌릴 수 없습니다.",
  },
  {
    id: "kox19", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 외화환산손익은 기타포괄손익으로 처리한다.",
    answer: false,
    explanation: "화폐성 항목의 외화환산손익은 당기손익. 기타포괄손익이 아닙니다.",
    hint: "외화환산손익은 일반적으로 당기손익입니다.",
  },
  {
    id: "kox20", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 충당부채는 현재의무, 경제적 효익 유출 가능성, 신뢰성 있는 추정 세 가지 요건을 모두 충족해야 인식한다.",
    answer: true,
    explanation: "충당부채 인식 3요건: ① 현재의무 ② 경제적 효익 유출 가능 ③ 금액 신뢰성 추정 가능.",
    hint: "충당부채는 세 가지 조건을 모두 충족해야 합니다.",
  },
  {
    id: "kox21", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 리스이용자는 리스기간이 12개월을 초과하면 무조건 사용권자산을 인식해야 한다.",
    answer: false,
    explanation: "소액자산 리스는 리스기간과 무관하게 면제 가능. 12개월 기준은 단기리스에 해당.",
    hint: "소액자산 리스는 기간과 무관하게 면제됩니다.",
  },
  {
    id: "kox22", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 수익은 고객에게 통제가 이전될 때 인식한다.",
    answer: true,
    explanation: "K-IFRS 15: 수익인식 5단계 모형에서 핵심은 고객에게 통제가 이전되는 시점.",
    hint: "K-IFRS 15에서 수익 인식의 핵심은 '통제의 이전'입니다.",
  },
  {
    id: "kox23", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 전환사채의 전환권은 부채로 분류한다.",
    answer: false,
    explanation: "전환사채의 전환권(자본요소)은 자본으로 분류. 부채요소(사채)와 자본요소(전환권)로 분리.",
    hint: "전환사채는 부채요소와 자본요소로 분리합니다.",
  },
  {
    id: "kox24", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 기타포괄손익은 나중에 당기손익으로 재분류될 수 있는 항목과 그렇지 않은 항목으로 구분된다.",
    answer: true,
    explanation: "재분류 가능: 해외사업환산차이, FVOCI 채무상품 등. 재분류 불가: 재평가잉여금, FVOCI 지분상품 등.",
    hint: "기타포괄손익은 재분류 가능 여부에 따라 두 가지로 구분됩니다.",
  },
  {
    id: "kox25", type: "ox", standard: "k-ifrs", category: "ox-basic", difficulty: "basic",
    text: "K-IFRS에서 영업권은 상각하지 않고 매년 손상검사를 실시한다.",
    answer: true,
    explanation: "K-IFRS: 영업권은 비상각 자산. 매년 또는 손상 징후 시 손상검사 실시.",
    hint: "영업권은 상각하지 않고 손상 여부만 검토합니다.",
  },
  {
    id: "kcalc01", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "리스부채 잔액 10,000,000원, 유효이자율 연 6%, 연간 리스료 3,000,000원일 때 1년 후 리스부채 잔액은?",
    correctAnswer: 7600000,
    explanation: "이자비용 = 10,000,000 × 6% = 600,000. 원금 상환 = 3,000,000 - 600,000 = 2,400,000. 기말 리스부채 = 10,000,000 - 2,400,000 = 7,600,000.",
    hint: "리스료 = 이자 + 원금상환. 원금상환액만큼 부채가 줄어듭니다.",
  },
  {
    id: "kcalc02", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "취득원가 5,000,000원, 잔존가치 500,000원, 내용연수 5년인 사용권자산의 정액법 1년 감가상각비는?",
    correctAnswer: 900000,
    explanation: "(5,000,000 - 500,000) ÷ 5 = 900,000원.",
    hint: "사용권자산도 일반 유형자산과 동일하게 감가상각합니다.",
  },
  {
    id: "kcalc03", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "FVTPL 금융자산 취득원가 2,000,000원, 기말 공정가치 2,300,000원일 때 평가이익은?",
    correctAnswer: 300000,
    explanation: "평가이익 = 2,300,000 - 2,000,000 = 300,000원. FVTPL은 당기손익 반영.",
    hint: "공정가치 - 장부가액 = 평가손익",
  },
  {
    id: "kcalc04", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "유형자산 취득원가 10,000,000원, 감가상각누계액 3,000,000원, 회수가능액 6,500,000원일 때 손상차손은?",
    correctAnswer: 500000,
    explanation: "장부가액 = 10,000,000 - 3,000,000 = 7,000,000. 손상차손 = 7,000,000 - 6,500,000 = 500,000.",
    hint: "손상차손 = 장부가액 - 회수가능액",
  },
  {
    id: "kcalc05", type: "calculation", standard: "k-ifrs", category: "kifrs-calc", difficulty: "basic",
    text: "매출채권 잔액 5,000,000원에 대해 기대신용손실률 3%를 적용할 때 대손충당금 설정액은?",
    correctAnswer: 150000,
    explanation: "대손충당금 = 5,000,000 × 3% = 150,000원.",
    hint: "기대신용손실 = 매출채권 잔액 × 기대신용손실률",
  },
];
